const organismoCodigo = {
 "Administrador del Fondo Autónomo de Protección Previsional (FAPP)": "CO008",
 "Administradora de los Tribunales Tributarios y Aduaneros y del Tribunal de Contratación Pública": "AE013",
 "Agencia Chilena de Cooperación Internacional para el Desarrollo (AGCID)": "AC004",
 "Agencia Chilena de Eficiencia Energética": "FU014",
 "Agencia de Calidad de la Educación": "AJ012",
 "Agencia de Promoción de la Inversión Extranjera": "AH003",
 "Agencia Nacional de Investigación y Desarrollo (ANID)": "AJ008",
 "Agencia Nacional de Investigación y Desarrollo ANID": "AJ008",
 "Agencia Regional de Desarrollo Productivo de la Araucanía": "FU028",
 "Armada de Chile": "AD007",
 "Asociación Chilena de Municipalidades con Farmacias Populares (ACHIFARP)": "MA053",
 "Asociación Chilena de Municipalidades": "MA007",
 "Asociación Cultural Municipal de Cerrillos": "MA068",
 "Asociación de Gobernadores y Gobernadoras Regionales de Chile  AGORECHI": "FU025",
 "Asociación de Municipalidades Bio Bio Centro": "MA038",
 "Asociación de Municipalidades Comunas Costeras de PuchuncavíQuintero": "MA060",
 "Asociación de Municipalidades con Alcalde Mapuche": "MA026",
 "Asociación de Municipalidades con Centros de Montaña": "MA047",
 "Asociación de Municipalidades Cordilleranas de la Araucanía": "MA058",
 "Asociación de Municipalidades de Arauco y Curanilahue": "MA048",
 "Asociación de Municipalidades de Chile AMUCH": "MA018",
 "Asociación de Municipalidades de Ciudades Puerto y Borde Costero": "MA029",
 "Asociación de Municipalidades de la cuenca del Lago Llanquihue": "MA052",
 "Asociación de Municipalidades de la Provincia de Arauco": "MA015",
 "Asociación de Municipalidades de la Provincia de Osorno": "MA024",
 "Asociación de Municipalidades de la Provincia de San Antonio (AMPSA)": "MA061",
 "Asociación de Municipalidades de la Provincia del Huasco": "MA046",
 "Asociación de Municipalidades de la Región de  Coquimbo": "MA035",
 "Asociación de Municipalidades de la Región de Aconcagua": "MA016",
 "Asociación de Municipalidades de la Región de Antofagasta": "MA002",
 "Asociación de Municipalidades de la región de la araucanía o amra araucanía": "MA071",
 "Asociación de Municipalidades de la Región de Los Ríos para el Manejo sustentable de Residuos y la Gestión Ambiental": "MA005",
 "Asociación de Municipalidades de La Región de Los Ríos": "MA004",
 "Asociación de Municipalidades de la Región de OHiggins": "MA021",
 "Asociación de Municipalidades de la Región de Valparaíso": "MA023",
 "Asociación de Municipalidades de la Región del Biobío": "MA036",
 "Asociación de Municipalidades de la Zona Central y Costa (AMUCC)": "MA042",
 "Asociación de Municipalidades de la Zona Metropolitana de la Araucanía (AMZOMA)": "MA067",
 "Asociación de Municipalidades del Norte de Chile": "MA020",
 "Asociación de Municipalidades del Punilla": "MA022",
 "Asociación de Municipalidades del Valle del Itata": "MA040",
 "Asociación de Municipalidades del Valle del Maipo": "MA049",
 "Asociación de Municipalidades Desarrollo Apicultura Turismo y Medio Ambiente Zona de Amortiguación de la Región de Los Lagos": "MA017",
 "Asociación de Municipalidades Libres (AML)": "MA065",
 "Asociación de Municipalidades Malleco Norte AMMN": "MA008",
 "Asociación de Municipalidades Nahuelbuta (AMN)": "MA003",
 "Asociación de Municipalidades para el Desarrollo Económico Local": "MA010",
 "Asociación de Municipalidades para la Preservación de la Biodiversidad en el Territorio de Nonguén y otros Ecosistemas": "MA043",
 "Asociación de Municipalidades para la Seguridad Ciudadana Concón  Limache": "MA063",
 "Asociación de Municipalidades para la Seguridad Ciudadana en la Zona Oriente": "MA051",
 "Asociación de Municipalidades Parque Cordillera": "MA006",
 "Asociación de Municipalidades Red Nacional de Comunas Mágicas de Chile": "MA059",
 "Asociación de Municipalidades Región de Aysén": "MA039",
 "Asociación de Municipalidades Rurales (AMUR)": "MA001",
 "Asociación de Municipalidades Rurales del Norte Chico": "MA034",
 "Asociación de Municipalidades Territorio de Riego Canal LajaDiguillín": "MA011",
 "Asociación de Municipalidades Turísticas de Chile (AMTC)": "MA064",
 "Asociación de Municipios Ciudad Sur": "MA031",
 "Asociación de Municipios Cordillera de la Costa CorralLa Unión": "MA054",
 "Asociación de Municipios Cordilleranos AMCORDI": "MA037",
 "Asociación de Municipios Costa Araucanía": "MA033",
 "Asociación de Municipios de Desarrollo Intercomunal de Chiloé (AMUDICH)": "MA032",
 "Asociación de Municipios Metropolitanos para la Seguridad Ciudadana (AMMSeguridad)": "MA056",
 "Asociación de Municipios para el Desarrollo Turístico de las Comunas de Cabrero Los Ángeles y Yumbel": "MA055",
 "Asociación de Municipios para la Conservación de la Biodiversidad de la Región de Los Ríos": "MA012",
 "Asociación de Municipios para la seguridad comunitaria (AMSC)": "MA074",
 "Asociación de Municipios Rurales Regiones de Tarapacá y AricaParinacota": "MA013",
 "Asociación de municipios verdes araucanía sur  amvas": "MA075",
 "Asociación Metropolitana de Municipalidades de Santiago Sur para la Gestión Ambiental y de Residuos (Msur)": "MA050",
 "Asociación Municipal para la sustentabilidad ambiental AMUSA": "MA027",
 "Asociación Municipalidades Provincia de Llanquihue Para Manejo Sustentable de Residuos y Gestión Ambiental": "MA025",
 "Asociación Nacional de Municipalidades de Ciudades Puerto Concesionados": "MA044",
 "Asociación Regional de Municipalidades de Magallanes y Antártica Chilena (AMUMAG)": "MA019",
 "Asociación Regional de Municipios de Atacama": "MA014",
 "Asociación Special Olympics World Games Santiago Two Thousand TwentySeven Local Organizing Committee": "FU033",
 "Caja de Previsión de la Defensa Nacional (CAPREDENA)": "AD015",
 "Carabineros de Chile": "AD009",
 "Central de Abastecimiento del Sistema Nacional de Servicios de Salud (CENABAST)": "AO003",
 "Centro de Formación Técnica de la Región del Maule": "CF002",
 "Centro de Formación Técnica Estatal Región de Coquimbo": "CF006",
 "Centro de Información de Recursos Naturales (CIREN)": "AR010",
 "Centro de Referencia de Salud de Maipú (CRSM)": "AO015",
 "Centro de Referencia de Salud de Peñalolén Cordillera Oriente (CRSORIENTE)": "AO014",
 "Centro de Referencia de Salud Hospital Provincia Cordillera (hpcordillera)": "AO119",
 "CFT de la Región de Antofagasta": "CF009",
 "CFT de la Región de Arica y Parinacota": "CF012",
 "CFT de la Región de Atacama": "CF011",
 "CFT de la Región de la Araucanía": "CF001",
 "CFT de la Región de los Lagos": "CF005",
 "CFT de la Región de Los Ríos": "CF004",
 "CFT de la Región de OHiggins": "CF015",
 "CFT de la Región de Valparaíso": "CF007",
 "CFT de la Región del Tarapacá": "CF003",
 "CFT de la Región Metropolitana (CFTRM)": "CF008",
 "CFT Estatal de la Región de Aysén": "CF013",
 "CFT Estatal de la Región del Biobío": "CF014",
 "CFT Estatal de la Región del Maule": "CF002",
 "CFT Magallanes": "CF010",
 "CLUB DE LA REINA SOCIAL DEPORTIVO Y RECREACIONAL": "CM281",
 "Comercializadora de Trigo COTRISA": "EP029",
 "Comisión Administradora del Sistema de Créditos para Estudios Superiores (INGRESA)": "AJ004",
 "Comisión Chilena de Energía Nuclear (CCHEN)": "AU003",
 "Comisión Chilena del Cobre (COCHILCO)": "AS002",
 "Comisión del Sistema Nacional de Certificación de Competencias Laborales": "AL010",
 "Comisión Nacional de Acreditación (CNA)": "AZ001",
 "Comisión Nacional de Energía (CNE)": "AU001",
 "Comisión Nacional de Riego (CNR)": "AR002",
 "Comisión para el Mercado Financiero  CMF ex SVS": "AE009",
 "Consejo de Defensa del Estado (CDE)": "AX001",
 "Consejo de Rectores de las Universidades Chilenas (CRUCH)": "AJ002",
 "Consejo de Rectores": "AJ002",
 "Consejo Fiscal Autónomo": "CO006",
 "Consejo Nacional de Educación (CNED)": "AJ003",
 "Consejo Nacional de Televisión (CNTV)": "AG003",
 "Consejo para la Transparencia (CPLT)": "CT001",
 "Corporación Cultural Aldea del Encuentro La Reina": "CM065",
 "Corporación cultural de Ancud": "CM285",
 "Corporación Cultural de Antofagasta": "CM067",
 "Corporación Cultural de Estación Central": "CM069",
 "Corporación Cultural de la Comuna de La Granja": "CM070",
 "Corporación Cultural de La Ilustre Municipalidad de Romeral": "CM071",
 "Corporación Cultural de La Ilustre Municipalidad de Valdivia": "CM072",
 "Corporación Cultural de la Municipalidad de Curicó": "CM155",
 "Corporación Cultural de La Reina": "CM073",
 "Corporación Cultural de Lampa": "CM074",
 "Corporación Cultural de Las Condes": "CM075",
 "Corporación Cultural de Lo Barnechea": "CM076",
 "Corporación Cultural de Mostazal": "CM079",
 "Corporación Cultural de Nacimiento": "CM080",
 "Corporación Cultural de Osorno": "CM082",
 "Corporación Cultural de Peñalolén": "CM083",
 "Corporación Cultural de Recoleta": "CM086",
 "Corporación Cultural de San Pedro de La Paz": "CM087",
 "Corporación Cultural de Teno": "CM090",
 "Corporación Cultural de Vitacura": "CM092",
 "Corporación Cultural de Ñuñoa": "CM081",
 "Corporación Cultural Ilustre Municipalidad de Rauco": "CM158",
 "Corporación Cultural Isla de Maipo": "CM094",
 "Corporación Cultural Municipal de La Comuna de Chillán": "CM096",
 "Corporación Cultural Municipal de La Comuna de Villarrica": "CM098",
 "Corporación Cultural Municipal de Los Ángeles": "CM099",
 "Corporación Cultural Municipal de Ovalle": "CM100",
 "Corporación Cultural Municipal de Padre Las Casas": "CM101",
 "Corporación Cultural Municipal de Puente Alto": "CM103",
 "Corporación Cultural Municipal de San Javier de Loncomilla": "CM104",
 "Corporación Cultural Municipal de Vicuña": "CM091",
 "Corporación Cultural Municipalidad de Coyhaique": "CM106",
 "Corporación Cultural Municipalidad de Maule": "CM077",
 "Corporación Cultural San Francisco de El Monte": "CM296",
 "Corporación Cultural Social y Deportiva Municipal de Quilicura": "CM110",
 "Corporación Cultural y de Extensión de La Ilustre Municipalidad de Constitución": "CM108",
 "Corporación Cultural y de Turismo Municipal Pelarco": "CM109",
 "Corporación de Artes y Cultura de Colina": "CM114",
 "Corporación de Asistencia Judicial de la Región Metropolitana (CAJMETRO)": "AK008",
 "Corporación de Asistencia Judicial Regiones Tarapacá y Antofagasta (CAJTA)": "AK010",
 "Corporación de Asistencia Judicial Región Bío Bío (CAJBIOBIO)": "AK011",
 "Corporación de Asistencia Judicial Región Valparaíso (CAJVAL)": "AK009",
 "Corporación de Cultura de Pichidegua": "CM111",
 "Corporación de Cultura La Florida": "CM113",
 "Corporación de Cultura y Patrimonio de Independencia": "CM115",
 "Corporación de Cultura y Turismo de Calama": "CM116",
 "Corporación de Deporte de Estación Central Cormudep": "CM119",
 "Corporación de Deporte de Los Andes": "CM120",
 "Corporación de Deporte y Recreacion de La Municipalidad de Aysén": "CM144",
 "Corporación de Deporte y Recreación de Zapallar": "CM291",
 "Corporación de Deportes Constitución": "CM124",
 "Corporación de Deportes de la Ilustre Municipalidad de Curicó": "CM250",
 "Corporación de Deportes de La Ilustre Municipalidad de Teno": "CM126",
 "Corporación de Deportes de la Municipalidad de Independencia": "CM125",
 "Corporación de Deportes de Parral": "CM127",
 "Corporación de Deportes de Peñaflor": "CM295",
 "Corporación de Deportes de San Clemente": "CM283",
 "Corporación de Deportes La Florida": "CM129",
 "Corporación de Deportes y Recreación de Peñalolén": "CM133",
 "Corporación de Deportes y Recreación de San Javier Loncomilla": "CM230",
 "Corporación de Deportes y Recreación La Reina": "CM134",
 "Corporación de Deportes y Recreación Rapa Nui": "CM200",
 "Corporación de Desarrollo de Magallanes y de la Antártica chilena.": "FU026",
 "Corporación de Desarrollo de Talca": "CM135",
 "Corporación de Desarrollo e Innovación de Rancagua": "CM060",
 "Corporación de Desarrollo Social de Buin": "CM025",
 "Corporación de Desarrollo Social de Cerro Navia (CORMUCENA)": "CM022",
 "Corporación de Desarrollo Social de la Municipalidad de Independencia": "CM207",
 "Corporación de desarrollo territorial de la región de Arica y Parinacota": "FU023",
 "Corporación de Educación Salud y Atención de Menores Chonchi Chiloé": "CM020",
 "Corporación de Educación Salud y Menores de Puerto Natales": "CM045",
 "Corporación de Educación y Salud de Las Condes": "CM021",
 "Corporación de Fomento de Desarrollo comunal y Productivo de la Granja": "CM284",
 "Corporación de Fomento de la Producción (CORFO)": "AH004",
 "Corporación de Inclusión Social de Cerro Navia": "CM160",
 "Corporación de Innovación y Desarrollo Económico y Social Innova Recoleta": "CM141",
 "Corporación de investigación y avance de la Paleontología e historia natural de Atacama": "FU020",
 "Corporación de la Cultura y las Artes de la Ilustre Municipalidad de Rancagua": "CM058",
 "Corporación del Deporte de Lampa": "CM145",
 "Corporación del Deporte de Pichidegua": "CM146",
 "Corporación Deportiva Municipal de San Pedro de La Paz": "CM147",
 "Corporación Municipal Costa Chinchorro de Arica": "CM152",
 "Corporación Municipal Cultural Museo de Bellas Artes Valparaíso": "CM154",
 "Corporación Municipal Cultural y Patrimonial de San Bernardo": "CM055",
 "Corporación Municipal de Administración Sitio Patrimonio Mundial Área Histórica de la Cuidad Puerto de Valparaíso": "CM139",
 "Corporación Municipal de Ancud": "CM024",
 "Corporación Municipal de Calera De Tango": "CM035",
 "Corporación Municipal de Castro": "CM011",
 "Corporación Municipal de Colina": "CM026",
 "Corporación Municipal de cultura de Isla de Pascua": "CM235",
 "Corporación Municipal de Cultura de Paine": "CM165",
 "Corporación Municipal de Cultura de San Joaquín": "CM167",
 "Corporación Municipal de Cultura de Talca": "CM112",
 "Corporación Municipal de Cultura de TilTil": "CM258",
 "Corporación Municipal de Cultura La Pintana": "CM168",
 "Corporación Municipal de Cultura San Clemente": "CM191",
 "Corporación Municipal de Cultura Turismo y Patrimonio de La Comuna de Natales": "CM173",
 "Corporación Municipal de Cultura y Artes de Molina": "CM169",
 "Corporación Municipal de Cultura y Deportes de Recoleta": "CM086",
 "Corporación Municipal de Cultura y Turismo de La Comuna de Quintero": "CM171",
 "Corporación Municipal de Curaco De Velez": "CM037",
 "Corporación Municipal de Deporte de Padre Hurtado": "CM176",
 "Corporación Municipal de Deporte de Romeral": "CM177",
 "Corporación Municipal de Deporte Quinta Normal": "CM247",
 "Corporación Municipal de Deporte y Recreación de Recoleta": "CM180",
 "Corporación Municipal de Deportes de Caldera": "CM181",
 "Corporación Municipal de Deportes de Colina": "CM122",
 "Corporación Municipal de Deportes de Iquique (CORMUDEPI)": "CM062",
 "Corporación Municipal de Deportes de Lo Prado": "CM185",
 "Corporación Municipal de Deportes de Natales": "CM186",
 "Corporación Municipal de Deportes de Padre Las Casas": "CM187",
 "Corporación Municipal de Deportes de Puente Alto": "CM189",
 "Corporación Municipal de Deportes de Rancagua": "CM059",
 "Corporación Municipal de Deportes de San Joaquín": "CM253",
 "Corporación Municipal de Deportes de Talca": "CM128",
 "Corporación Municipal de Deportes de Ñuñoa": "CM063",
 "Corporación Municipal de Deportes La Pintana": "CM194",
 "Corporación Municipal de Deportes Recreación y Cultura de Coquimbo": "CM057",
 "Corporación Municipal de Deportes y Desarrollo Social de Quintero": "CM196",
 "Corporación Municipal de Deportes y Recreación de Antofagasta": "CM197",
 "Corporación Municipal de Deportes y Recreación de Coyhaique": "CM198",
 "Corporación Municipal de Deportes y Recreación de La Ilustre Municipalidad de Isla de Pascua": "CM200",
 "Corporación Municipal de Deportes y Recreación de Mejillones": "CM132",
 "Corporación Municipal de Deportes y Recreación de Molina": "CM202",
 "Corporación Municipal de Deportes y Recreación de Panguipulli": "CM233",
 "Corporación Municipal de Deportes y Recreación de Talcahuano": "CM204",
 "Corporación Municipal de Deportes y Recreación de Tocopilla": "CM259",
 "Corporación Municipal de Deportes y Recreación Tomé": "CM205",
 "Corporación Municipal de desarrollo Comunal y Productivo de Licantén": "CM156",
 "Corporación Municipal de Desarrollo Económico Cultura y Deporte de Renca": "CM061",
 "Corporación Municipal de Desarrollo Económico de Peñalolén (YUNUS)": "CM234",
 "Corporación Municipal de Desarrollo Productivo y Turismo de Molina": "CM211",
 "Corporación Municipal de Desarrollo Social de Antofagasta (CMDS)": "CM002",
 "Corporación Municipal de Desarrollo Social de Calama (COMDES)": "CM018",
 "Corporación Municipal de Desarrollo Social de Los Muermos": "CM214",
 "Corporación Municipal de Desarrollo Social de San Joaquin": "CM030",
 "Corporación Municipal de Desarrollo Social de Tiltil": "CM016",
 "Corporación Municipal de Desarrollo Social de Ñuñoa": "CM001",
 "Corporación Municipal de Educación y Salud de San Bernardo": "CM033",
 "Corporación Municipal de Educación y Servicios Ramón Freire Dalcahue": "CM012",
 "Corporación Municipal de Fomento Al Desarrollo Comunal y Productivo de La Florida (Cofodep)": "CM217",
 "Corporación Municipal de Fomento al Desarrollo Comunal y Productivo de Parral": "CM220",
 "Corporación Municipal de Fomento Al Desarrollo Económico y Productivo de Estación Central": "CM219",
 "Corporación Municipal de Fomento Productivo de Curicó": "CM138",
 "Corporación Municipal de Fomento y Desarrollo Comunal de Sierra Gorda": "CM054",
 "Corporación Municipal de innovación y desarrollo económico y social de SAN JOAQUÍN": "CM210",
 "Corporación Municipal de La Cultura y Las Artes de San Antonio": "CM224",
 "Corporación Municipal de La Reina": "CM017",
 "Corporación Municipal de las Artes y la Cultura de Río Claro": "CM290",
 "Corporación Municipal de Lo Prado": "CM040",
 "Corporación Municipal de Macul": "CM041",
 "Corporación Municipal de Maria Pinto": "CM028",
 "Corporación Municipal de Melipilla": "CM042",
 "Corporación Municipal de Peñalolén (CORMUP)": "CM005",
 "Corporación Municipal de Pirque": "CM014",
 "Corporación Municipal de Pozo Almonte": "CM034",
 "Corporación Municipal de Providencia": "CM031",
 "Corporación Municipal de Pudahuel": "CM032",
 "Corporación Municipal de Puente Alto": "CM044",
 "Corporación Municipal de Punta Arenas para la Educación Salud y Atención al Menor (CORMUPA)": "CM046",
 "Corporación Municipal de Puqueldón": "CM006",
 "Corporación Municipal de Queilen": "CM004",
 "Corporación Municipal de Quellón": "CM013",
 "Corporación Municipal de Quilpué": "CM019",
 "Corporación Municipal de Quinchao": "CM047",
 "Corporación Municipal de Quinta Normal": "CM029",
 "Corporación Municipal de Rancagua (CORMUN)": "CM008",
 "Corporación Municipal de Renca": "CM048",
 "Corporación Municipal de Salud de Panguipulli": "CM043",
 "Corporación Municipal de San Fernando (CORMUSAF)": "CM010",
 "Corporación Municipal de San Vicente": "CM051",
 "Corporación Municipal de Servicios y Desarrollo de Maipú (CODEDUC)": "CM007",
 "Corporación Municipal de Talagante": "CM052",
 "Corporación Municipal de Turismo Coquimbo": "CM260",
 "Corporación Municipal de Turismo de Paihuano": "CM143",
 "Corporación Municipal de Turismo de Vicuña": "CM261",
 "Corporación Municipal de Valparaíso": "CM015",
 "Corporación Municipal del Arte y la Cultura de Talagante": "CM089",
 "Corporación Municipal del Deporte de Vitacura": "CM175",
 "Corporación Municipal Deportiva Cultural y de Fomento Productivo Alto Hospicio": "CM179",
 "Corporación Municipal Isla de Maipo": "CM003",
 "Corporación Municipal Para El Desarrollo Cultural de Temuco": "CM268",
 "Corporación Municipal para el Desarrollo Social de Villa Alemana": "CM009",
 "Corporación Municipal Pueblito de Las Vizcachas": "CM269",
 "Corporación Municipal Viña del Mar para el Desarrollo Social": "CM053",
 "Corporación Nacional de Desarrollo Indígena (CONADI)": "AI002",
 "Corporación Nacional Forestal (CONAF)": "AR003",
 "Corporación Para El Desarrollo de La Provincia de Osorno (Corposorno)": "CM270",
 "Corporación Para El Desarrollo Productivo del Turismo de Alto del Carmen": "CM271",
 "Corporación Regional de Desarrollo de la Región del Biobío (Desarrolla Biobío)": "FU011",
 "Corporación Regional de Desarrollo Productivo de la Región de Tarapacá": "FU009",
 "Corporación Regional de Investigación y Desarrollo Centro de Investigación en Ecosistemas de la Patagonia": "FU021",
 "Corporación Regional de Turismo de la Región de Valparaíso": "FU031",
 "Corporación Regional de Turismo de la Región Metropolitana": "FU013",
 "Corporación Regional del Desarrollo Productivo del Maule": "FU032",
 "Corporación Santiago Innova": "CM276",
 "Corporación Social y Cultural de Concepción (SEMCO)": "CM278",
 "Corporación Teatro Regional Del Biobío": "FU027",
 "Corporación XIX Juegos Panamericanos Santiago 2023": "CM251",
 "Defensa Civil de Chile": "AD012",
 "Defensoría de los Derechos de la Niñez": "CO005",
 "Defensoría del Contribuyente": "AE033",
 "Defensoría Penal Pública (DPP)": "AK005",
 "Delegación Presidencial Provincial de Arauco": "AB052",
 "Delegación Presidencial Provincial de Aysén": "AB062",
 "Delegación Presidencial Provincial de Capitán Prat": "AB064",
 "Delegación Presidencial Provincial de Cardenal Caro": "AB044",
 "Delegación Presidencial Provincial de Cauquenes": "AB048",
 "Delegación Presidencial Provincial de Chacabuco": "AB069",
 "Delegación Presidencial Provincial de Chañaral": "AB029",
 "Delegación Presidencial Provincial de Chiloé": "AB059",
 "Delegación Presidencial Provincial de Choapa": "AB034",
 "Delegación Presidencial Provincial de Colchagua": "AB043",
 "Delegación Presidencial Provincial de Cordillera": "AB070",
 "Delegación Presidencial Provincial de Curicó": "AB045",
 "Delegación Presidencial Provincial de El Loa": "AB027",
 "Delegación Presidencial Provincial de General Carrera": "AB063",
 "Delegación Presidencial Provincial de Huasco": "AB031",
 "Delegación Presidencial Provincial de Isla de Pascua": "AB041",
 "Delegación Presidencial Provincial de Itata": "AB097",
 "Delegación Presidencial Provincial de La Antártica Chilena": "AB068",
 "Delegación Presidencial Provincial de Limarí": "AB033",
 "Delegación Presidencial Provincial de Linares": "AB047",
 "Delegación Presidencial Provincial de Los Andes": "AB038",
 "Delegación Presidencial Provincial de Maipo": "AB071",
 "Delegación Presidencial Provincial de Malleco": "AB053",
 "Delegación Presidencial Provincial de Marga Marga": "AB090",
 "Delegación Presidencial Provincial de Melipilla": "AB073",
 "Delegación Presidencial Provincial de Osorno": "AB057",
 "Delegación Presidencial Provincial de Palena": "AB060",
 "Delegación Presidencial Provincial de Parinacota": "AB023",
 "Delegación Presidencial Provincial de Petorca": "AB035",
 "Delegación Presidencial Provincial de Punilla": "AB096",
 "Delegación Presidencial Provincial de Quillota": "AB039",
 "Delegación Presidencial Provincial de San Antonio": "AB040",
 "Delegación Presidencial Provincial de San Felipe": "AB037",
 "Delegación Presidencial Provincial de Talagante": "AB072",
 "Delegación Presidencial Provincial de Tamarugal": "AB025",
 "Delegación Presidencial Provincial de Tierra del Fuego": "AB067",
 "Delegación Presidencial Provincial de Tocopilla": "AB028",
 "Delegación Presidencial Provincial de última Esperanza": "AB065",
 "Delegación Presidencial Provincial del Bíobío": "AB050",
 "Delegación Presidencial Provincial del Ranco": "AB056",
 "Delegación Presidencial Regional de Antofagasta": "AB008",
 "Delegación Presidencial Regional de Arica y Parinacota": "AB007",
 "Delegación Presidencial Regional de Atacama": "AB009",
 "Delegación Presidencial Regional de Aysén del General Carlos Ibáñez del Campo": "AB010",
 "Delegación Presidencial Regional de Coquimbo": "AB011",
 "Delegación Presidencial Regional de La Araucanía": "AB012",
 "Delegación Presidencial Regional de Los Lagos": "AB013",
 "Delegación Presidencial Regional de Los Ríos": "AB014",
 "Delegación Presidencial Regional de Magallanes y la Antártica Chilena": "AB015",
 "Delegación Presidencial Regional de Tarapacá": "AB017",
 "Delegación Presidencial Regional de Valparaíso": "AB018",
 "Delegación Presidencial Regional de Ñuble": "AB094",
 "Delegación Presidencial Regional del Biobío": "AB019",
 "Delegación Presidencial Regional del Libertador General Bernardo OHiggins": "AB016",
 "Delegación Presidencial Regional del Maule": "AB020",
 "Delegación Presidencial Regional Metropolitana": "AB021",
 "Dirección de Aeropuertos (DAP)": "AM004",
 "Dirección de Arquitectura (DARQ)": "AM005",
 "Dirección de Compras y Contratación Pública (CHILECOMPRA)": "AE011",
 "Dirección de Contabilidad y Finanzas (DCYF)": "AM003",
 "Dirección de Educación Pública": "AJ018",
 "Dirección de Obras Hidráulicas (DOH)": "AM007",
 "Dirección de Obras Portuarias (DOP)": "AM008",
 "Dirección de Planeamiento (DIRPLAN)": "AM009",
 "Dirección de Presupuestos (DIPRES)": "AE002",
 "Dirección de Previsión de Carabineros de Chile (DIPRECA)": "AD016",
 "Dirección de Vialidad (VIALIDAD)": "AM010",
 "Dirección del Trabajo (DT)": "AL003",
 "Dirección General de Aeronáutica Civil (DGAC)": "AD020",
 "Dirección General de Aguas (DGA)": "AM006",
 "Dirección General de Concesiones (DGC)": "AM014",
 "Dirección General de Crédito Prendario (DICREP)": "AL004",
 "Dirección General de Movilización Nacional (DGMN)": "AD013",
 "Dirección General de Obras Públicas (DGOP)": "AM002",
 "Dirección General de Relaciones Económicas Internacionales (DIRECON)": "AC002",
 "Dirección Nacional de Fronteras y Límites del Estado (DIFROL)": "AC003",
 "Dirección Nacional del Servicio Civil": "AE004",
 "Ejército de Chile": "AD006",
 "Estado Mayor Conjunto (EMCO)": "AD023",
 "Ex Consejo Nacional de la Cultura y las Artes (CNCA)": "AV001",
 "Fiscalía de Obras Públicas": "AM013",
 "Fiscalía Nacional Económica (FNE)": "AH005",
 "Fondo de Solidaridad e Inversión Social (FOSIS)": "AI004",
 "Fondo Nacional de Salud (FONASA)": "AO004",
 "Fuerza Aérea de Chile (Incluye al Servicio Aerofotogramétrico)": "AD008",
 "Fundación Artesanías de Chile": "FU005",
 "Fundación Centro Cultural de Lo Prado": "FU010",
 "Fundación Centro Cultural Palacio de La Moneda": "FU018",
 "Fundación Cultural de la municipalidad de Tocopilla": "FM004",
 "Fundación Cultural de Sierra Gorda": "FU012",
 "Fundación Cultural Providencia": "FU008",
 "Fundación de Comunicación Capacitación y Cultura del Agro (FUCOA)": "AR009",
 "Fundación de Cultura y Turismo de la Municipalidad de Mejillones": "FM002",
 "Fundación de desarrollo social de Quillota (BANAMOR)": "FU024",
 "Fundación de Orquestas Juveniles e Infantiles de Chile (FOJI)": "FU004",
 "Fundación del deporte de Punta Arenas": "FU016",
 "Fundación Integra": "FU001",
 "Fundación para el Desarrollo de la Cultura y las Artes de la comuna de Punta Arenas": "FU022",
 "Fundación para la Promoción y Desarrollo de la Mujer  (PRODEMU)": "FU003",
 "Fundación Teatro Municipal de Las Condes": "FU015",
 "Fundación Tiempos Nuevos (MIM)": "FU002",
 "Gendarmería de Chile": "AK006",
 "Gobierno Regional de Antofagasta (GORE)": "AB077",
 "Gobierno Regional de Arica y Parinacota (GORE)": "AB075",
 "Gobierno Regional de Atacama (GORE)": "AB078",
 "Gobierno Regional de Aysén (GORE Aysén)": "AB088",
 "Gobierno Regional de Coquimbo  GORECOQUIMBO": "AB079",
 "Gobierno Regional de La Araucanía (Gore Araucanía)": "AB085",
 "Gobierno Regional de Los Lagos (Gore Los Lagos)": "AB087",
 "Gobierno Regional de Los Ríos (GORE de Los Ríos)": "AB086",
 "Gobierno Regional de Magallanes y de la Antártica Chilena (GORE Magallanes)": "AB089",
 "Gobierno Regional de OHiggins (Gore OHiggins)": "AB082",
 "Gobierno Regional de Tarapacá (GORE)": "AB076",
 "Gobierno Regional de Valparaíso  (GORE)": "AB080",
 "Gobierno Regional de Ñuble (GORE)": "AB098",
 "Gobierno Regional del Bío Bío (Gore Bío Bío)": "AB084",
 "Gobierno Regional del Maule (Gore Maule)": "AB083",
 "Gobierno Regional Metropolitano de Santiago  (GORE Metropolitano)": "AB081",
 "Hospital Barros Luco": "AO080",
 "Hospital Base de Valdivia": "AO093",
 "Hospital Carlos Van Buren": "AO095",
 "Hospital Claudio Vicuña de San Antonio": "AO094",
 "Hospital Clínico Dra. Eloísa Díaz I. La Florida": "AO112",
 "Hospital Clínico Magallanes Dr Lautaro Navarro Aravia": "AO082",
 "Hospital Clínico Metropolitano La Florida Dra. Eloísa Díaz Insunza": "AO112",
 "Hospital de Curicó": "AO083",
 "Hospital de las Higueras": "AO092",
 "Hospital de Linares": "AO084",
 "Hospital de Lota": "AO063",
 "Hospital de Melipilla": "AO074",
 "Hospital de Osorno": "AO089",
 "Hospital de Ovalle": "AO065",
 "Hospital de Puerto Montt": "AO090",
 "Hospital de Quilpué": "AO097",
 "Hospital de San Camilo": "AO054",
 "Hospital de San Carlos": "AO086",
 "Hospital de Tomé": "AO091",
 "Hospital de Urgencia Asistencia Pública (HUAP)": "AO069",
 "Hospital de Victoria": "AO056",
 "Hospital del Salvador": "AO079",
 "Hospital Dr. Augusto Riffart de Castro": "AO061",
 "Hospital Dr. Carlos Cisternas De Calama": "AO114",
 "Hospital Dr. Exequiel González Cortes": "AO102",
 "Hospital Dr. Hernán Henríquez Aravena de Temuco": "AO110",
 "Hospital Dr. Mauricio Heyermann Torres de Angol": "AO057",
 "Hospital Eduardo Pereira de Valparaíso": "AO096",
 "Hospital El Carmen Dr. Luis Valentín Ferrada": "AO111",
 "Hospital El Pino": "AO103",
 "Hospital Ernesto Torres de Iquique": "AO068",
 "Hospital Franco Ravera Zunino": "AO088",
 "Hospital Félix Bulnes": "AO073",
 "Hospital Guillermo Grant Benavente de Concepción": "AO064",
 "Hospital Gustavo Fricke": "AO098",
 "Hospital Herminda Martin": "AO104",
 "Hospital Juan Noé de Arica": "AO058",
 "Hospital La Serena": "AO066",
 "Hospital Leonardo Guzmán de Antofagasta": "AO055",
 "Hospital Luis Calvo Mackenna": "AO109",
 "Hospital Luis Tisné": "AO106",
 "Hospital Padre Hurtado": "AO013",
 "Hospital Regional Copiapó San José del Carmen": "AO113",
 "Hospital Regional Coyhaique": "AO059",
 "Hospital Regional de Rancagua": "AO088",
 "Hospital Regional de Talca": "AO085",
 "Hospital Roberto del Río": "AO072",
 "Hospital San Borja Arriarán": "AO070",
 "Hospital San José de Coronel": "AO062",
 "Hospital San José": "AO071",
 "Hospital San Juan de Dios de Los Andes": "AO101",
 "Hospital San Juan de Dios de San Fernando": "AO087",
 "Hospital San Juan de Dios": "AO075",
 "Hospital San Martín de Quillota": "AO099",
 "Hospital San Pablo de Coquimbo": "AO067",
 "Hospital Sótero del Río": "AO081",
 "Hospital Víctor Ríos Ruiz de Los Angeles": "AO060",
 "I. Municipalidad de Macul": "MU161",
 "I. Municipalidad de Negrete": "MU181",
 "I. Municipalidad de Penco": "MU210",
 "Ilustre Municipalidad de Constitución": "MU064",
 "Ilustre Municipalidad de Olivar": "MU188",
 "Instituto Antártico Chileno (INACH)": "AC005",
 "Instituto de Desarrollo Agropecuario (INDAP)": "AR004",
 "Instituto de Neurocirugía": "AO077",
 "Instituto de Previsión Social (IPS)": "AL005",
 "Instituto de Salud Pública (ISP)": "AO005",
 "Instituto de Seguridad Laboral (ISL)": "AL006",
 "Instituto Forestal (INFOR)": "AR011",
 "Instituto Nacional de Derechos Humanos (INDH)": "CO001",
 "Instituto Nacional de Desarrollo Sustentable de la Pesca Artesanal y de la Acuicultura de Pequeña Escala (INDESPA)": "AH015",
 "Instituto Nacional de Estadisticas (INE)": "AH007",
 "Instituto Nacional de Geriatría (INGER)": "AO078",
 "Instituto Nacional de Hidráulica (INH)": "AM012",
 "Instituto Nacional de la Juventud (INJUV)": "AI005",
 "Instituto Nacional de Propiedad Industrial (INAPI)": "AY001",
 "Instituto Nacional de Rehabilitación Pedro Aguirre Cerda": "AO076",
 "Instituto Nacional del Cáncer": "AO108",
 "Instituto Nacional del Deporte (IND)": "BA002",
 "Instituto Nacional del Tórax": "AO105",
 "Instituto Psiquiátrico": "AO100",
 "Instituto Traumatológico": "AO107",
 "Junta de Aeronáutica Civil (JAC)": "AN003",
 "Junta Nacional de Auxilio Escolar y Becas (JUNAEB)": "AJ009",
 "Junta Nacional de Jardines Infantiles (JUNJI)": "AJ010",
 "Municipalidad de Algarrobo": "MU001",
 "Municipalidad de Alhué": "MU002",
 "Municipalidad de Alto Biobío": "MU003",
 "Municipalidad de Alto del Carmen": "MU004",
 "Municipalidad de Andacollo": "MU007",
 "Municipalidad de Angol": "MU008",
 "Municipalidad de Antofagasta": "MU009",
 "Municipalidad de Antuco": "MU010",
 "Municipalidad de Arauco": "MU011",
 "Municipalidad de Arica": "MU012",
 "Municipalidad de Aysén": "MU013",
 "Municipalidad de Buin": "MU014",
 "Municipalidad de Bulnes": "MU015",
 "Municipalidad de Cabildo": "MU016",
 "Municipalidad de Cabo de Hornos y Antártica": "MU017",
 "Municipalidad de Calama": NaN,
 "Municipalidad de Calbuco": "MU020",
 "Municipalidad de Caldera": "MU021",
 "Municipalidad de Calera de Tango": "MU022",
 "Municipalidad de Calle Larga": "MU023",
 "Municipalidad de Camarones": "MU024",
 "Municipalidad de Camiña": "MU025",
 "Municipalidad de Canela": "MU026",
 "Municipalidad de Carahue": "MU028",
 "Municipalidad de Cartagena": "MU029",
 "Municipalidad de Casablanca": "MU030",
 "Municipalidad de Catemu": "MU032",
 "Municipalidad de Cauquenes": "MU033",
 "Municipalidad de Cañete": "MU027",
 "Municipalidad de Cerrillos": "MU034",
 "Municipalidad de Cerro Navia": "MU035",
 "Municipalidad de Chaitén": "MU036",
 "Municipalidad de Chanco": "MU037",
 "Municipalidad de Chañaral": "MU038",
 "Municipalidad de Chiguayante": "MU040",
 "Municipalidad de Chile Chico": "MU041",
 "Municipalidad de Chillán Viejo": "MU043",
 "Municipalidad de Chillán": "MU042",
 "Municipalidad de Chimbarongo": "MU044",
 "Municipalidad de Cholchol": "MU045",
 "Municipalidad de Chonchi": "MU046",
 "Municipalidad de Chépica": "MU039",
 "Municipalidad de Cisnes": "MU047",
 "Municipalidad de Cobquecura": "MU048",
 "Municipalidad de Cochamó": "MU049",
 "Municipalidad de Cochrane": "MU050",
 "Municipalidad de Codegua": "MU051",
 "Municipalidad de Coelemu": "MU052",
 "Municipalidad de Coihueco": "MU053",
 "Municipalidad de Coinco": "MU054",
 "Municipalidad de Colbún": "MU055",
 "Municipalidad de Colchane": "MU056",
 "Municipalidad de Colina": "MU057",
 "Municipalidad de Collipulli": "MU058",
 "Municipalidad de Coltauco": "MU059",
 "Municipalidad de Combarbalá": "MU060",
 "Municipalidad de Concepción": "MU061",
 "Municipalidad de Conchalí": "MU062",
 "Municipalidad de Coquimbo": "MU067",
 "Municipalidad de Coronel": "MU068",
 "Municipalidad de Corral": "MU069",
 "Municipalidad de Coyhaique": "MU070",
 "Municipalidad de Cunco": "MU071",
 "Municipalidad de Curacautín": "MU072",
 "Municipalidad de Curaco de Vélez": "MU074",
 "Municipalidad de Curanilahue": "MU075",
 "Municipalidad de Curarrehue": "MU076",
 "Municipalidad de Curicó": "MU078",
 "Municipalidad de Dalcahue": "MU079",
 "Municipalidad de Diego de Almagro": "MU080",
 "Municipalidad de Doñihue": "MU081",
 "Municipalidad de El Bosque": "MU082",
 "Municipalidad de El Carmen": "MU083",
 "Municipalidad de El Monte": "MU084",
 "Municipalidad de El Quisco": "MU085",
 "Municipalidad de El Tabo": "MU086",
 "Municipalidad de Empedrado": "MU087",
 "Municipalidad de Ercilla": "MU088",
 "Municipalidad de Estación Central": "MU089",
 "Municipalidad de Florida": "MU090",
 "Municipalidad de Freire": "MU091",
 "Municipalidad de Freirina": "MU092",
 "Municipalidad de Fresia": "MU093",
 "Municipalidad de Frutillar": "MU094",
 "Municipalidad de Futaleufú": "MU095",
 "Municipalidad de Futrono": "MU096",
 "Municipalidad de Galvarino": "MU097",
 "Municipalidad de General Lagos": "MU098",
 "Municipalidad de Gorbea": "MU099",
 "Municipalidad de Graneros": "MU100",
 "Municipalidad de Guaitecas": "MU101",
 "Municipalidad de Hijuelas": "MU102",
 "Municipalidad de Hualaihué": "MU103",
 "Municipalidad de Hualpén": "MU105",
 "Municipalidad de Hualqui": "MU106",
 "Municipalidad de Huara": "MU107",
 "Municipalidad de Huasco": "MU108",
 "Municipalidad de Huechuraba": "MU109",
 "Municipalidad de Illapel": "MU110",
 "Municipalidad de Independencia": "MU111",
 "Municipalidad de Iquique": "MU112",
 "Municipalidad de Isla de Maipo": "MU113",
 "Municipalidad de Isla de Pascua (Rapa Nui)": "MU114",
 "Municipalidad de Juan Fernández": "MU115",
 "Municipalidad de La Calera": "MU116",
 "Municipalidad de La Cisterna": "MU117",
 "Municipalidad de La Cruz": "MU118",
 "Municipalidad de La Estrella": "MU119",
 "Municipalidad de La Florida": "MU120",
 "Municipalidad de La Granja": "MU121",
 "Municipalidad de La Higuera": "MU122",
 "Municipalidad de La Ligua": "MU123",
 "Municipalidad de La Pintana": "MU124",
 "Municipalidad de La Reina": "MU125",
 "Municipalidad de La Serena": "MU126",
 "Municipalidad de La Unión": "MU127",
 "Municipalidad de Lago Ranco": "MU128",
 "Municipalidad de Lago Verde": "MU129",
 "Municipalidad de Laguna Blanca": "MU130",
 "Municipalidad de Laja": "MU131",
 "Municipalidad de Lampa": "MU132",
 "Municipalidad de Lanco": "MU133",
 "Municipalidad de Las Cabras": "MU134",
 "Municipalidad de Lautaro": "MU136",
 "Municipalidad de Lebu": "MU137",
 "Municipalidad de Licantén": "MU138",
 "Municipalidad de Limache": "MU139",
 "Municipalidad de Linares": "MU140",
 "Municipalidad de Litueche": "MU141",
 "Municipalidad de Llanquihue": "MU142",
 "Municipalidad de Llay Llay": "MU143",
 "Municipalidad de Lo Barnechea": "MU144",
 "Municipalidad de Lo Espejo": "MU145",
 "Municipalidad de Lo Prado": "MU146",
 "Municipalidad de Lolol": "MU147",
 "Municipalidad de Loncoche": "MU148",
 "Municipalidad de Lonquimay": "MU150",
 "Municipalidad de Los Alamos": "MU151",
 "Municipalidad de Los Andes": "MU152",
 "Municipalidad de Los Lagos": "MU154",
 "Municipalidad de Los Muermos": "MU155",
 "Municipalidad de Los Sauces": "MU156",
 "Municipalidad de Los Vilos": "MU157",
 "Municipalidad de Los Ángeles": "MU153",
 "Municipalidad de Lumaco": "MU159",
 "Municipalidad de Machalí": "MU160",
 "Municipalidad de Maipú": "MU163",
 "Municipalidad de Malloa": "MU164",
 "Municipalidad de Marchige": "MU165",
 "Municipalidad de Mariquina": "MU168",
 "Municipalidad de María Elena": "MU166",
 "Municipalidad de María Pinto": "MU167",
 "Municipalidad de Maule": "MU169",
 "Municipalidad de Maullín": "MU170",
 "Municipalidad de Mejillones": "MU171",
 "Municipalidad de Melipeuco": "MU172",
 "Municipalidad de Melipilla": "MU173",
 "Municipalidad de Molina": "MU174",
 "Municipalidad de Monte Patria": "MU175",
 "Municipalidad de Mostazal": "MU176",
 "Municipalidad de Mulchén": "MU177",
 "Municipalidad de Máfil": "MU162",
 "Municipalidad de Nacimiento": "MU178",
 "Municipalidad de Nancagua": "MU179",
 "Municipalidad de Navidad": "MU180",
 "Municipalidad de Ninhue": "MU182",
 "Municipalidad de Nogales": "MU183",
 "Municipalidad de OHiggins": "MU187",
 "Municipalidad de Ollague": "MU189",
 "Municipalidad de Olmué": "MU190",
 "Municipalidad de Osorno": "MU191",
 "Municipalidad de Ovalle": "MU192",
 "Municipalidad de Padre Hurtado": "MU193",
 "Municipalidad de Padre Las Casas": "MU194",
 "Municipalidad de Paihuano": "MU195",
 "Municipalidad de Paillaco": "MU196",
 "Municipalidad de Paine": "MU197",
 "Municipalidad de Palena": "MU198",
 "Municipalidad de Palmilla": "MU199",
 "Municipalidad de Panguipulli": "MU200",
 "Municipalidad de Panquehue": "MU201",
 "Municipalidad de Papudo": "MU202",
 "Municipalidad de Paredones": "MU203",
 "Municipalidad de Parral": "MU204",
 "Municipalidad de Pedro Aguirre Cerda": "MU205",
 "Municipalidad de Pelarco": "MU206",
 "Municipalidad de Pelluhue": "MU207",
 "Municipalidad de Pemuco": "MU208",
 "Municipalidad de Pencahue": "MU209",
 "Municipalidad de Peralillo": "MU213",
 "Municipalidad de Perquenco": "MU214",
 "Municipalidad de Petorca": "MU215",
 "Municipalidad de Peumo": "MU216",
 "Municipalidad de Peñaflor": "MU211",
 "Municipalidad de Peñalolén": "MU212",
 "Municipalidad de Pica": "MU217",
 "Municipalidad de Pichidegua": "MU218",
 "Municipalidad de Pichilemu": "MU219",
 "Municipalidad de Pinto": "MU220",
 "Municipalidad de Pirque": "MU221",
 "Municipalidad de Pitrufquén": "MU222",
 "Municipalidad de Placilla": "MU223",
 "Municipalidad de Portezuelo": "MU224",
 "Municipalidad de Porvenir": "MU225",
 "Municipalidad de Pozo Almonte": "MU226",
 "Municipalidad de Primavera": "MU227",
 "Municipalidad de Providencia": NaN,
 "Municipalidad de Puchuncaví": "MU229",
 "Municipalidad de Pucón": "MU230",
 "Municipalidad de Pudahuel": "MU231",
 "Municipalidad de Puente Alto": "MU232",
 "Municipalidad de Puerto Montt": "MU233",
 "Municipalidad de Puerto Natales": "MU234",
 "Municipalidad de Puerto Octay": "MU235",
 "Municipalidad de Puerto Varas": "MU236",
 "Municipalidad de Pumanque": "MU237",
 "Municipalidad de Punitaqui": "MU238",
 "Municipalidad de Punta Arenas": "MU239",
 "Municipalidad de Puqueldón": "MU240",
 "Municipalidad de Purranque": "MU242",
 "Municipalidad de Putaendo": "MU243",
 "Municipalidad de Putre": "MU244",
 "Municipalidad de Puyehue": "MU245",
 "Municipalidad de Queilén": "MU246",
 "Municipalidad de Quellón": "MU247",
 "Municipalidad de Quemchi": "MU248",
 "Municipalidad de Quilaco": "MU249",
 "Municipalidad de Quilicura": "MU250",
 "Municipalidad de Quilleco": "MU251",
 "Municipalidad de Quillota": "MU253",
 "Municipalidad de Quillón": "MU252",
 "Municipalidad de Quilpué": "MU254",
 "Municipalidad de Quinchao": "MU255",
 "Municipalidad de Quinta Normal": "MU257",
 "Municipalidad de Quintero": "MU258",
 "Municipalidad de Quirihue": "MU259",
 "Municipalidad de Rancagua": "MU260",
 "Municipalidad de Rauco": "MU262",
 "Municipalidad de Renaico": "MU264",
 "Municipalidad de Renca": "MU265",
 "Municipalidad de Rengo": "MU266",
 "Municipalidad de Requínoa": "MU267",
 "Municipalidad de Retiro": "MU268",
 "Municipalidad de Rinconada": "MU269",
 "Municipalidad de Rio Bueno": "MU270",
 "Municipalidad de Romeral": "MU276",
 "Municipalidad de Ránquil": "MU261",
 "Municipalidad de Río Claro": "MU271",
 "Municipalidad de Río Hurtado": "MU272",
 "Municipalidad de Río Ibáñez": "MU273",
 "Municipalidad de Río Negro": "MU274",
 "Municipalidad de Río Verde": "MU275",
 "Municipalidad de Saavedra": "MU277",
 "Municipalidad de Sagrada Familia": "MU278",
 "Municipalidad de Salamanca": "MU279",
 "Municipalidad de San Antonio": "MU280",
 "Municipalidad de San Bernardo": "MU281",
 "Municipalidad de San Carlos": "MU282",
 "Municipalidad de San Clemente": "MU283",
 "Municipalidad de San Esteban": "MU284",
 "Municipalidad de San Fabián": "MU285",
 "Municipalidad de San Felipe": "MU286",
 "Municipalidad de San Fernando": "MU287",
 "Municipalidad de San Gregorio": "MU288",
 "Municipalidad de San Ignacio": "MU289",
 "Municipalidad de San Javier": "MU290",
 "Municipalidad de San Joaquín": "MU291",
 "Municipalidad de San José de Maipo": "MU292",
 "Municipalidad de San Juan de la Costa": "MU293",
 "Municipalidad de San Miguel": "MU294",
 "Municipalidad de San Nicolás": "MU295",
 "Municipalidad de San Pablo": "MU296",
 "Municipalidad de San Pedro De La Paz": "MU299",
 "Municipalidad de San Pedro": "MU297",
 "Municipalidad de San Rafael": "MU300",
 "Municipalidad de San Ramón": "MU301",
 "Municipalidad de San Rosendo": "MU302",
 "Municipalidad de San Vicente de Tagua Tagua": "MU303",
 "Municipalidad de Santa Bárbara": "MU304",
 "Municipalidad de Santa Cruz": "MU305",
 "Municipalidad de Santa Juana": "MU306",
 "Municipalidad de Santa María": "MU307",
 "Municipalidad de Santiago": "MU308",
 "Municipalidad de Santo Domingo": "MU309",
 "Municipalidad de Sierra Gorda": "MU310",
 "Municipalidad de Talagante": "MU311",
 "Municipalidad de Talca": "MU312",
 "Municipalidad de Talcahuano": "MU313",
 "Municipalidad de Taltal": "MU314",
 "Municipalidad de Teno": "MU316",
 "Municipalidad de Teodoro Schmidt": "MU317",
 "Municipalidad de Tierra Amarilla": "MU318",
 "Municipalidad de Tiltil": "MU319",
 "Municipalidad de Timaukel": "MU320",
 "Municipalidad de Tirúa": "MU321",
 "Municipalidad de Tocopilla": "MU322",
 "Municipalidad de Toltén": "MU323",
 "Municipalidad de Tome": "MU324",
 "Municipalidad de Torres del Paine": "MU325",
 "Municipalidad de Tortel": "MU326",
 "Municipalidad de Traiguén": "MU327",
 "Municipalidad de Trehuaco": "MU328",
 "Municipalidad de Tucapel": "MU329",
 "Municipalidad de Valdivia": "MU330",
 "Municipalidad de Vallenar": "MU331",
 "Municipalidad de Valparaíso": "MU332",
 "Municipalidad de Vichuquén": "MU333",
 "Municipalidad de Victoria": "MU334",
 "Municipalidad de Vicuña": "MU335",
 "Municipalidad de Vilcún": "MU336",
 "Municipalidad de Villa Alegre": "MU337",
 "Municipalidad de Villa Alemana": "MU338",
 "Municipalidad de Villarrica": "MU339",
 "Municipalidad de Vitacura": "MU341",
 "Municipalidad de Viña del Mar": "MU340",
 "Municipalidad de Yerbas Buenas": "MU342",
 "Municipalidad de Yumbel": "MU343",
 "Municipalidad de Yungay": "MU344",
 "Municipalidad de Zapallar": "MU345",
 "Municipalidad de Ñiquén": "MU185",
 "Municipalidad de Ñuñoa": "MU186",
 "Oficinas de Estudios y Políticas Agrarias (ODEPA)": "AR005",
 "Organismo de Capacitación (CPLT)": "EP029",
 "Organismo de Capacitación (Prueba)": "EP029",
 "Parque Metropolitano de Santiago": "AP017",
 "Partido Ciudadanos": "PP030",
 "Policía de Investigaciones (PDI)": "AD010",
 "Presidencia de la República": "AA001",
 "SEREMI de Salud  de Antofagasta": "AO041",
 "SEREMI de Salud  de Arica y Parinacota": "AO039",
 "SEREMI de Salud  de Atacama": "AO042",
 "SEREMI de Salud  de Coquimbo": "AO043",
 "SEREMI de Salud  de Tarapacá": "AO040",
 "SEREMI de Salud  de Valparaíso": "AO044",
 "SEREMI de Salud  Metropolitano de Santiago": "AO045",
 "SEREMI de Salud de Aysén": "AO052",
 "SEREMI de Salud de La Araucanía": "AO049",
 "SEREMI de Salud de Los Ríos": "AO050",
 "SEREMI de Salud de Magallanes y Antártica Chilena": "AO053",
 "SEREMI de Salud de OHiggins": "AO046",
 "SEREMI de Salud del Bío Bío": "AO048",
 "SEREMI de Salud del Maule": "AO047",
 "SEREMI de Salud del Ñuble": "AO117",
 "SEREMI de Salud región de Los Lagos": "AO051",
 "SEREMI de Vivienda y Urbanismo Región de Antofagasta": "AP021",
 "SEREMI de Vivienda y Urbanismo Región de Arica y Parinacota": "AP019",
 "SEREMI de Vivienda y Urbanismo Región de Atacama": "AP022",
 "SEREMI de Vivienda y Urbanismo Región de Aysén": "AP033",
 "SEREMI de Vivienda y Urbanismo Región de Bíobio": "AP029",
 "SEREMI de Vivienda y Urbanismo Región de Coquimbo": "AP023",
 "SEREMI de Vivienda y Urbanismo Región de La Araucanía": "AP030",
 "SEREMI de Vivienda y Urbanismo Región de Los Lagos": "AP032",
 "SEREMI de Vivienda y Urbanismo Región de Los Ríos": "AP031",
 "SEREMI de Vivienda y Urbanismo Región de Magallanes y Antártica Chilena": "AP034",
 "SEREMI de Vivienda y Urbanismo Región de Maule": "AP027",
 "SEREMI de Vivienda y Urbanismo Región de Tarapacá": "AP020",
 "SEREMI de Vivienda y Urbanismo Región de Valparaíso": "AP024",
 "SEREMI de Vivienda y Urbanismo Región de Ñuble": "AP028",
 "SEREMI de Vivienda y Urbanismo Región del Libertador Bernardo OHiggins": "AP026",
 "SEREMI de Vivienda y Urbanismo Región Metropolitana": "AP025",
 "Servicio Agrícola y Ganadero (SAG)": "AR006",
 "Servicio de Biodiversidad y Áreas Protegidas": "AW005",
 "Servicio de Cooperación Técnica (SERCOTEC)": "AH012",
 "Servicio de Evaluación Ambiental (SEA)": "AW004",
 "Servicio de Gobierno Interior": "AB005",
 "Servicio de Registro Civil e Identificación": "AK002",
 "Servicio de Salud Aconcagua": "AO021",
 "Servicio de Salud Antofagasta": "AO018",
 "SERVICIO DE SALUD ARAUCANIA NORTE": "AO031",
 "Servicio de Salud Araucanía Sur": "AO032",
 "Servicio de Salud Arauco": "AO030",
 "Servicio de Salud Arica y Parinacota": "AO016",
 "Servicio de Salud Atacama": "AO019",
 "Servicio de Salud Aysén": "AO036",
 "Servicio de Salud Bíobío": "AO029",
 "Servicio de Salud Concepción": "AO027",
 "Servicio de Salud Coquimbo": "AO020",
 "Servicio de Salud de Chiloé": "AO035",
 "Servicio de Salud del Reloncaví": "AO037",
 "Servicio de Salud Magallanes": "AO038",
 "Servicio de Salud Maule": "AO025",
 "Servicio de Salud Metropolitano Central": "AO007",
 "Servicio de Salud Metropolitano Norte": "AO008",
 "Servicio de Salud Metropolitano Occidente": "AO009",
 "Servicio de Salud Metropolitano Oriente": "AO010",
 "Servicio de Salud Metropolitano Sur Oriente": "AO012",
 "Servicio de Salud Metropolitano Sur": "AO011",
 "Servicio de Salud OHiggins": "AO024",
 "Servicio de Salud Osorno": "AO034",
 "Servicio de Salud Talcahuano": "AO028",
 "Servicio de Salud Tarapacá": "AO017",
 "Servicio de Salud Valdivia": "AO033",
 "Servicio de Salud Valparaíso  San Antonio": "AO022",
 "Servicio de Salud Viña del Mar  Quillota": "AO023",
 "Servicio de Salud Ñuble": "AO026",
 "Servicio Electoral (SERVEL)": "AB006",
 "Servicio Local de Educación Pública  Maule Costa": "AJ034",
 "Servicio Local de Educación Pública Aconcagua (SLEP Aconcagua)": "AJ048",
 "Servicio Local de Educación Pública Andalién Sur (SLEP Andalién Sur)": "AJ024",
 "Servicio Local de Educación Pública Atacama (SLEP Atacama)": "AJ027",
 "Servicio Local de Educación Pública Chiloé (SLEP Chiloé)": "AJ049",
 "Servicio Local de Educación Pública Chinchorro (SLEP Chinchorro)": "AJ023",
 "Servicio Local de Educación Pública Colchagua (SLEP Colchagua)": "AJ026",
 "Servicio Local de Educación Pública Costa Araucanía (SLEP Costa Araucanía)": "AJ020",
 "Servicio Local de Educación Pública Costa Central (SLEP Costa Central)": "AJ039",
 "Servicio Local de Educación Pública de Andalién Costa (SLEP Andalién Costa)": "AJ038",
 "Servicio Local de Educación Pública de Antofagasta (SLEP Antofagasta)": "AJ047",
 "Servicio Local de Educación Pública de Aysén (SLEP Aysén)": "AJ031",
 "Servicio Local de Educación Pública de Barrancas (SLEP Barrancas)": "AJ016",
 "Servicio Local de Educación Pública de Iquique (SLEP Iquique)": "AJ032",
 "Servicio Local de Educación Pública de Los Parques": "AJ040",
 "Servicio Local de Educación Pública de Magallanes (SLEP Magallanes)": "AJ030",
 "Servicio Local de Educación Pública del Pino": "AJ041",
 "Servicio Local de Educación Pública del Tamarugal": "AJ045",
 "Servicio Local de Educación Pública Elqui (SLEP Elqui)": "AJ042",
 "Servicio Local de Educación Pública Gabriela Mistral (SLEP Gabriela Mistral)": "AJ022",
 "Servicio Local de Educación Pública Huasco (SLEP Huasco)": "AJ019",
 "Servicio Local de Educación Pública Licancabur": "AJ035",
 "Servicio Local de Educación Pública Llanquihue (SLEP Llanquihue)": "AJ028",
 "Servicio Local de Educación Pública Los Andes (SLEP Los Andes)": "AJ051",
 "Servicio Local de Educación Pública los Libertadores": "AJ043",
 "Servicio Local de Educación Pública Los Álamos (SLEP Los Álamos)": "AJ050",
 "Servicio Local de Educación Pública Marga Marga (SLEP Marga Marga)": "AJ044",
 "Servicio Local de Educación Pública Petorca (SLEP Petorca)": "AJ052",
 "Servicio Local de Educación Pública Puelche (SLEP Puelche)": "AJ053",
 "Servicio Local de Educación Pública Puerto Cordillera": "AJ017",
 "Servicio Local de educación Pública Punilla Cordillera": "AJ033",
 "Servicio Local de Educación Pública Santa Rosa": "AJ037",
 "Servicio Local de Educación Pública Santiago Centro (SLEP Santiago Centro)": "AJ054",
 "Servicio Local de Educación Pública Valdivia (SLEP Valdivia)": "AJ046",
 "Servicio Local de Educación Pública Valle Cachapoal": "AJ055",
 "Servicio Local de Educación Pública Valle Diguillín (SLEP Valle Diguillín)": "AJ056",
 "Servicio Local de Educación Pública Valparaíso (SLEP Valparaíso)": "AJ029",
 "Servicio Localde Educación Pública Santa Corina": "AJ036",
 "Servicio Médico Legal (SML)": "AK003",
 "Servicio Nacional de Aduanas": "AE007",
 "Servicio Nacional de Capacitación y Empleo (SENCE)": "AL007",
 "Servicio Nacional de Geología y Minería (SERNAGEOMIN)": "AS004",
 "Servicio Nacional de la Discapacidad (SENADIS)": "AI003",
 "Servicio Nacional de la Mujer y la Equidad de Género (SERNAMEG)": "AT001",
 "Servicio Nacional de Menores (SENAME)": "AK004",
 "Servicio Nacional de Migraciones": "AB099",
 "Servicio Nacional de Pesca y Acuicultura (SERNAPESCA)": "AH010",
 "Servicio Nacional de Prevención y Respuesta ante Desastres (SENAPRED) ex ONEMI": "AB004",
 "Servicio Nacional de Prevención y Respuesta ante Desastres (SENAPRED)": "AB004",
 "Servicio Nacional de Protección Especializada a la Niñez y Adolescencia": "AI010",
 "Servicio Nacional de Reinserción Social Juvenil": "CO007",
 "Servicio Nacional de Turismo (SERNATUR)": "AH008",
 "Servicio Nacional del Adulto Mayor (SENAMA)": "AI006",
 "Servicio Nacional del Consumidor (SERNAC)": "AH009",
 "Servicio Nacional del Patrimonio Cultural": "BC003",
 "Servicio Nacional para la Prevención y Rehabilitación del Consumo de Drogas y Alcohol (SENDA)": "AB092",
 "SERVIU Metropolitano": "AP007",
 "SERVIU Región de Antofagasta": "AP003",
 "SERVIU Región de Arica y Parinacota": "AP016",
 "SERVIU Región de Atacama": "AP004",
 "SERVIU Región de Aysén del General Carlos Ibáñez del Campo": "AP013",
 "SERVIU Región de Coquimbo": "AP005",
 "SERVIU Región de la Araucanía": "AP011",
 "SERVIU Región de Los Lagos": "AP012",
 "SERVIU Región de Los Ríos": "AP015",
 "SERVIU Región de Magallanes y la Antártica Chilena": "AP014",
 "SERVIU Región de Tarapacá": "AP002",
 "SERVIU Región de Valparaíso": "AP006",
 "SERVIU Región del Bío Bío": "AP010",
 "SERVIU Región del Libertador Bernardo OHiggins": "AP008",
 "SERVIU Región del Maule": "AP009",
 "SERVIU Región del Ñuble": "AP018",
 "Sistema de Empresas  SEP": "EP025",
 "Subsecretaría de Agricultura": "AR001",
 "Subsecretaría de Bienes Nacionales": "AQ001",
 "Subsecretaría de Ciencia Tecnología Conocimiento e Innovación": "BD001",
 "Subsecretaría de Defensa": "AD021",
 "Subsecretaría de Derechos Humanos": "AK012",
 "Subsecretaría de Desarrollo Regional y Administrativo (SUBDERE)": "AB002",
 "Subsecretaría de Economía (MINECON)": "AH001",
 "Subsecretaría de Educación (MINEDUC)": "AJ001",
 "Subsecretaría de Educación Parvularia": "AJ014",
 "Subsecretaría de Educación Superior": "AJ025",
 "Subsecretaría de Energía": "AU002",
 "Subsecretaría de Evaluación Social": "AI001",
 "Subsecretaría de Hacienda": "AE001",
 "Subsecretaría de Justicia": "AK001",
 "Subsecretaría de la Mujer y la Equidad de Género": "BB001",
 "Subsecretaría de la Niñez": "AI009",
 "Subsecretaría de las Culturas y las Artes": "BC001",
 "Subsecretaría de Minería": "AS001",
 "Subsecretaría de Obras Públicas (MOP)": "AM001",
 "Subsecretaría de Pesca y Acuicultura": "AH002",
 "Subsecretaría de Prevención del Delito": "AB091",
 "Subsecretaría de Previsión Social (SPS)": "AL002",
 "Subsecretaría de Redes Asistenciales": "AO002",
 "Subsecretaría de Relaciones Económicas Internacionales": "AC007",
 "Subsecretaría de Relaciones Exteriores": "AC001",
 "Subsecretaría de Salud Pública (MINSAL)": "AO001",
 "Subsecretaría de Seguridad Pública": "BE001",
 "Subsecretaría de Servicios Sociales": "AI008",
 "Subsecretaría de Telecomunicaciones (SUBTEL)": "AN002",
 "Subsecretaría de Transportes (MTT)": "AN001",
 "Subsecretaría de Turismo": "AH011",
 "Subsecretaría de Vivienda y Urbanismo (MINVU)": "AP001",
 "Subsecretaría del Deporte": "BA001",
 "Subsecretaría del Interior": "AB001",
 "Subsecretaría del Medio Ambiente (MMA)": "AW002",
 "Subsecretaría del Patrimonio Cultural": "BC002",
 "Subsecretaría del Trabajo (MINTRAB)": "AL001",
 "Subsecretaría General de Gobierno (SEGEGOB)": "AG001",
 "Subsecretaría General de La Presidencia (SEGPRES)": "AF001",
 "Subsecretaría para las Fuerzas Armadas (SSFFAA)": "AD022",
 "Superintendencia de Bancos e Instituciones Financieras (SBIF) derogada por la CMF": "AE008",
 "Superintendencia de Casinos de Juego (SCJ)": "AE012",
 "Superintendencia de Educación Dirección Nacional": "AJ011",
 "Superintendencia de Educación Superior": "AJ021",
 "Superintendencia de Electricidad y Combustibles (SEC)": "AU004",
 "Superintendencia de Insolvencia y Reemprendimiento (SUPERIR)": "AH013",
 "Superintendencia de Pensiones (SP)": "AL008",
 "Superintendencia de Salud (SdS)": "AO006",
 "Superintendencia de Seguridad Social (SUSESO)": "AL009",
 "Superintendencia de Servicios Sanitarios (SISS)": "AM011",
 "Superintendencia del Medio Ambiente (SMA)": "AW003",
 "Tesorería General de la República (TGR)": "AE003",
 "Unidad de Análisis Financiero": "AE005",
 "Universidad de Atacama": "UN004",
 "Universidad de Aysén": "UN017",
 "Universidad de Los Lagos": "UN015",
 "Universidad de Magallanes": "UN016",
 "Universidad de OHiggins (UOH)": "UN018",
 "Universidad de OHiggins": "UN018",
 "Universidad de Santiago de Chile (USACH)": "UN008"
};