const organismoPadres = {
  "Administradora de los Tribunales Tributarios y Aduaneros y del Tribunal de Contratación Pública": "Hacienda",
  "Agencia Chilena de Cooperación Internacional para el Desarrollo (AGCID)": "Relaciones Exteriores",
  "Agencia Chilena de Eficiencia Energética": "Fund. Corp. Asoc. NO municipales",
  "Agencia Nacional de Investigación y Desarrollo ANID": "Ciencia Tecnología e Innovación",
  "Agencia Regional de Desarrollo Productivo de la Araucanía": "Fund. Corp. Asoc. NO municipales",
  "Agencia de Calidad de la Educación": "Educación",
  "Agencia de Promoción de la Inversión Extranjera": "Economía Fomento y Turismo",
  "Armada de Chile": "Defensa Nacional",
  "Asociación Chilena de Municipalidades": "Asociación Municipal",
  "Asociación Cultural Municipal de Cerrillos": "Asociación Municipal",
  "Asociación Metropolitana de Municipalidades de Santiago Sur para la Gestión Ambiental y de Residuos (Msur)": "Asociación Municipal",
  "Asociación Municipalidades Provincia de Llanquihue Para Manejo Sustentable de Residuos y Gestión Ambiental": "Asociación Municipal",
  "Asociación Nacional de Municipalidades de Ciudades Puerto Concesionados": "Asociación Municipal",
  "Asociación Regional de Municipalidades de Magallanes y Antártica Chilena (AMUMAG)": "Asociación Municipal",
  "Asociación Regional de Municipios de Atacama": "Asociación Municipal",
  "Asociación de Gobernadores y Gobernadoras Regionales de Chile  AGORECHI": "Fund. Corp. Asoc. NO municipales",
  "Asociación de Municipalidades Bio Bio Centro": "Asociación Municipal",
  "Asociación de Municipalidades Comunas Costeras de PuchuncavíQuintero": "Asociación Municipal",
  "Asociación de Municipalidades Cordilleranas de la Araucanía": "Asociación Municipal",
  "Asociación de Municipalidades Libres (AML)": "Asociación Municipal",
  "Asociación de Municipalidades Malleco Norte AMMN": "Asociación Municipal",
  "Asociación de Municipalidades Nahuelbuta (AMN)": "Asociación Municipal",
  "Asociación de Municipalidades Parque Cordillera": "Asociación Municipal",
  "Asociación de Municipalidades Red Nacional de Comunas Mágicas de Chile": "Asociación Municipal",
  "Asociación de Municipalidades Rurales (AMUR)": "Asociación Municipal",
  "Asociación de Municipalidades Rurales del Norte Chico": "Asociación Municipal",
  "Asociación de Municipalidades Turísticas de Chile (AMTC)": "Asociación Municipal",
  "Asociación de Municipalidades de Arauco y Curanilahue": "Asociación Municipal",
  "Asociación de Municipalidades de Chile AMUCH": "Asociación Municipal",
  "Asociación de Municipalidades de Ciudades Puerto y Borde Costero": "Asociación Municipal",
  "Asociación de Municipalidades de La Región de Los Ríos": "Asociación Municipal",
  "Asociación de Municipalidades de la Provincia de Arauco": "Asociación Municipal",
  "Asociación de Municipalidades de la Provincia de Osorno": "Asociación Municipal",
  "Asociación de Municipalidades de la Provincia de San Antonio (AMPSA)": "Asociación Municipal",
  "Asociación de Municipalidades de la Región de  Coquimbo": "Asociación Municipal",
  "Asociación de Municipalidades de la Región de Antofagasta": "Asociación Municipal",
  "Asociación de Municipalidades de la Región de Los Ríos para el Manejo sustentable de Residuos y la Gestión Ambiental": "Asociación Municipal",
  "Asociación de Municipalidades de la Región de OHiggins": "Asociación Municipal",
  "Asociación de Municipalidades de la Región de Valparaíso": "Asociación Municipal",
  "Asociación de Municipalidades de la Región del Biobío": "Asociación Municipal",
  "Asociación de Municipalidades de la Zona Central y Costa (AMUCC)": "Asociación Municipal",
  "Asociación de Municipalidades de la Zona Metropolitana de la Araucanía (AMZOMA)": "Asociación Municipal",
  "Asociación de Municipalidades de la cuenca del Lago Llanquihue": "Asociación Municipal",
  "Asociación de Municipalidades de la región de la araucanía o amra araucanía": "Asociación Municipal",
  "Asociación de Municipalidades del Norte de Chile": "Asociación Municipal",
  "Asociación de Municipalidades del Punilla": "Asociación Municipal",
  "Asociación de Municipalidades del Valle del Itata": "Asociación Municipal",
  "Asociación de Municipalidades del Valle del Maipo": "Asociación Municipal",
  "Asociación de Municipalidades para el Desarrollo Económico Local": "Asociación Municipal",
  "Asociación de Municipalidades para la Preservación de la Biodiversidad en el Territorio de Nonguén y otros Ecosistemas": "Asociación Municipal",
  "Asociación de Municipalidades para la Seguridad Ciudadana en la Zona Oriente": "Asociación Municipal",
  "Asociación de Municipios Ciudad Sur": "Asociación Municipal",
  "Asociación de Municipios Cordillera de la Costa CorralLa Unión": "Asociación Municipal",
  "Asociación de Municipios Costa Araucanía": "Asociación Municipal",
  "Asociación de Municipios Metropolitanos para la Seguridad Ciudadana (AMMSeguridad)": "Asociación Municipal",
  "Asociación de Municipios Rurales Regiones de Tarapacá y AricaParinacota": "Asociación Municipal",
  "Asociación de Municipios para el Desarrollo Turístico de las Comunas de Cabrero Los Ángeles y Yumbel": "Asociación Municipal",
  "Asociación de Municipios para la Conservación de la Biodiversidad de la Región de Los Ríos": "Asociación Municipal",
  "Asociación de Municipios para la seguridad comunitaria (AMSC)": "Asociación Municipal",
  "CFT Estatal de la Región del Biobío": "Centro de Formación Técnica",
  "CFT Estatal de la Región del Maule": "Centro de Formación Técnica",
  "CFT Magallanes": "Centro de Formación Técnica",
  "CFT de la Región Metropolitana (CFTRM)": "Centro de Formación Técnica",
  "CFT de la Región de Antofagasta": "Centro de Formación Técnica",
  "CFT de la Región de Arica y Parinacota": "Centro de Formación Técnica",
  "CFT de la Región de Atacama": "Centro de Formación Técnica",
  "CFT de la Región de Los Ríos": "Centro de Formación Técnica",
  "CFT de la Región de OHiggins": "Centro de Formación Técnica",
  "CFT de la Región de Valparaíso": "Centro de Formación Técnica",
  "CFT de la Región de la Araucanía": "Centro de Formación Técnica",
  "CFT de la Región de los Lagos": "Centro de Formación Técnica",
  "CFT de la Región del Tarapacá": "Centro de Formación Técnica",
  "CLUB DE LA REINA SOCIAL DEPORTIVO Y RECREACIONAL": "Corporaciones Municipales",
  "CORPORACIÓN REGIONAL DE TURISMO DE LA REGIÓN METROPOLITANA": "Fund. Corp. Asoc. NO municipales",
  "Caja de Previsión de la Defensa Nacional (CAPREDENA)": "Defensa Nacional",
  "Carabineros de Chile": "Interior",
  "Central de Abastecimiento del Sistema Nacional de Servicios de Salud (CENABAST)": "Salud",
  "Centro de Formación Técnica Estatal Región de Coquimbo": "Centro de Formación Técnica",
  "Centro de Información de Recursos Naturales (CIREN)": "Agricultura",
  "Centro de Referencia de Salud de Maipú (CRSM)": "Salud",
  "Centro de Referencia de Salud de Peñalolén Cordillera Oriente (CRSORIENTE)": "Salud",
  "Comercializadora de Trigo COTRISA": "Empresas y Sociedades",
  "Comisión Administradora del Sistema de Créditos para Estudios Superiores (INGRESA)": "Educación",
  "Comisión Chilena de Energía Nuclear (CCHEN)": "Energía",
  "Comisión Chilena del Cobre (COCHILCO)": "Minería",
  "Comisión Nacional de Acreditación (CNA)": "Educación",
  "Comisión Nacional de Energía (CNE)": "Energía",
  "Comisión Nacional de Riego (CNR)": "Agricultura",
  "Comisión del Sistema Nacional de Certificación de Competencias Laborales": "Trabajo y Previsión Social",
  "Comisión para el Mercado Financiero  CMF ex SVS": "Hacienda",
  "Consejo Fiscal Autónomo": "Consejo Fiscal Autónomo",
  "Consejo Nacional de Educación (CNED)": "Educación",
  "Consejo Nacional de Televisión (CNTV)": "Secretaría General de Gobierno",
  "Consejo de Defensa del Estado (CDE)": "Consejo Defensa del Estado",
  "Consejo de Rectores": "Educación",
  "Consejo para la Transparencia (CPLT)": "Consejo para la Transparencia",
  "Corporación Cultural Aldea del Encuentro La Reina": "Corporaciones Municipales",
  "Corporación Cultural Isla de Maipo": "Corporaciones Municipales",
  "Corporación Cultural Municipal de La Comuna de Chillán": "Corporaciones Municipales",
  "Corporación Cultural Municipal de La Comuna de Villarrica": "Corporaciones Municipales",
  "Corporación Cultural Municipal de Los Ángeles": "Corporaciones Municipales",
  "Corporación Cultural Municipal de Ovalle": "Corporaciones Municipales",
  "Corporación Cultural Municipal de Padre Las Casas": "Corporaciones Municipales",
  "Corporación Cultural Municipal de Puente Alto": "Corporaciones Municipales",
  "Corporación Cultural Municipal de San Javier de Loncomilla": "Corporaciones Municipales",
  "Corporación Cultural Municipal de Vicuña": "Corporaciones Municipales",
  "Corporación Cultural Municipalidad de Coyhaique": "Corporaciones Municipales",
  "Corporación Cultural Social y Deportiva Municipal de Quilicura": "Corporaciones Municipales",
  "Corporación Cultural de Antofagasta": "Corporaciones Municipales",
  "Corporación Cultural de Estación Central": "Corporaciones Municipales",
  "Corporación Cultural de La Ilustre Municipalidad de Romeral": "Corporaciones Municipales",
  "Corporación Cultural de La Ilustre Municipalidad de Valdivia": "Corporaciones Municipales",
  "Corporación Cultural de La Reina": "Corporaciones Municipales",
  "Corporación Cultural de Lampa": "Corporaciones Municipales",
  "Corporación Cultural de Las Condes": "Corporaciones Municipales",
  "Corporación Cultural de Lo Barnechea": "Corporaciones Municipales",
  "Corporación Cultural de Mostazal": "Corporaciones Municipales",
  "Corporación Cultural de Nacimiento": "Corporaciones Municipales",
  "Corporación Cultural de Osorno": "Corporaciones Municipales",
  "Corporación Cultural de Peñalolén": "Corporaciones Municipales",
  "Corporación Cultural de Recoleta": "Corporaciones Municipales",
  "Corporación Cultural de San Pedro de La Paz": "Corporaciones Municipales",
  "Corporación Cultural de Teno": "Corporaciones Municipales",
  "Corporación Cultural de Vitacura": "Corporaciones Municipales",
  "Corporación Cultural de la Comuna de La Granja": "Corporaciones Municipales",
  "Corporación Cultural de la Municipalidad de Curicó": "Corporaciones Municipales",
  "Corporación Cultural de Ñuñoa": "Corporaciones Municipales",
  "Corporación Cultural y de Extensión de La Ilustre Municipalidad de Constitución": "Corporaciones Municipales",
  "Corporación Deportiva Municipal de San Pedro de La Paz": "Corporaciones Municipales",
  "Corporación Municipal Cultural Museo de Bellas Artes Valparaíso": "Corporaciones Municipales",
  "Corporación Municipal Cultural y Patrimonial de San Bernardo": "Corporaciones Municipales",
  "Corporación Municipal Deportiva Cultural y de Fomento Productivo Alto Hospicio": "Corporaciones Municipales",
  "Corporación Municipal Isla de Maipo": "Corporaciones Municipales",
  "Corporación Municipal Pueblito de Las Vizcachas": "Corporaciones Municipales",
  "Corporación Municipal de Administración Sitio Patrimonio Mundial Área Histórica de la Cuidad Puerto de Valparaíso": "Corporaciones Municipales",
  "Corporación Municipal de Ancud": "Corporaciones Municipales",
  "Corporación Municipal de Calera De Tango": "Corporaciones Municipales",
  "Corporación Municipal de Castro": "Corporaciones Municipales",
  "Corporación Municipal de Colina": "Corporaciones Municipales",
  "Corporación Municipal de Cultura La Pintana": "Corporaciones Municipales",
  "Corporación Municipal de Cultura San Clemente": "Corporaciones Municipales",
  "Corporación Municipal de Cultura Turismo y Patrimonio de La Comuna de Natales": "Corporaciones Municipales",
  "Corporación Municipal de Cultura de Paine": "Corporaciones Municipales",
  "Corporación Municipal de Cultura de San Joaquín": "Corporaciones Municipales",
  "Corporación Municipal de Cultura de Talca": "Corporaciones Municipales",
  "Corporación Municipal de Cultura de TilTil": "Corporaciones Municipales",
  "Corporación Municipal de Cultura y Artes de Molina": "Corporaciones Municipales",
  "Corporación Municipal de Cultura y Turismo de La Comuna de Quintero": "Corporaciones Municipales",
  "Corporación Municipal de Curaco De Velez": "Corporaciones Municipales",
  "Corporación Municipal de Deporte Quinta Normal": "Corporaciones Municipales",
  "Corporación Municipal de Deporte de Padre Hurtado": "Corporaciones Municipales",
  "Corporación Municipal de Deporte de Romeral": "Corporaciones Municipales",
  "Corporación Municipal de Deporte y Recreación de Recoleta": "Corporaciones Municipales",
  "Corporación Municipal de Deportes La Pintana": "Corporaciones Municipales",
  "Corporación Municipal de Deportes de Caldera": "Corporaciones Municipales",
  "Corporación Municipal de Deportes de Colina": "Corporaciones Municipales",
  "Corporación Municipal de Deportes de Iquique (CORMUDEPI)": "Corporaciones Municipales",
  "Corporación Municipal de Deportes de Lo Prado": "Corporaciones Municipales",
  "Corporación Municipal de Deportes de Natales": "Corporaciones Municipales",
  "Corporación Municipal de Deportes de Padre Las Casas": "Corporaciones Municipales",
  "Corporación Municipal de Deportes de Puente Alto": "Corporaciones Municipales",
  "Corporación Municipal de Deportes de Rancagua": "Corporaciones Municipales",
  "Corporación Municipal de Deportes de San Joaquín": "Corporaciones Municipales",
  "Corporación Municipal de Deportes de Talca": "Corporaciones Municipales",
  "Corporación Municipal de Deportes de Ñuñoa": "Corporaciones Municipales",
  "Corporación Municipal de Deportes y Desarrollo Social de Quintero": "Corporaciones Municipales",
  "Corporación Municipal de Deportes y Recreación de Antofagasta": "Corporaciones Municipales",
  "Corporación Municipal de Deportes y Recreación de Coyhaique": "Corporaciones Municipales",
  "Corporación Municipal de Deportes y Recreación de La Ilustre Municipalidad de Isla de Pascua": "Corporaciones Municipales",
  "Corporación Municipal de Deportes y Recreación de Molina": "Corporaciones Municipales",
  "Corporación Municipal de Deportes y Recreación de Panguipulli": "Corporaciones Municipales",
  "Corporación Municipal de Deportes y Recreación de Talcahuano": "Corporaciones Municipales",
  "Corporación Municipal de Deportes y Recreación de Tocopilla": "Corporaciones Municipales",
  "Corporación Municipal de Desarrollo Económico Cultura y Deporte de Renca": "Corporaciones Municipales",
  "Corporación Municipal de Desarrollo Económico de Peñalolén (YUNUS)": "Corporaciones Municipales",
  "Corporación Municipal de Desarrollo Productivo y Turismo de Molina": "Corporaciones Municipales",
  "Corporación Municipal de Desarrollo Social de Antofagasta (CMDS)": "Corporaciones Municipales",
  "Corporación Municipal de Desarrollo Social de Calama (COMDES)": "Corporaciones Municipales",
  "Corporación Municipal de Desarrollo Social de Los Muermos": "Corporaciones Municipales",
  "Corporación Municipal de Desarrollo Social de San Joaquin": "Corporaciones Municipales",
  "Corporación Municipal de Desarrollo Social de Tiltil": "Corporaciones Municipales",
  "Corporación Municipal de Desarrollo Social de Ñuñoa": "Corporaciones Municipales",
  "Corporación Municipal de Educación y Salud de San Bernardo": "Corporaciones Municipales",
  "Corporación Municipal de Educación y Servicios Ramón Freire Dalcahue": "Corporaciones Municipales",
  "Corporación Municipal de Fomento Al Desarrollo Comunal y Productivo de La Florida (Cofodep)": "Corporaciones Municipales",
  "Corporación Municipal de Fomento Al Desarrollo Económico y Productivo de Estación Central": "Corporaciones Municipales",
  "Corporación Municipal de Fomento Productivo de Curicó": "Corporaciones Municipales",
  "Corporación Municipal de Fomento al Desarrollo Comunal y Productivo de Parral": "Corporaciones Municipales",
  "Corporación Municipal de La Cultura y Las Artes de San Antonio": "Corporaciones Municipales",
  "Corporación Municipal de La Reina": "Corporaciones Municipales",
  "Corporación Municipal de Lo Prado": "Corporaciones Municipales",
  "Corporación Municipal de Macul": "Corporaciones Municipales",
  "Corporación Municipal de Maria Pinto": "Corporaciones Municipales",
  "Corporación Municipal de Melipilla": "Corporaciones Municipales",
  "Corporación Municipal de Peñalolén (CORMUP)": "Corporaciones Municipales",
  "Corporación Municipal de Pirque": "Corporaciones Municipales",
  "Corporación Municipal de Pozo Almonte": "Corporaciones Municipales",
  "Corporación Municipal de Providencia": "Corporaciones Municipales",
  "Corporación Municipal de Pudahuel": "Corporaciones Municipales",
  "Corporación Municipal de Puente Alto": "Corporaciones Municipales",
  "Corporación Municipal de Puqueldón": "Corporaciones Municipales",
  "Corporación Municipal de Queilen": "Corporaciones Municipales",
  "Corporación Municipal de Quellón": "Corporaciones Municipales",
  "Corporación Municipal de Quilpué": "Corporaciones Municipales",
  "Corporación Municipal de Quinchao": "Corporaciones Municipales",
  "Corporación Municipal de Quinta Normal": "Corporaciones Municipales",
  "Corporación Municipal de Rancagua (CORMUN)": "Corporaciones Municipales",
  "Corporación Municipal de Renca": "Corporaciones Municipales",
  "Corporación Municipal de Salud de Panguipulli": "Corporaciones Municipales",
  "Corporación Municipal de San Fernando (CORMUSAF)": "Corporaciones Municipales",
  "Corporación Municipal de San Vicente": "Corporaciones Municipales",
  "Corporación Municipal de Servicios y Desarrollo de Maipú (CODEDUC)": "Corporaciones Municipales",
  "Corporación Municipal de Talagante": "Corporaciones Municipales",
  "Corporación Municipal de Turismo de Paihuano": "Corporaciones Municipales",
  "Corporación Municipal de Turismo de Vicuña": "Corporaciones Municipales",
  "Corporación Municipal de Valparaíso": "Corporaciones Municipales",
  "Corporación Municipal de cultura de Isla de Pascua": "Corporaciones Municipales",
  "Corporación Municipal de desarrollo Comunal y Productivo de Licantén": "Corporaciones Municipales",
  "Corporación Municipal de innovación y desarrollo económico y social de SAN JOAQUÍN": "Corporaciones Municipales",
  "Corporación Municipal del Arte y la Cultura de Talagante": "Corporaciones Municipales",
  "Corporación Municipal para el Desarrollo Social de Villa Alemana": "Corporaciones Municipales",
  "Corporación Nacional Forestal (CONAF)": "Agricultura",
  "Corporación Nacional de Desarrollo Indígena (CONADI)": "Desarrollo Social",
  "Corporación Para El Desarrollo de La Provincia de Osorno (Corposorno)": "Corporaciones Municipales",
  "Corporación Regional de Desarrollo Productivo de la Región de Tarapacá": "Fund. Corp. Asoc. NO municipales",
  "Corporación Regional de Desarrollo de la Región del Biobío (Desarrolla Biobío)": "Fund. Corp. Asoc. NO municipales",
  "Corporación Regional de Investigación y Desarrollo Centro de Investigación en Ecosistemas de la Patagonia": "Fund. Corp. Asoc. NO municipales",
  "Corporación Social y Cultural de Concepción (SEMCO)": "Corporaciones Municipales",
  "Corporación Teatro Regional Del Biobío": "Fund. Corp. Asoc. NO municipales",
  "Corporación XIX Juegos Panamericanos Santiago 2023": "Corporaciones Municipales",
  "Corporación cultural de Ancud": "Corporaciones Municipales",
  "Corporación de Asistencia Judicial Regiones Tarapacá y Antofagasta (CAJTA)": "Justicia",
  "Corporación de Asistencia Judicial Región Bío Bío (CAJBIOBIO)": "Justicia",
  "Corporación de Asistencia Judicial Región Valparaíso (CAJVAL)": "Justicia",
  "Corporación de Asistencia Judicial de la Región Metropolitana (CAJMETRO)": "Justicia",
  "Corporación de Cultura de Pichidegua": "Corporaciones Municipales",
  "Corporación de Cultura y Patrimonio de Independencia": "Corporaciones Municipales",
  "Corporación de Cultura y Turismo de Calama": "Corporaciones Municipales",
  "Corporación de Deporte de Estación Central Cormudep": "Corporaciones Municipales",
  "Corporación de Deporte de Los Andes": "Corporaciones Municipales",
  "Corporación de Deporte y Recreacion de La Municipalidad de Aysén": "Corporaciones Municipales",
  "Corporación de Deportes Constitución": "Corporaciones Municipales",
  "Corporación de Deportes de La Ilustre Municipalidad de Teno": "Corporaciones Municipales",
  "Corporación de Deportes de Parral": "Corporaciones Municipales",
  "Corporación de Deportes de San Clemente": "Corporaciones Municipales",
  "Corporación de Deportes de la Ilustre Municipalidad de Curicó": "Corporaciones Municipales",
  "Corporación de Deportes de la Municipalidad de Independencia": "Corporaciones Municipales",
  "Corporación de Deportes y Recreación La Reina": "Corporaciones Municipales",
  "Corporación de Deportes y Recreación de Peñalolén": "Corporaciones Municipales",
  "Corporación de Deportes y Recreación de San Javier Loncomilla": "Corporaciones Municipales",
  "Corporación de Desarrollo Social de Buin": "Corporaciones Municipales",
  "Corporación de Desarrollo Social de Cerro Navia (CORMUCENA)": "Corporaciones Municipales",
  "Corporación de Desarrollo Social de la Municipalidad de Independencia": "Corporaciones Municipales",
  "Corporación de Desarrollo de Magallanes y de la Antártica chilena.": "Fund. Corp. Asoc. NO municipales",
  "Corporación de Desarrollo de Talca": "Corporaciones Municipales",
  "Corporación de Desarrollo e Innovación de Rancagua": "Corporaciones Municipales",
  "Corporación de Educación Salud y Atención de Menores Chonchi Chiloé": "Corporaciones Municipales",
  "Corporación de Educación Salud y Menores de Puerto Natales": "Corporaciones Municipales",
  "Corporación de Educación y Salud de Las Condes": "Corporaciones Municipales",
  "Corporación de Fomento de Desarrollo comunal y Productivo de la Granja": "Corporaciones Municipales",
  "Corporación de Fomento de la Producción (CORFO)": "Economía Fomento y Turismo",
  "Corporación de Inclusión Social de Cerro Navia": "Corporaciones Municipales",
  "Corporación de Innovación y Desarrollo Económico y Social Innova Recoleta": "Corporaciones Municipales",
  "Corporación de desarrollo territorial de la región de Arica y Parinacota": "Fund. Corp. Asoc. NO municipales",
  "Corporación de investigación y avance de la Paleontología e historia natural de Atacama": "Fund. Corp. Asoc. NO municipales",
  "Corporación de la Cultura y las Artes de la Ilustre Municipalidad de Rancagua": "Corporaciones Municipales",
  "Corporación del Deporte de Lampa": "Corporaciones Municipales",
  "Corporación del Deporte de Pichidegua": "Corporaciones Municipales",
  "Defensoría Penal Pública (DPP)": "Justicia",
  "Defensoría de los Derechos de la Niñez": "Defensoría de los Derechos de la Niñez",
  "Defensoría del Contribuyente": "Hacienda",
  "Delegación Presidencial Provincial de Arauco": "Interior",
  "Delegación Presidencial Provincial de Aysén": "Interior",
  "Delegación Presidencial Provincial de Capitán Prat": "Interior",
  "Delegación Presidencial Provincial de Cardenal Caro": "Interior",
  "Delegación Presidencial Provincial de Cauquenes": "Interior",
  "Delegación Presidencial Provincial de Chacabuco": "Interior",
  "Delegación Presidencial Provincial de Chañaral": "Interior",
  "Delegación Presidencial Provincial de Chiloé": "Interior",
  "Delegación Presidencial Provincial de Choapa": "Interior",
  "Delegación Presidencial Provincial de Colchagua": "Interior",
  "Delegación Presidencial Provincial de Cordillera": "Interior",
  "Delegación Presidencial Provincial de Curicó": "Interior",
  "Delegación Presidencial Provincial de El Loa": "Interior",
  "Delegación Presidencial Provincial de General Carrera": "Interior",
  "Delegación Presidencial Provincial de Huasco": "Interior",
  "Delegación Presidencial Provincial de Isla de Pascua": "Interior",
  "Delegación Presidencial Provincial de Itata": "Interior",
  "Delegación Presidencial Provincial de La Antártica Chilena": "Interior",
  "Delegación Presidencial Provincial de Limarí": "Interior",
  "Delegación Presidencial Provincial de Linares": "Interior",
  "Delegación Presidencial Provincial de Los Andes": "Interior",
  "Delegación Presidencial Provincial de Maipo": "Interior",
  "Delegación Presidencial Provincial de Malleco": "Interior",
  "Delegación Presidencial Provincial de Marga Marga": "Interior",
  "Delegación Presidencial Provincial de Melipilla": "Interior",
  "Delegación Presidencial Provincial de Osorno": "Interior",
  "Delegación Presidencial Provincial de Palena": "Interior",
  "Delegación Presidencial Provincial de Parinacota": "Interior",
  "Delegación Presidencial Provincial de Petorca": "Interior",
  "Delegación Presidencial Provincial de Punilla": "Interior",
  "Delegación Presidencial Provincial de Quillota": "Interior",
  "Delegación Presidencial Provincial de San Antonio": "Interior",
  "Delegación Presidencial Provincial de San Felipe": "Interior",
  "Delegación Presidencial Provincial de Talagante": "Interior",
  "Delegación Presidencial Provincial de Tamarugal": "Interior",
  "Delegación Presidencial Provincial de Tierra del Fuego": "Interior",
  "Delegación Presidencial Provincial de Tocopilla": "Interior",
  "Delegación Presidencial Provincial de última Esperanza": "Interior",
  "Delegación Presidencial Provincial del Bíobío": "Interior",
  "Delegación Presidencial Provincial del Ranco": "Interior",
  "Delegación Presidencial Regional Metropolitana": "Interior",
  "Delegación Presidencial Regional de Antofagasta": "Interior",
  "Delegación Presidencial Regional de Arica y Parinacota": "Interior",
  "Delegación Presidencial Regional de Atacama": "Interior",
  "Delegación Presidencial Regional de Aysén del General Carlos Ibáñez del Campo": "Interior",
  "Delegación Presidencial Regional de Coquimbo": "Interior",
  "Delegación Presidencial Regional de La Araucanía": "Interior",
  "Delegación Presidencial Regional de Los Lagos": "Interior",
  "Delegación Presidencial Regional de Los Ríos": "Interior",
  "Delegación Presidencial Regional de Magallanes y la Antártica Chilena": "Interior",
  "Delegación Presidencial Regional de Tarapacá": "Interior",
  "Delegación Presidencial Regional de Valparaíso": "Interior",
  "Delegación Presidencial Regional de Ñuble": "Interior",
  "Delegación Presidencial Regional del Biobío": "Interior",
  "Delegación Presidencial Regional del Libertador General Bernardo OHiggins": "Interior",
  "Delegación Presidencial Regional del Maule": "Interior",
  "Dirección General de Aeronáutica Civil (DGAC)": "Defensa Nacional",
  "Dirección General de Aguas (DGA)": "Obras Públicas",
  "Dirección General de Concesiones (DGC)": "Obras Públicas",
  "Dirección General de Crédito Prendario (DICREP)": "Trabajo y Previsión Social",
  "Dirección General de Movilización Nacional (DGMN)": "Defensa Nacional",
  "Dirección General de Obras Públicas (DGOP)": "Obras Públicas",
  "Dirección Nacional de Fronteras y Límites del Estado (DIFROL)": "Relaciones Exteriores",
  "Dirección Nacional del Servicio Civil": "Hacienda",
  "Dirección de Aeropuertos (DAP)": "Obras Públicas",
  "Dirección de Arquitectura (DARQ)": "Obras Públicas",
  "Dirección de Compras y Contratación Pública (CHILECOMPRA)": "Hacienda",
  "Dirección de Contabilidad y Finanzas (DCYF)": "Obras Públicas",
  "Dirección de Educación Pública": "Educación",
  "Dirección de Obras Hidráulicas (DOH)": "Obras Públicas",
  "Dirección de Obras Portuarias (DOP)": "Obras Públicas",
  "Dirección de Planeamiento (DIRPLAN)": "Obras Públicas",
  "Dirección de Presupuestos (DIPRES)": "Hacienda",
  "Dirección de Previsión de Carabineros de Chile (DIPRECA)": "Interior",
  "Dirección de Vialidad (VIALIDAD)": "Obras Públicas",
  "Dirección del Trabajo (DT)": "Trabajo y Previsión Social",
  "Ejército de Chile": "Defensa Nacional",
  "Estado Mayor Conjunto (EMCO)": "Defensa Nacional",
  "Fiscalía Nacional Económica (FNE)": "Economía Fomento y Turismo",
  "Fiscalía de Obras Públicas": "Obras Públicas",
  "Fondo Nacional de Salud (FONASA)": "Salud",
  "Fondo de Solidaridad e Inversión Social (FOSIS)": "Desarrollo Social",
  "Fuerza Aérea de Chile (Incluye al Servicio Aerofotogramétrico)": "Defensa Nacional",
  "Fundación Artesanías de Chile": "Fund. Corp. Asoc. NO municipales",
  "Fundación Centro Cultural Palacio de La Moneda": "Fund. Corp. Asoc. NO municipales",
  "Fundación Centro Cultural de Lo Prado": "Fund. Corp. Asoc. NO municipales",
  "Fundación Cultural Providencia": "Fund. Corp. Asoc. NO municipales",
  "Fundación Cultural de Sierra Gorda": "Fund. Corp. Asoc. NO municipales",
  "Fundación Cultural de la municipalidad de Tocopilla": "Fundaciones y Otros Organismos Municipales",
  "Fundación Integra": "Fund. Corp. Asoc. NO municipales",
  "Fundación Teatro Municipal de Las Condes": "Fund. Corp. Asoc. NO municipales",
  "Fundación Tiempos Nuevos (MIM)": "Fund. Corp. Asoc. NO municipales",
  "Fundación de Orquestas Juveniles e Infantiles de Chile (FOJI)": "Fund. Corp. Asoc. NO municipales",
  "Fundación del deporte de Punta Arenas": "Fund. Corp. Asoc. NO municipales",
  "Fundación para el Desarrollo de la Cultura y las Artes de la comuna de Punta Arenas": "Fund. Corp. Asoc. NO municipales",
  "Fundación para la Promoción y Desarrollo de la Mujer  (PRODEMU)": "Fund. Corp. Asoc. NO municipales",
  "Gobierno Regional Metropolitano de Santiago  (GORE Metropolitano)": "Interior",
  "Gobierno Regional de Antofagasta (GORE)": "Interior",
  "Gobierno Regional de Arica y Parinacota (GORE)": "Interior",
  "Gobierno Regional de Atacama (GORE)": "Interior",
  "Gobierno Regional de Aysén (GORE Aysén)": "Interior",
  "Gobierno Regional de Coquimbo  GORECOQUIMBO": "Interior",
  "Gobierno Regional de La Araucanía (Gore Araucanía)": "Interior",
  "Gobierno Regional de Los Lagos (Gore Los Lagos)": "Interior",
  "Gobierno Regional de Los Ríos (GORE de Los Ríos)": "Interior",
  "Gobierno Regional de Magallanes y de la Antártica Chilena (GORE Magallanes)": "Interior",
  "Gobierno Regional de OHiggins (Gore OHiggins)": "Interior",
  "Gobierno Regional de Tarapacá (GORE)": "Interior",
  "Gobierno Regional de Valparaíso  (GORE)": "Interior",
  "Gobierno Regional de Ñuble (GORE)": "Interior",
  "Gobierno Regional del Bío Bío (Gore Bío Bío)": "Interior",
  "Gobierno Regional del Maule (Gore Maule)": "Interior",
  "Hospital Barros Luco": "Salud",
  "Hospital Base de Valdivia": "Salud",
  "Hospital Carlos Van Buren": "Salud",
  "Hospital Claudio Vicuña de San Antonio": "Salud",
  "Hospital Clínico Magallanes Dr Lautaro Navarro Aravia": "Salud",
  "Hospital Clínico Metropolitano La Florida Dra. Eloísa Díaz Insunza": "Salud",
  "Hospital Dr. Augusto Riffart de Castro": "Salud",
  "Hospital Dr. Carlos Cisternas De Calama": "Salud",
  "Hospital Dr. Exequiel González Cortes": "Salud",
  "Hospital Dr. Hernán Henríquez Aravena de Temuco": "Salud",
  "Hospital Dr. Mauricio Heyermann Torres de Angol": "Salud",
  "Hospital Eduardo Pereira de Valparaíso": "Salud",
  "Hospital El Carmen Dr. Luis Valentín Ferrada": "Salud",
  "Hospital El Pino": "Salud",
  "Hospital Ernesto Torres de Iquique": "Salud",
  "Hospital Félix Bulnes": "Salud",
  "Hospital Guillermo Grant Benavente de Concepción": "Salud",
  "Hospital Gustavo Fricke": "Salud",
  "Hospital Herminda Martin": "Salud",
  "Hospital Juan Noé de Arica": "Salud",
  "Hospital La Serena": "Salud",
  "Hospital Leonardo Guzmán de Antofagasta": "Salud",
  "Hospital Luis Calvo Mackenna": "Salud",
  "Hospital Luis Tisné": "Salud",
  "Hospital Padre Hurtado": "Salud",
  "Hospital Regional Copiapó San José del Carmen": "Salud",
  "Hospital Regional Coyhaique": "Salud",
  "Hospital Regional de Rancagua": "Salud",
  "Hospital Regional de Talca": "Salud",
  "Hospital Roberto del Río": "Salud",
  "Hospital San Borja Arriarán": "Salud",
  "Hospital San José": "Salud",
  "Hospital San José de Coronel": "Salud",
  "Hospital San Juan de Dios": "Salud",
  "Hospital San Juan de Dios de Los Andes": "Salud",
  "Hospital San Juan de Dios de San Fernando": "Salud",
  "Hospital San Martín de Quillota": "Salud",
  "Hospital San Pablo de Coquimbo": "Salud",
  "Hospital Sótero del Río": "Salud",
  "Hospital Víctor Ríos Ruiz de Los Angeles": "Salud",
  "Hospital de Curicó": "Salud",
  "Hospital de Linares": "Salud",
  "Hospital de Lota": "Salud",
  "Hospital de Melipilla": "Salud",
  "Hospital de Osorno": "Salud",
  "Hospital de Ovalle": "Salud",
  "Hospital de Puerto Montt": "Salud",
  "Hospital de Quilpué": "Salud",
  "Hospital de San Camilo": "Salud",
  "Hospital de San Carlos": "Salud",
  "Hospital de Tomé": "Salud",
  "Hospital de Urgencia Asistencia Pública (HUAP)": "Salud",
  "Hospital de Victoria": "Salud",
  "Hospital de las Higueras": "Salud",
  "Hospital del Salvador": "Salud",
  "I. Municipalidad de Macul": "Municipios de R. Metropolitana de Santiago",
  "I. Municipalidad de Negrete": "Municipios del Bíobio",
  "I. Municipalidad de Penco": "Municipios del Bíobio",
  "Ilustre Municipalidad de Constitución": "Municipios del Maule",
  "Ilustre Municipalidad de Olivar": "Municipios del Libertador General Bernardo OHiggins",
  "Instituto Antártico Chileno (INACH)": "Relaciones Exteriores",
  "Instituto Forestal (INFOR)": "Agricultura",
  "Instituto Nacional de Derechos Humanos (INDH)": "Instituto Derechos Humanos",
  "Instituto Nacional de Desarrollo Sustentable de la Pesca Artesanal y de la Acuicultura de Pequeña Escala (INDESPA)": "Economía Fomento y Turismo",
  "Instituto Nacional de Estadisticas (INE)": "Economía Fomento y Turismo",
  "Instituto Nacional de Geriatría (INGER)": "Salud",
  "Instituto Nacional de Hidráulica (INH)": "Obras Públicas",
  "Instituto Nacional de Propiedad Industrial (INAPI)": "Economía Fomento y Turismo",
  "Instituto Nacional de Rehabilitación Pedro Aguirre Cerda": "Salud",
  "Instituto Nacional de la Juventud (INJUV)": "Desarrollo Social",
  "Instituto Nacional del Cáncer": "Salud",
  "Instituto Nacional del Deporte (IND)": "Deporte",
  "Instituto Nacional del Tórax": "Salud",
  "Instituto Psiquiátrico": "Salud",
  "Instituto Traumatológico": "Salud",
  "Instituto de Desarrollo Agropecuario (INDAP)": "Agricultura",
  "Instituto de Neurocirugía": "Salud",
  "Instituto de Previsión Social (IPS)": "Trabajo y Previsión Social",
  "Instituto de Salud Pública (ISP)": "Salud",
  "Instituto de Seguridad Laboral (ISL)": "Trabajo y Previsión Social",
  "Junta Nacional de Auxilio Escolar y Becas (JUNAEB)": "Educación",
  "Junta Nacional de Jardines Infantiles (JUNJI)": "Educación",
  "Junta de Aeronáutica Civil (JAC)": "Transportes y Telecomunicaciones",
  "Municipalidad de Algarrobo": "Municipios de Valparaíso",
  "Municipalidad de Alhué": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Alto Biobío": "Municipios del Bíobio",
  "Municipalidad de Alto del Carmen": "Municipios de Atacama",
  "Municipalidad de Andacollo": "Municipios de Coquimbo",
  "Municipalidad de Angol": "Municipios de La Araucanía",
  "Municipalidad de Antofagasta": "Municipios de Antofagasta",
  "Municipalidad de Antuco": "Municipios del Bíobio",
  "Municipalidad de Arauco": "Municipios del Bíobio",
  "Municipalidad de Aysén": "Municipios de Aysen del General Carlos Ibáñez del Campo",
  "Municipalidad de Buin": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Bulnes": "Municipios de Ñuble",
  "Municipalidad de Cabildo": "Municipios de Valparaíso",
  "Municipalidad de Cabo de Hornos y Antártica": "Municipios de Magallanes y de la Antártica Chilena",
  "Municipalidad de Calama": "Municipios de Antofagasta",
  "Municipalidad de Calbuco": "Municipios de Los Lagos",
  "Municipalidad de Caldera": "Municipios de Atacama",
  "Municipalidad de Calera de Tango": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Calle Larga": "Municipios de Valparaíso",
  "Municipalidad de Camarones": "Municipios de Arica y  Parinacota",
  "Municipalidad de Camiña": "Municipios de Tarapacá",
  "Municipalidad de Canela": "Municipios de Coquimbo",
  "Municipalidad de Cartagena": "Municipios de Valparaíso",
  "Municipalidad de Casablanca": "Municipios de Valparaíso",
  "Municipalidad de Catemu": "Municipios de Valparaíso",
  "Municipalidad de Cauquenes": "Municipios del Maule",
  "Municipalidad de Cañete": "Municipios del Bíobio",
  "Municipalidad de Cerrillos": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Cerro Navia": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Chaitén": "Municipios de Los Lagos",
  "Municipalidad de Chanco": "Municipios del Maule",
  "Municipalidad de Chañaral": "Municipios de Atacama",
  "Municipalidad de Chiguayante": "Municipios del Bíobio",
  "Municipalidad de Chile Chico": "Municipios de Aysen del General Carlos Ibáñez del Campo",
  "Municipalidad de Chillán": "Municipios de Ñuble",
  "Municipalidad de Chillán Viejo": "Municipios de Ñuble",
  "Municipalidad de Chimbarongo": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Cholchol": "Municipios de La Araucanía",
  "Municipalidad de Chépica": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Cisnes": "Municipios de Aysen del General Carlos Ibáñez del Campo",
  "Municipalidad de Cobquecura": "Municipios de Ñuble",
  "Municipalidad de Cochamó": "Municipios de Los Lagos",
  "Municipalidad de Cochrane": "Municipios de Aysen del General Carlos Ibáñez del Campo",
  "Municipalidad de Codegua": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Coelemu": "Municipios de Ñuble",
  "Municipalidad de Coihueco": "Municipios de Ñuble",
  "Municipalidad de Coinco": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Colbún": "Municipios del Maule",
  "Municipalidad de Colchane": "Municipios de Tarapacá",
  "Municipalidad de Colina": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Collipulli": "Municipios de La Araucanía",
  "Municipalidad de Coltauco": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Combarbalá": "Municipios de Coquimbo",
  "Municipalidad de Concepción": "Municipios del Bíobio",
  "Municipalidad de Conchalí": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Coquimbo": "Municipios de Coquimbo",
  "Municipalidad de Coronel": "Municipios del Bíobio",
  "Municipalidad de Corral": "Municipios de Los Ríos",
  "Municipalidad de Coyhaique": "Municipios de Aysen del General Carlos Ibáñez del Campo",
  "Municipalidad de Cunco": "Municipios de La Araucanía",
  "Municipalidad de Curacautín": "Municipios de La Araucanía",
  "Municipalidad de Curaco de Vélez": "Municipios de Los Lagos",
  "Municipalidad de Curanilahue": "Municipios del Bíobio",
  "Municipalidad de Curarrehue": "Municipios de La Araucanía",
  "Municipalidad de Curicó": "Municipios del Maule",
  "Municipalidad de Dalcahue": "Municipios de Los Lagos",
  "Municipalidad de Diego de Almagro": "Municipios de Atacama",
  "Municipalidad de Doñihue": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de El Bosque": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de El Carmen": "Municipios de Ñuble",
  "Municipalidad de El Monte": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de El Quisco": "Municipios de Valparaíso",
  "Municipalidad de El Tabo": "Municipios de Valparaíso",
  "Municipalidad de Empedrado": "Municipios del Maule",
  "Municipalidad de Ercilla": "Municipios de La Araucanía",
  "Municipalidad de Estación Central": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Florida": "Municipios del Bíobio",
  "Municipalidad de Freire": "Municipios de La Araucanía",
  "Municipalidad de Freirina": "Municipios de Atacama",
  "Municipalidad de Fresia": "Municipios de Los Lagos",
  "Municipalidad de Frutillar": "Municipios de Los Lagos",
  "Municipalidad de Futaleufú": "Municipios de Los Lagos",
  "Municipalidad de Futrono": "Municipios de Los Ríos",
  "Municipalidad de Galvarino": "Municipios de La Araucanía",
  "Municipalidad de General Lagos": "Municipios de Arica y  Parinacota",
  "Municipalidad de Gorbea": "Municipios de La Araucanía",
  "Municipalidad de Graneros": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Guaitecas": "Municipios de Aysen del General Carlos Ibáñez del Campo",
  "Municipalidad de Hijuelas": "Municipios de Valparaíso",
  "Municipalidad de Hualaihué": "Municipios de Los Lagos",
  "Municipalidad de Hualpén": "Municipios del Bíobio",
  "Municipalidad de Hualqui": "Municipios del Bíobio",
  "Municipalidad de Huara": "Municipios de Tarapacá",
  "Municipalidad de Huasco": "Municipios de Atacama",
  "Municipalidad de Huechuraba": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Illapel": "Municipios de Coquimbo",
  "Municipalidad de Independencia": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Iquique": "Municipios de Tarapacá",
  "Municipalidad de Isla de Maipo": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Isla de Pascua (Rapa Nui)": "Municipios de Valparaíso",
  "Municipalidad de Juan Fernández": "Municipios de Valparaíso",
  "Municipalidad de La Cisterna": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de La Cruz": "Municipios de Valparaíso",
  "Municipalidad de La Estrella": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de La Florida": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de La Granja": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de La Higuera": "Municipios de Coquimbo",
  "Municipalidad de La Ligua": "Municipios de Valparaíso",
  "Municipalidad de La Pintana": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de La Reina": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de La Serena": "Municipios de Coquimbo",
  "Municipalidad de La Unión": "Municipios de Los Ríos",
  "Municipalidad de Lago Ranco": "Municipios de Los Ríos",
  "Municipalidad de Lago Verde": "Municipios de Aysen del General Carlos Ibáñez del Campo",
  "Municipalidad de Laguna Blanca": "Municipios de Magallanes y de la Antártica Chilena",
  "Municipalidad de Laja": "Municipios del Bíobio",
  "Municipalidad de Lampa": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Lanco": "Municipios de Los Ríos",
  "Municipalidad de Las Cabras": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Lautaro": "Municipios de La Araucanía",
  "Municipalidad de Lebu": "Municipios del Bíobio",
  "Municipalidad de Licantén": "Municipios del Maule",
  "Municipalidad de Limache": "Municipios de Valparaíso",
  "Municipalidad de Litueche": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Llanquihue": "Municipios de Los Lagos",
  "Municipalidad de Llay Llay": "Municipios de Valparaíso",
  "Municipalidad de Lo Barnechea": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Lo Espejo": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Lo Prado": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Lolol": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Loncoche": "Municipios de La Araucanía",
  "Municipalidad de Lonquimay": "Municipios de La Araucanía",
  "Municipalidad de Los Alamos": "Municipios del Bíobio",
  "Municipalidad de Los Andes": "Municipios de Valparaíso",
  "Municipalidad de Los Lagos": "Municipios de Los Ríos",
  "Municipalidad de Los Muermos": "Municipios de Los Lagos",
  "Municipalidad de Los Sauces": "Municipios de La Araucanía",
  "Municipalidad de Los Vilos": "Municipios de Coquimbo",
  "Municipalidad de Los Ángeles": "Municipios del Bíobio",
  "Municipalidad de Lumaco": "Municipios de La Araucanía",
  "Municipalidad de Machalí": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Maipú": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Malloa": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Marchige": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Mariquina": "Municipios de Los Ríos",
  "Municipalidad de María Elena": "Municipios de Antofagasta",
  "Municipalidad de María Pinto": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Maule": "Municipios del Maule",
  "Municipalidad de Maullín": "Municipios de Los Lagos",
  "Municipalidad de Mejillones": "Municipios de Antofagasta",
  "Municipalidad de Melipeuco": "Municipios de La Araucanía",
  "Municipalidad de Molina": "Municipios del Maule",
  "Municipalidad de Monte Patria": "Municipios de Coquimbo",
  "Municipalidad de Mostazal": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Mulchén": "Municipios del Bíobio",
  "Municipalidad de Máfil": "Municipios de Los Ríos",
  "Municipalidad de Nacimiento": "Municipios del Bíobio",
  "Municipalidad de Nancagua": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Navidad": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Ninhue": "Municipios de Ñuble",
  "Municipalidad de Nogales": "Municipios de Valparaíso",
  "Municipalidad de OHiggins": "Municipios de Aysen del General Carlos Ibáñez del Campo",
  "Municipalidad de Ollague": "Municipios de Antofagasta",
  "Municipalidad de Olmué": "Municipios de Valparaíso",
  "Municipalidad de Osorno": "Municipios de Los Lagos",
  "Municipalidad de Ovalle": "Municipios de Coquimbo",
  "Municipalidad de Padre Hurtado": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Padre Las Casas": "Municipios de La Araucanía",
  "Municipalidad de Paihuano": "Municipios de Coquimbo",
  "Municipalidad de Paillaco": "Municipios de Los Ríos",
  "Municipalidad de Paine": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Palena": "Municipios de Los Lagos",
  "Municipalidad de Palmilla": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Panguipulli": "Municipios de Los Ríos",
  "Municipalidad de Panquehue": "Municipios de Valparaíso",
  "Municipalidad de Papudo": "Municipios de Valparaíso",
  "Municipalidad de Paredones": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Parral": "Municipios del Maule",
  "Municipalidad de Pedro Aguirre Cerda": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Pelarco": "Municipios del Maule",
  "Municipalidad de Pelluhue": "Municipios del Maule",
  "Municipalidad de Pemuco": "Municipios de Ñuble",
  "Municipalidad de Pencahue": "Municipios del Maule",
  "Municipalidad de Peralillo": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Perquenco": "Municipios de La Araucanía",
  "Municipalidad de Petorca": "Municipios de Valparaíso",
  "Municipalidad de Peumo": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Peñaflor": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Peñalolén": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Pica": "Municipios de Tarapacá",
  "Municipalidad de Pichidegua": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Pichilemu": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Pinto": "Municipios de Ñuble",
  "Municipalidad de Pirque": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Pitrufquén": "Municipios de La Araucanía",
  "Municipalidad de Placilla": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Portezuelo": "Municipios de Ñuble",
  "Municipalidad de Porvenir": "Municipios de Magallanes y de la Antártica Chilena",
  "Municipalidad de Pozo Almonte": "Municipios de Tarapacá",
  "Municipalidad de Primavera": "Municipios de Magallanes y de la Antártica Chilena",
  "Municipalidad de Providencia": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Puchuncaví": "Municipios de Valparaíso",
  "Municipalidad de Pucón": "Municipios de La Araucanía",
  "Municipalidad de Pudahuel": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Puente Alto": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Puerto Montt": "Municipios de Los Lagos",
  "Municipalidad de Puerto Natales": "Municipios de Magallanes y de la Antártica Chilena",
  "Municipalidad de Puerto Octay": "Municipios de Los Lagos",
  "Municipalidad de Puerto Varas": "Municipios de Los Lagos",
  "Municipalidad de Pumanque": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Punitaqui": "Municipios de Coquimbo",
  "Municipalidad de Punta Arenas": "Municipios de Magallanes y de la Antártica Chilena",
  "Municipalidad de Puqueldón": "Municipios de Los Lagos",
  "Municipalidad de Purranque": "Municipios de Los Lagos",
  "Municipalidad de Putaendo": "Municipios de Valparaíso",
  "Municipalidad de Putre": "Municipios de Arica y  Parinacota",
  "Municipalidad de Puyehue": "Municipios de Los Lagos",
  "Municipalidad de Queilén": "Municipios de Los Lagos",
  "Municipalidad de Quellón": "Municipios de Los Lagos",
  "Municipalidad de Quemchi": "Municipios de Los Lagos",
  "Municipalidad de Quilaco": "Municipios del Bíobio",
  "Municipalidad de Quilicura": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Quilleco": "Municipios del Bíobio",
  "Municipalidad de Quillota": "Municipios de Valparaíso",
  "Municipalidad de Quilpué": "Municipios de Valparaíso",
  "Municipalidad de Quinchao": "Municipios de Los Lagos",
  "Municipalidad de Quinta Normal": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Quintero": "Municipios de Valparaíso",
  "Municipalidad de Quirihue": "Municipios de Ñuble",
  "Municipalidad de Rancagua": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Rauco": "Municipios del Maule",
  "Municipalidad de Renaico": "Municipios de La Araucanía",
  "Municipalidad de Renca": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Rengo": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Requínoa": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Retiro": "Municipios del Maule",
  "Municipalidad de Rinconada": "Municipios de Valparaíso",
  "Municipalidad de Rio Bueno": "Municipios de Los Ríos",
  "Municipalidad de Romeral": "Municipios del Maule",
  "Municipalidad de Ránquil": "Municipios de Ñuble",
  "Municipalidad de Río Claro": "Municipios del Maule",
  "Municipalidad de Río Hurtado": "Municipios de Coquimbo",
  "Municipalidad de Río Ibáñez": "Municipios de Aysen del General Carlos Ibáñez del Campo",
  "Municipalidad de Río Negro": "Municipios de Los Lagos",
  "Municipalidad de Río Verde": "Municipios de Magallanes y de la Antártica Chilena",
  "Municipalidad de Saavedra": "Municipios de La Araucanía",
  "Municipalidad de Sagrada Familia": "Municipios del Maule",
  "Municipalidad de Salamanca": "Municipios de Coquimbo",
  "Municipalidad de San Antonio": "Municipios de Valparaíso",
  "Municipalidad de San Bernardo": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de San Carlos": "Municipios de Ñuble",
  "Municipalidad de San Clemente": "Municipios del Maule",
  "Municipalidad de San Esteban": "Municipios de Valparaíso",
  "Municipalidad de San Fabián": "Municipios de Ñuble",
  "Municipalidad de San Felipe": "Municipios de Valparaíso",
  "Municipalidad de San Fernando": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de San Gregorio": "Municipios de Magallanes y de la Antártica Chilena",
  "Municipalidad de San Ignacio": "Municipios de Ñuble",
  "Municipalidad de San Javier": "Municipios del Maule",
  "Municipalidad de San Joaquín": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de San José de Maipo": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de San Juan de la Costa": "Municipios de Los Lagos",
  "Municipalidad de San Miguel": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de San Nicolás": "Municipios de Ñuble",
  "Municipalidad de San Pablo": "Municipios de Los Lagos",
  "Municipalidad de San Pedro": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de San Pedro De La Paz": "Municipios del Bíobio",
  "Municipalidad de San Ramón": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de San Rosendo": "Municipios del Bíobio",
  "Municipalidad de San Vicente de Tagua Tagua": "Municipios del Libertador General Bernardo OHiggins",
  "Municipalidad de Santa Bárbara": "Municipios del Bíobio",
  "Municipalidad de Santa Juana": "Municipios del Bíobio",
  "Municipalidad de Santa María": "Municipios de Valparaíso",
  "Municipalidad de Santiago": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Santo Domingo": "Municipios de Valparaíso",
  "Municipalidad de Sierra Gorda": "Municipios de Antofagasta",
  "Municipalidad de Talagante": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Talca": "Municipios del Maule",
  "Municipalidad de Talcahuano": "Municipios del Bíobio",
  "Municipalidad de Taltal": "Municipios de Antofagasta",
  "Municipalidad de Teno": "Municipios del Maule",
  "Municipalidad de Teodoro Schmidt": "Municipios de La Araucanía",
  "Municipalidad de Tierra Amarilla": "Municipios de Atacama",
  "Municipalidad de Tiltil": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Timaukel": "Municipios de Magallanes y de la Antártica Chilena",
  "Municipalidad de Tirúa": "Municipios del Bíobio",
  "Municipalidad de Tocopilla": "Municipios de Antofagasta",
  "Municipalidad de Toltén": "Municipios de La Araucanía",
  "Municipalidad de Tome": "Municipios del Bíobio",
  "Municipalidad de Torres del Paine": "Municipios de Magallanes y de la Antártica Chilena",
  "Municipalidad de Tortel": "Municipios de Aysen del General Carlos Ibáñez del Campo",
  "Municipalidad de Traiguén": "Municipios de La Araucanía",
  "Municipalidad de Trehuaco": "Municipios de Ñuble",
  "Municipalidad de Tucapel": "Municipios del Bíobio",
  "Municipalidad de Valdivia": "Municipios de Los Ríos",
  "Municipalidad de Vallenar": "Municipios de Atacama",
  "Municipalidad de Valparaíso": "Municipios de Valparaíso",
  "Municipalidad de Vichuquén": "Municipios del Maule",
  "Municipalidad de Vicuña": "Municipios de Coquimbo",
  "Municipalidad de Vilcún": "Municipios de La Araucanía",
  "Municipalidad de Villa Alegre": "Municipios del Maule",
  "Municipalidad de Villa Alemana": "Municipios de Valparaíso",
  "Municipalidad de Villarrica": "Municipios de La Araucanía",
  "Municipalidad de Vitacura": "Municipios de R. Metropolitana de Santiago",
  "Municipalidad de Viña del Mar": "Municipios de Valparaíso",
  "Municipalidad de Yerbas Buenas": "Municipios del Maule",
  "Municipalidad de Yumbel": "Municipios del Bíobio",
  "Municipalidad de Yungay": "Municipios de Ñuble",
  "Municipalidad de Zapallar": "Municipios de Valparaíso",
  "Municipalidad de Ñiquén": "Municipios de Ñuble",
  "Municipalidad de Ñuñoa": "Municipios de R. Metropolitana de Santiago",
  "Oficinas de Estudios y Políticas Agrarias (ODEPA)": "Agricultura",
  "Parque Metropolitano de Santiago": "Vivienda y Urbanismo",
  "Policía de Investigaciones (PDI)": "Interior",
  "Presidencia de la República": "Presidencia de la República",
  "SEREMI de Salud  Metropolitano de Santiago": "Salud",
  "SEREMI de Salud  de Antofagasta": "Salud",
  "SEREMI de Salud  de Arica y Parinacota": "Salud",
  "SEREMI de Salud  de Atacama": "Salud",
  "SEREMI de Salud  de Coquimbo": "Salud",
  "SEREMI de Salud  de Tarapacá": "Salud",
  "SEREMI de Salud  de Valparaíso": "Salud",
  "SEREMI de Salud de Aysén": "Salud",
  "SEREMI de Salud de La Araucanía": "Salud",
  "SEREMI de Salud de Los Ríos": "Salud",
  "SEREMI de Salud de Magallanes y Antártica Chilena": "Salud",
  "SEREMI de Salud de OHiggins": "Salud",
  "SEREMI de Salud del Bío Bío": "Salud",
  "SEREMI de Salud del Maule": "Salud",
  "SEREMI de Salud del Ñuble": "Salud",
  "SEREMI de Salud región de Los Lagos": "Salud",
  "SEREMI de Vivienda y Urbanismo Región Metropolitana": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Antofagasta": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Arica y Parinacota": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Atacama": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Aysén": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Bíobio": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Coquimbo": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de La Araucanía": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Los Lagos": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Los Ríos": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Magallanes y Antártica Chilena": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Maule": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Tarapacá": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Valparaíso": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región de Ñuble": "Vivienda y Urbanismo",
  "SEREMI de Vivienda y Urbanismo Región del Libertador Bernardo OHiggins": "Vivienda y Urbanismo",
  "SERVICIO DE SALUD ARAUCANIA NORTE": "Salud",
  "SERVIU Metropolitano": "Vivienda y Urbanismo",
  "SERVIU Región de Antofagasta": "Vivienda y Urbanismo",
  "SERVIU Región de Arica y Parinacota": "Vivienda y Urbanismo",
  "SERVIU Región de Atacama": "Vivienda y Urbanismo",
  "SERVIU Región de Aysén del General Carlos Ibáñez del Campo": "Vivienda y Urbanismo",
  "SERVIU Región de Coquimbo": "Vivienda y Urbanismo",
  "SERVIU Región de Los Lagos": "Vivienda y Urbanismo",
  "SERVIU Región de Los Ríos": "Vivienda y Urbanismo",
  "SERVIU Región de Magallanes y la Antártica Chilena": "Vivienda y Urbanismo",
  "SERVIU Región de Tarapacá": "Vivienda y Urbanismo",
  "SERVIU Región de Valparaíso": "Vivienda y Urbanismo",
  "SERVIU Región de la Araucanía": "Vivienda y Urbanismo",
  "SERVIU Región del Bío Bío": "Vivienda y Urbanismo",
  "SERVIU Región del Libertador Bernardo OHiggins": "Vivienda y Urbanismo",
  "SERVIU Región del Maule": "Vivienda y Urbanismo",
  "SERVIU Región del Ñuble": "Vivienda y Urbanismo",
  "Servicio Agrícola y Ganadero (SAG)": "Agricultura",
  "Servicio Electoral (SERVEL)": "Servicio Electoral",
  "Servicio Local de Educación Pública  Maule Costa": "Educación",
  "Servicio Local de Educación Pública Aconcagua (SLEP Aconcagua)": "Educación",
  "Servicio Local de Educación Pública Andalién Sur (SLEP Andalién Sur)": "Educación",
  "Servicio Local de Educación Pública Atacama (SLEP Atacama)": "Educación",
  "Servicio Local de Educación Pública Chiloé (SLEP Chiloé)": "Educación",
  "Servicio Local de Educación Pública Chinchorro (SLEP Chinchorro)": "Educación",
  "Servicio Local de Educación Pública Colchagua (SLEP Colchagua)": "Educación",
  "Servicio Local de Educación Pública Costa Araucanía (SLEP Costa Araucanía)": "Educación",
  "Servicio Local de Educación Pública Costa Central (SLEP Costa Central)": "Educación",
  "Servicio Local de Educación Pública Elqui (SLEP Elqui)": "Educación",
  "Servicio Local de Educación Pública Gabriela Mistral (SLEP Gabriela Mistral)": "Educación",
  "Servicio Local de Educación Pública Huasco (SLEP Huasco)": "Educación",
  "Servicio Local de Educación Pública Licancabur": "Educación",
  "Servicio Local de Educación Pública Llanquihue (SLEP Llanquihue)": "Educación",
  "Servicio Local de Educación Pública Los Álamos (SLEP Los Álamos)": "Educación",
  "Servicio Local de Educación Pública Marga Marga (SLEP Marga Marga)": "Educación",
  "Servicio Local de Educación Pública Petorca (SLEP Petorca)": "Educación",
  "Servicio Local de Educación Pública Puerto Cordillera": "Educación",
  "Servicio Local de Educación Pública Santa Rosa": "Educación",
  "Servicio Local de Educación Pública Santiago Centro (SLEP Santiago Centro)": "Educación",
  "Servicio Local de Educación Pública Valdivia (SLEP Valdivia)": "Educación",
  "Servicio Local de Educación Pública Valparaíso (SLEP Valparaíso)": "Educación",
  "Servicio Local de Educación Pública de Andalién Costa (SLEP Andalién Costa)": "Educación",
  "Servicio Local de Educación Pública de Antofagasta (SLEP Antofagasta)": "Educación",
  "Servicio Local de Educación Pública de Aysén (SLEP Aysén)": "Educación",
  "Servicio Local de Educación Pública de Barrancas (SLEP Barrancas)": "Educación",
  "Servicio Local de Educación Pública de Iquique (SLEP Iquique)": "Educación",
  "Servicio Local de Educación Pública de Los Parques": "Educación",
  "Servicio Local de Educación Pública de Magallanes (SLEP Magallanes)": "Educación",
  "Servicio Local de Educación Pública del Pino": "Educación",
  "Servicio Local de Educación Pública del Tamarugal": "Educación",
  "Servicio Local de Educación Pública los Libertadores": "Educación",
  "Servicio Local de educación Pública Punilla Cordillera": "Educación",
  "Servicio Localde Educación Pública Santa Corina": "Educación",
  "Servicio Médico Legal (SML)": "Justicia",
  "Servicio Nacional de Aduanas": "Hacienda",
  "Servicio Nacional de Capacitación y Empleo (SENCE)": "Trabajo y Previsión Social",
  "Servicio Nacional de Geología y Minería (SERNAGEOMIN)": "Minería",
  "Servicio Nacional de Menores (SENAME)": "Justicia",
  "Servicio Nacional de Migraciones": "Interior",
  "Servicio Nacional de Pesca y Acuicultura (SERNAPESCA)": "Economía Fomento y Turismo",
  "Servicio Nacional de Prevención y Respuesta ante Desastres (SENAPRED) ex ONEMI": "Interior",
  "Servicio Nacional de Protección Especializada a la Niñez y Adolescencia": "Desarrollo Social",
  "Servicio Nacional de Reinserción Social Juvenil": "Justicia",
  "Servicio Nacional de Turismo (SERNATUR)": "Economía Fomento y Turismo",
  "Servicio Nacional de la Discapacidad (SENADIS)": "Desarrollo Social",
  "Servicio Nacional de la Mujer y la Equidad de Género (SERNAMEG)": "La Mujer y Equidad de Género",
  "Servicio Nacional del Adulto Mayor (SENAMA)": "Desarrollo Social",
  "Servicio Nacional del Consumidor (SERNAC)": "Economía Fomento y Turismo",
  "Servicio Nacional del Patrimonio Cultural": "Culturas y las Artes",
  "Servicio Nacional para la Prevención y Rehabilitación del Consumo de Drogas y Alcohol (SENDA)": "Interior",
  "Servicio de Biodiversidad y Áreas Protegidas": "Medio Ambiente",
  "Servicio de Cooperación Técnica (SERCOTEC)": "Economía Fomento y Turismo",
  "Servicio de Evaluación Ambiental (SEA)": "Medio Ambiente",
  "Servicio de Gobierno Interior": "Interior",
  "Servicio de Registro Civil e Identificación": "Justicia",
  "Servicio de Salud Aconcagua": "Salud",
  "Servicio de Salud Antofagasta": "Salud",
  "Servicio de Salud Araucanía Sur": "Salud",
  "Servicio de Salud Arauco": "Salud",
  "Servicio de Salud Arica y Parinacota": "Salud",
  "Servicio de Salud Atacama": "Salud",
  "Servicio de Salud Aysén": "Salud",
  "Servicio de Salud Bíobío": "Salud",
  "Servicio de Salud Concepción": "Salud",
  "Servicio de Salud Coquimbo": "Salud",
  "Servicio de Salud Magallanes": "Salud",
  "Servicio de Salud Maule": "Salud",
  "Servicio de Salud Metropolitano Central": "Salud",
  "Servicio de Salud Metropolitano Norte": "Salud",
  "Servicio de Salud Metropolitano Occidente": "Salud",
  "Servicio de Salud Metropolitano Oriente": "Salud",
  "Servicio de Salud Metropolitano Sur": "Salud",
  "Servicio de Salud Metropolitano Sur Oriente": "Salud",
  "Servicio de Salud OHiggins": "Salud",
  "Servicio de Salud Osorno": "Salud",
  "Servicio de Salud Talcahuano": "Salud",
  "Servicio de Salud Tarapacá": "Salud",
  "Servicio de Salud Valdivia": "Salud",
  "Servicio de Salud Valparaíso  San Antonio": "Salud",
  "Servicio de Salud Viña del Mar  Quillota": "Salud",
  "Servicio de Salud de Chiloé": "Salud",
  "Servicio de Salud del Reloncaví": "Salud",
  "Servicio de Salud Ñuble": "Salud",
  "Sistema de Empresas  SEP": "Empresas y Sociedades",
  "Subsecretaría General de Gobierno (SEGEGOB)": "Secretaría General de Gobierno",
  "Subsecretaría General de La Presidencia (SEGPRES)": "Secretaría General de la Presidencia",
  "Subsecretaría de Agricultura": "Agricultura",
  "Subsecretaría de Bienes Nacionales": "Bienes Nacionales",
  "Subsecretaría de Ciencia Tecnología Conocimiento e Innovación": "Ciencia Tecnología e Innovación",
  "Subsecretaría de Defensa": "Defensa Nacional",
  "Subsecretaría de Derechos Humanos": "Justicia",
  "Subsecretaría de Desarrollo Regional y Administrativo (SUBDERE)": "Interior",
  "Subsecretaría de Economía (MINECON)": "Economía Fomento y Turismo",
  "Subsecretaría de Educación (MINEDUC)": "Educación",
  "Subsecretaría de Educación Parvularia": "Educación",
  "Subsecretaría de Educación Superior": "Educación",
  "Subsecretaría de Energía": "Energía",
  "Subsecretaría de Evaluación Social": "Desarrollo Social",
  "Subsecretaría de Hacienda": "Hacienda",
  "Subsecretaría de Justicia": "Justicia",
  "Subsecretaría de Minería": "Minería",
  "Subsecretaría de Obras Públicas (MOP)": "Obras Públicas",
  "Subsecretaría de Pesca y Acuicultura": "Economía Fomento y Turismo",
  "Subsecretaría de Prevención del Delito": "Interior",
  "Subsecretaría de Previsión Social (SPS)": "Trabajo y Previsión Social",
  "Subsecretaría de Redes Asistenciales": "Salud",
  "Subsecretaría de Relaciones Económicas Internacionales": "Relaciones Exteriores",
  "Subsecretaría de Relaciones Exteriores": "Relaciones Exteriores",
  "Subsecretaría de Salud Pública (MINSAL)": "Salud",
  "Subsecretaría de Seguridad Pública": "Seguridad Pública",
  "Subsecretaría de Servicios Sociales": "Desarrollo Social",
  "Subsecretaría de Telecomunicaciones (SUBTEL)": "Transportes y Telecomunicaciones",
  "Subsecretaría de Transportes (MTT)": "Transportes y Telecomunicaciones",
  "Subsecretaría de Turismo": "Economía Fomento y Turismo",
  "Subsecretaría de Vivienda y Urbanismo (MINVU)": "Vivienda y Urbanismo",
  "Subsecretaría de la Mujer y la Equidad de Género": "La Mujer y Equidad de Género",
  "Subsecretaría de la Niñez": "Desarrollo Social",
  "Subsecretaría de las Culturas y las Artes": "Culturas y las Artes",
  "Subsecretaría del Deporte": "Deporte",
  "Subsecretaría del Interior": "Interior",
  "Subsecretaría del Medio Ambiente (MMA)": "Medio Ambiente",
  "Subsecretaría del Patrimonio Cultural": "Culturas y las Artes",
  "Subsecretaría del Trabajo (MINTRAB)": "Trabajo y Previsión Social",
  "Subsecretaría para las Fuerzas Armadas (SSFFAA)": "Defensa Nacional",
  "Superintendencia de Casinos de Juego (SCJ)": "Hacienda",
  "Superintendencia de Educación Dirección Nacional": "Educación",
  "Superintendencia de Educación Superior": "Educación",
  "Superintendencia de Electricidad y Combustibles (SEC)": "Energía",
  "Superintendencia de Insolvencia y Reemprendimiento (SUPERIR)": "Economía Fomento y Turismo",
  "Superintendencia de Pensiones (SP)": "Trabajo y Previsión Social",
  "Superintendencia de Salud (SdS)": "Salud",
  "Superintendencia de Seguridad Social (SUSESO)": "Trabajo y Previsión Social",
  "Superintendencia de Servicios Sanitarios (SISS)": "Obras Públicas",
  "Superintendencia del Medio Ambiente (SMA)": "Medio Ambiente",
  "Tesorería General de la República (TGR)": "Hacienda",
  "Unidad de Análisis Financiero": "Hacienda",
  "Universidad de Atacama": "Universidades",
  "Universidad de Aysén": "Universidades",
  "Universidad de Los Lagos": "Universidades",
  "Universidad de Magallanes": "Universidades",
  "Universidad de OHiggins": "Universidades",
  "Universidad de Santiago de Chile (USACH)": "Universidades"
};