const organismoMunicipal = {
 "Administrador del Fondo Autónomo de Protección Previsional (FAPP)": 0,
 "Administradora de los Tribunales Tributarios y Aduaneros y del Tribunal de Contratación Pública": 0,
 "Agencia Chilena de Cooperación Internacional para el Desarrollo (AGCID)": 0,
 "Agencia Chilena de Eficiencia Energética": 0,
 "Agencia de Calidad de la Educación": 0,
 "Agencia de Promoción de la Inversión Extranjera": 0,
 "Agencia Nacional de Investigación y Desarrollo (ANID)": 0,
 "Agencia Nacional de Investigación y Desarrollo ANID": 0,
 "Agencia Regional de Desarrollo Productivo de la Araucanía": 0,
 "Armada de Chile": 0,
 "Asociación Chilena de Municipalidades con Farmacias Populares (ACHIFARP)": 0,
 "Asociación Chilena de Municipalidades": 0,
 "Asociación Cultural Municipal de Cerrillos": 0,
 "Asociación de Gobernadores y Gobernadoras Regionales de Chile  AGORECHI": 0,
 "Asociación de Municipalidades Bio Bio Centro": 0,
 "Asociación de Municipalidades Comunas Costeras de PuchuncavíQuintero": 0,
 "Asociación de Municipalidades con Alcalde Mapuche": 0,
 "Asociación de Municipalidades con Centros de Montaña": 0,
 "Asociación de Municipalidades Cordilleranas de la Araucanía": 0,
 "Asociación de Municipalidades de Arauco y Curanilahue": 0,
 "Asociación de Municipalidades de Chile AMUCH": 0,
 "Asociación de Municipalidades de Ciudades Puerto y Borde Costero": 0,
 "Asociación de Municipalidades de la cuenca del Lago Llanquihue": 0,
 "Asociación de Municipalidades de la Provincia de Arauco": 0,
 "Asociación de Municipalidades de la Provincia de Osorno": 0,
 "Asociación de Municipalidades de la Provincia de San Antonio (AMPSA)": 0,
 "Asociación de Municipalidades de la Provincia del Huasco": 0,
 "Asociación de Municipalidades de la Región de  Coquimbo": 0,
 "Asociación de Municipalidades de la Región de Aconcagua": 0,
 "Asociación de Municipalidades de la Región de Antofagasta": 0,
 "Asociación de Municipalidades de la región de la araucanía o amra araucanía": 0,
 "Asociación de Municipalidades de la Región de Los Ríos para el Manejo sustentable de Residuos y la Gestión Ambiental": 0,
 "Asociación de Municipalidades de La Región de Los Ríos": 0,
 "Asociación de Municipalidades de la Región de OHiggins": 0,
 "Asociación de Municipalidades de la Región de Valparaíso": 0,
 "Asociación de Municipalidades de la Región del Biobío": 0,
 "Asociación de Municipalidades de la Zona Central y Costa (AMUCC)": 0,
 "Asociación de Municipalidades de la Zona Metropolitana de la Araucanía (AMZOMA)": 0,
 "Asociación de Municipalidades del Norte de Chile": 0,
 "Asociación de Municipalidades del Punilla": 0,
 "Asociación de Municipalidades del Valle del Itata": 0,
 "Asociación de Municipalidades del Valle del Maipo": 0,
 "Asociación de Municipalidades Desarrollo Apicultura Turismo y Medio Ambiente Zona de Amortiguación de la Región de Los Lagos": 0,
 "Asociación de Municipalidades Libres (AML)": 0,
 "Asociación de Municipalidades Malleco Norte AMMN": 0,
 "Asociación de Municipalidades Nahuelbuta (AMN)": 0,
 "Asociación de Municipalidades para el Desarrollo Económico Local": 0,
 "Asociación de Municipalidades para la Preservación de la Biodiversidad en el Territorio de Nonguén y otros Ecosistemas": 0,
 "Asociación de Municipalidades para la Seguridad Ciudadana Concón  Limache": 0,
 "Asociación de Municipalidades para la Seguridad Ciudadana en la Zona Oriente": 0,
 "Asociación de Municipalidades Parque Cordillera": 0,
 "Asociación de Municipalidades Red Nacional de Comunas Mágicas de Chile": 0,
 "Asociación de Municipalidades Región de Aysén": 0,
 "Asociación de Municipalidades Rurales (AMUR)": 0,
 "Asociación de Municipalidades Rurales del Norte Chico": 0,
 "Asociación de Municipalidades Territorio de Riego Canal LajaDiguillín": 0,
 "Asociación de Municipalidades Turísticas de Chile (AMTC)": 0,
 "Asociación de Municipios Ciudad Sur": 0,
 "Asociación de Municipios Cordillera de la Costa CorralLa Unión": 0,
 "Asociación de Municipios Cordilleranos AMCORDI": 0,
 "Asociación de Municipios Costa Araucanía": 0,
 "Asociación de Municipios de Desarrollo Intercomunal de Chiloé (AMUDICH)": 0,
 "Asociación de Municipios Metropolitanos para la Seguridad Ciudadana (AMMSeguridad)": 0,
 "Asociación de Municipios para el Desarrollo Turístico de las Comunas de Cabrero Los Ángeles y Yumbel": 0,
 "Asociación de Municipios para la Conservación de la Biodiversidad de la Región de Los Ríos": 0,
 "Asociación de Municipios para la seguridad comunitaria (AMSC)": 0,
 "Asociación de Municipios Rurales Regiones de Tarapacá y AricaParinacota": 0,
 "Asociación de municipios verdes araucanía sur  amvas": 0,
 "Asociación Metropolitana de Municipalidades de Santiago Sur para la Gestión Ambiental y de Residuos (Msur)": 0,
 "Asociación Municipal para la sustentabilidad ambiental AMUSA": 0,
 "Asociación Municipalidades Provincia de Llanquihue Para Manejo Sustentable de Residuos y Gestión Ambiental": 0,
 "Asociación Nacional de Municipalidades de Ciudades Puerto Concesionados": 0,
 "Asociación Regional de Municipalidades de Magallanes y Antártica Chilena (AMUMAG)": 0,
 "Asociación Regional de Municipios de Atacama": 0,
 "Asociación Special Olympics World Games Santiago Two Thousand TwentySeven Local Organizing Committee": 0,
 "Caja de Previsión de la Defensa Nacional (CAPREDENA)": 0,
 "Carabineros de Chile": 0,
 "Central de Abastecimiento del Sistema Nacional de Servicios de Salud (CENABAST)": 0,
 "Centro de Formación Técnica de la Región del Maule": 0,
 "Centro de Formación Técnica Estatal Región de Coquimbo": 0,
 "Centro de Información de Recursos Naturales (CIREN)": 0,
 "Centro de Referencia de Salud de Maipú (CRSM)": 0,
 "Centro de Referencia de Salud de Peñalolén Cordillera Oriente (CRSORIENTE)": 0,
 "Centro de Referencia de Salud Hospital Provincia Cordillera (hpcordillera)": 0,
 "CFT de la Región de Antofagasta": 0,
 "CFT de la Región de Arica y Parinacota": 0,
 "CFT de la Región de Atacama": 0,
 "CFT de la Región de la Araucanía": 0,
 "CFT de la Región de los Lagos": 0,
 "CFT de la Región de Los Ríos": 0,
 "CFT de la Región de OHiggins": 0,
 "CFT de la Región de Valparaíso": 0,
 "CFT de la Región del Tarapacá": 0,
 "CFT de la Región Metropolitana (CFTRM)": 0,
 "CFT Estatal de la Región de Aysén": 0,
 "CFT Estatal de la Región del Biobío": 0,
 "CFT Estatal de la Región del Maule": 0,
 "CFT Magallanes": 0,
 "CLUB DE LA REINA SOCIAL DEPORTIVO Y RECREACIONAL": 1,
 "Comercializadora de Trigo COTRISA": 0,
 "Comisión Administradora del Sistema de Créditos para Estudios Superiores (INGRESA)": 0,
 "Comisión Chilena de Energía Nuclear (CCHEN)": 0,
 "Comisión Chilena del Cobre (COCHILCO)": 0,
 "Comisión del Sistema Nacional de Certificación de Competencias Laborales": 0,
 "Comisión Nacional de Acreditación (CNA)": 0,
 "Comisión Nacional de Energía (CNE)": 0,
 "Comisión Nacional de Riego (CNR)": 0,
 "Comisión para el Mercado Financiero  CMF ex SVS": 0,
 "Consejo de Defensa del Estado (CDE)": 0,
 "Consejo de Rectores de las Universidades Chilenas (CRUCH)": 0,
 "Consejo de Rectores": 0,
 "Consejo Fiscal Autónomo": 0,
 "Consejo Nacional de Educación (CNED)": 0,
 "Consejo Nacional de Televisión (CNTV)": 0,
 "Consejo para la Transparencia (CPLT)": 0,
 "Corporación Cultural Aldea del Encuentro La Reina": 1,
 "Corporación cultural de Ancud": 1,
 "Corporación Cultural de Antofagasta": 1,
 "Corporación Cultural de Estación Central": 1,
 "Corporación Cultural de la Comuna de La Granja": 1,
 "Corporación Cultural de La Ilustre Municipalidad de Romeral": 1,
 "Corporación Cultural de La Ilustre Municipalidad de Valdivia": 1,
 "Corporación Cultural de la Municipalidad de Curicó": 1,
 "Corporación Cultural de La Reina": 1,
 "Corporación Cultural de Lampa": 1,
 "Corporación Cultural de Las Condes": 1,
 "Corporación Cultural de Lo Barnechea": 1,
 "Corporación Cultural de Mostazal": 1,
 "Corporación Cultural de Nacimiento": 1,
 "Corporación Cultural de Osorno": 1,
 "Corporación Cultural de Peñalolén": 1,
 "Corporación Cultural de Recoleta": 1,
 "Corporación Cultural de San Pedro de La Paz": 1,
 "Corporación Cultural de Teno": 1,
 "Corporación Cultural de Vitacura": 1,
 "Corporación Cultural de Ñuñoa": 1,
 "Corporación Cultural Ilustre Municipalidad de Rauco": 1,
 "Corporación Cultural Isla de Maipo": 1,
 "Corporación Cultural Municipal de La Comuna de Chillán": 1,
 "Corporación Cultural Municipal de La Comuna de Villarrica": 1,
 "Corporación Cultural Municipal de Los Ángeles": 1,
 "Corporación Cultural Municipal de Ovalle": 1,
 "Corporación Cultural Municipal de Padre Las Casas": 1,
 "Corporación Cultural Municipal de Puente Alto": 1,
 "Corporación Cultural Municipal de San Javier de Loncomilla": 1,
 "Corporación Cultural Municipal de Vicuña": 1,
 "Corporación Cultural Municipalidad de Coyhaique": 1,
 "Corporación Cultural Municipalidad de Maule": 1,
 "Corporación Cultural San Francisco de El Monte": 0,
 "Corporación Cultural Social y Deportiva Municipal de Quilicura": 1,
 "Corporación Cultural y de Extensión de La Ilustre Municipalidad de Constitución": 1,
 "Corporación Cultural y de Turismo Municipal Pelarco": 1,
 "Corporación de Artes y Cultura de Colina": 1,
 "Corporación de Asistencia Judicial de la Región Metropolitana (CAJMETRO)": 0,
 "Corporación de Asistencia Judicial Regiones Tarapacá y Antofagasta (CAJTA)": 0,
 "Corporación de Asistencia Judicial Región Bío Bío (CAJBIOBIO)": 0,
 "Corporación de Asistencia Judicial Región Valparaíso (CAJVAL)": 0,
 "Corporación de Cultura de Pichidegua": 1,
 "Corporación de Cultura La Florida": 1,
 "Corporación de Cultura y Patrimonio de Independencia": 1,
 "Corporación de Cultura y Turismo de Calama": 1,
 "Corporación de Deporte de Estación Central Cormudep": 1,
 "Corporación de Deporte de Los Andes": 1,
 "Corporación de Deporte y Recreacion de La Municipalidad de Aysén": 1,
 "Corporación de Deporte y Recreación de Zapallar": 0,
 "Corporación de Deportes Constitución": 1,
 "Corporación de Deportes de la Ilustre Municipalidad de Curicó": 1,
 "Corporación de Deportes de La Ilustre Municipalidad de Teno": 1,
 "Corporación de Deportes de la Municipalidad de Independencia": 1,
 "Corporación de Deportes de Parral": 1,
 "Corporación de Deportes de Peñaflor": 0,
 "Corporación de Deportes de San Clemente": 1,
 "Corporación de Deportes La Florida": 1,
 "Corporación de Deportes y Recreación de Peñalolén": 1,
 "Corporación de Deportes y Recreación de San Javier Loncomilla": 1,
 "Corporación de Deportes y Recreación La Reina": 1,
 "Corporación de Deportes y Recreación Rapa Nui": 0,
 "Corporación de Desarrollo de Magallanes y de la Antártica chilena.": 0,
 "Corporación de Desarrollo de Talca": 1,
 "Corporación de Desarrollo e Innovación de Rancagua": 1,
 "Corporación de Desarrollo Social de Buin": 1,
 "Corporación de Desarrollo Social de Cerro Navia (CORMUCENA)": 1,
 "Corporación de Desarrollo Social de la Municipalidad de Independencia": 1,
 "Corporación de desarrollo territorial de la región de Arica y Parinacota": 0,
 "Corporación de Educación Salud y Atención de Menores Chonchi Chiloé": 1,
 "Corporación de Educación Salud y Menores de Puerto Natales": 1,
 "Corporación de Educación y Salud de Las Condes": 1,
 "Corporación de Fomento de Desarrollo comunal y Productivo de la Granja": 1,
 "Corporación de Fomento de la Producción (CORFO)": 0,
 "Corporación de Inclusión Social de Cerro Navia": 1,
 "Corporación de Innovación y Desarrollo Económico y Social Innova Recoleta": 1,
 "Corporación de investigación y avance de la Paleontología e historia natural de Atacama": 0,
 "Corporación de la Cultura y las Artes de la Ilustre Municipalidad de Rancagua": 1,
 "Corporación del Deporte de Lampa": 1,
 "Corporación del Deporte de Pichidegua": 1,
 "Corporación Deportiva Municipal de San Pedro de La Paz": 1,
 "Corporación Municipal Costa Chinchorro de Arica": 1,
 "Corporación Municipal Cultural Museo de Bellas Artes Valparaíso": 1,
 "Corporación Municipal Cultural y Patrimonial de San Bernardo": 1,
 "Corporación Municipal de Administración Sitio Patrimonio Mundial Área Histórica de la Cuidad Puerto de Valparaíso": 1,
 "Corporación Municipal de Ancud": 1,
 "Corporación Municipal de Calera De Tango": 1,
 "Corporación Municipal de Castro": 1,
 "Corporación Municipal de Colina": 1,
 "Corporación Municipal de cultura de Isla de Pascua": 1,
 "Corporación Municipal de Cultura de Paine": 1,
 "Corporación Municipal de Cultura de San Joaquín": 1,
 "Corporación Municipal de Cultura de Talca": 1,
 "Corporación Municipal de Cultura de TilTil": 1,
 "Corporación Municipal de Cultura La Pintana": 1,
 "Corporación Municipal de Cultura San Clemente": 1,
 "Corporación Municipal de Cultura Turismo y Patrimonio de La Comuna de Natales": 1,
 "Corporación Municipal de Cultura y Artes de Molina": 1,
 "Corporación Municipal de Cultura y Deportes de Recoleta": 0,
 "Corporación Municipal de Cultura y Turismo de La Comuna de Quintero": 1,
 "Corporación Municipal de Curaco De Velez": 1,
 "Corporación Municipal de Deporte de Padre Hurtado": 1,
 "Corporación Municipal de Deporte de Romeral": 1,
 "Corporación Municipal de Deporte Quinta Normal": 1,
 "Corporación Municipal de Deporte y Recreación de Recoleta": 1,
 "Corporación Municipal de Deportes de Caldera": 1,
 "Corporación Municipal de Deportes de Colina": 1,
 "Corporación Municipal de Deportes de Iquique (CORMUDEPI)": 1,
 "Corporación Municipal de Deportes de Lo Prado": 1,
 "Corporación Municipal de Deportes de Natales": 1,
 "Corporación Municipal de Deportes de Padre Las Casas": 1,
 "Corporación Municipal de Deportes de Puente Alto": 1,
 "Corporación Municipal de Deportes de Rancagua": 1,
 "Corporación Municipal de Deportes de San Joaquín": 1,
 "Corporación Municipal de Deportes de Talca": 1,
 "Corporación Municipal de Deportes de Ñuñoa": 1,
 "Corporación Municipal de Deportes La Pintana": 1,
 "Corporación Municipal de Deportes Recreación y Cultura de Coquimbo": 1,
 "Corporación Municipal de Deportes y Desarrollo Social de Quintero": 1,
 "Corporación Municipal de Deportes y Recreación de Antofagasta": 1,
 "Corporación Municipal de Deportes y Recreación de Coyhaique": 1,
 "Corporación Municipal de Deportes y Recreación de La Ilustre Municipalidad de Isla de Pascua": 1,
 "Corporación Municipal de Deportes y Recreación de Mejillones": 1,
 "Corporación Municipal de Deportes y Recreación de Molina": 1,
 "Corporación Municipal de Deportes y Recreación de Panguipulli": 1,
 "Corporación Municipal de Deportes y Recreación de Talcahuano": 1,
 "Corporación Municipal de Deportes y Recreación de Tocopilla": 1,
 "Corporación Municipal de Deportes y Recreación Tomé": 1,
 "Corporación Municipal de desarrollo Comunal y Productivo de Licantén": 1,
 "Corporación Municipal de Desarrollo Económico Cultura y Deporte de Renca": 1,
 "Corporación Municipal de Desarrollo Económico de Peñalolén (YUNUS)": 1,
 "Corporación Municipal de Desarrollo Productivo y Turismo de Molina": 1,
 "Corporación Municipal de Desarrollo Social de Antofagasta (CMDS)": 1,
 "Corporación Municipal de Desarrollo Social de Calama (COMDES)": 1,
 "Corporación Municipal de Desarrollo Social de Los Muermos": 1,
 "Corporación Municipal de Desarrollo Social de San Joaquin": 1,
 "Corporación Municipal de Desarrollo Social de Tiltil": 1,
 "Corporación Municipal de Desarrollo Social de Ñuñoa": 1,
 "Corporación Municipal de Educación y Salud de San Bernardo": 1,
 "Corporación Municipal de Educación y Servicios Ramón Freire Dalcahue": 1,
 "Corporación Municipal de Fomento Al Desarrollo Comunal y Productivo de La Florida (Cofodep)": 1,
 "Corporación Municipal de Fomento al Desarrollo Comunal y Productivo de Parral": 1,
 "Corporación Municipal de Fomento Al Desarrollo Económico y Productivo de Estación Central": 1,
 "Corporación Municipal de Fomento Productivo de Curicó": 1,
 "Corporación Municipal de Fomento y Desarrollo Comunal de Sierra Gorda": 1,
 "Corporación Municipal de innovación y desarrollo económico y social de SAN JOAQUÍN": 1,
 "Corporación Municipal de La Cultura y Las Artes de San Antonio": 1,
 "Corporación Municipal de La Reina": 1,
 "Corporación Municipal de las Artes y la Cultura de Río Claro": 0,
 "Corporación Municipal de Lo Prado": 1,
 "Corporación Municipal de Macul": 1,
 "Corporación Municipal de Maria Pinto": 1,
 "Corporación Municipal de Melipilla": 1,
 "Corporación Municipal de Peñalolén (CORMUP)": 1,
 "Corporación Municipal de Pirque": 1,
 "Corporación Municipal de Pozo Almonte": 1,
 "Corporación Municipal de Providencia": 1,
 "Corporación Municipal de Pudahuel": 1,
 "Corporación Municipal de Puente Alto": 1,
 "Corporación Municipal de Punta Arenas para la Educación Salud y Atención al Menor (CORMUPA)": 1,
 "Corporación Municipal de Puqueldón": 1,
 "Corporación Municipal de Queilen": 1,
 "Corporación Municipal de Quellón": 1,
 "Corporación Municipal de Quilpué": 1,
 "Corporación Municipal de Quinchao": 1,
 "Corporación Municipal de Quinta Normal": 1,
 "Corporación Municipal de Rancagua (CORMUN)": 1,
 "Corporación Municipal de Renca": 1,
 "Corporación Municipal de Salud de Panguipulli": 1,
 "Corporación Municipal de San Fernando (CORMUSAF)": 1,
 "Corporación Municipal de San Vicente": 1,
 "Corporación Municipal de Servicios y Desarrollo de Maipú (CODEDUC)": 1,
 "Corporación Municipal de Talagante": 1,
 "Corporación Municipal de Turismo Coquimbo": 1,
 "Corporación Municipal de Turismo de Paihuano": 1,
 "Corporación Municipal de Turismo de Vicuña": 1,
 "Corporación Municipal de Valparaíso": 1,
 "Corporación Municipal del Arte y la Cultura de Talagante": 1,
 "Corporación Municipal del Deporte de Vitacura": 1,
 "Corporación Municipal Deportiva Cultural y de Fomento Productivo Alto Hospicio": 1,
 "Corporación Municipal Isla de Maipo": 1,
 "Corporación Municipal Para El Desarrollo Cultural de Temuco": 1,
 "Corporación Municipal para el Desarrollo Social de Villa Alemana": 1,
 "Corporación Municipal Pueblito de Las Vizcachas": 1,
 "Corporación Municipal Viña del Mar para el Desarrollo Social": 0,
 "Corporación Nacional de Desarrollo Indígena (CONADI)": 0,
 "Corporación Nacional Forestal (CONAF)": 0,
 "Corporación Para El Desarrollo de La Provincia de Osorno (Corposorno)": 1,
 "Corporación Para El Desarrollo Productivo del Turismo de Alto del Carmen": 1,
 "Corporación Regional de Desarrollo de la Región del Biobío (Desarrolla Biobío)": 0,
 "Corporación Regional de Desarrollo Productivo de la Región de Tarapacá": 0,
 "Corporación Regional de Investigación y Desarrollo Centro de Investigación en Ecosistemas de la Patagonia": 0,
 "Corporación Regional de Turismo de la Región de Valparaíso": 0,
 "Corporación Regional de Turismo de la Región Metropolitana": 0,
 "Corporación Regional del Desarrollo Productivo del Maule": 0,
 "Corporación Santiago Innova": 1,
 "Corporación Social y Cultural de Concepción (SEMCO)": 1,
 "Corporación Teatro Regional Del Biobío": 0,
 "Corporación XIX Juegos Panamericanos Santiago 2023": 1,
 "Defensa Civil de Chile": 0,
 "Defensoría de los Derechos de la Niñez": 0,
 "Defensoría del Contribuyente": 0,
 "Defensoría Penal Pública (DPP)": 0,
 "Delegación Presidencial Provincial de Arauco": 0,
 "Delegación Presidencial Provincial de Aysén": 0,
 "Delegación Presidencial Provincial de Capitán Prat": 0,
 "Delegación Presidencial Provincial de Cardenal Caro": 0,
 "Delegación Presidencial Provincial de Cauquenes": 0,
 "Delegación Presidencial Provincial de Chacabuco": 0,
 "Delegación Presidencial Provincial de Chañaral": 0,
 "Delegación Presidencial Provincial de Chiloé": 0,
 "Delegación Presidencial Provincial de Choapa": 0,
 "Delegación Presidencial Provincial de Colchagua": 0,
 "Delegación Presidencial Provincial de Cordillera": 0,
 "Delegación Presidencial Provincial de Curicó": 0,
 "Delegación Presidencial Provincial de El Loa": 0,
 "Delegación Presidencial Provincial de General Carrera": 0,
 "Delegación Presidencial Provincial de Huasco": 0,
 "Delegación Presidencial Provincial de Isla de Pascua": 0,
 "Delegación Presidencial Provincial de Itata": 0,
 "Delegación Presidencial Provincial de La Antártica Chilena": 0,
 "Delegación Presidencial Provincial de Limarí": 0,
 "Delegación Presidencial Provincial de Linares": 0,
 "Delegación Presidencial Provincial de Los Andes": 0,
 "Delegación Presidencial Provincial de Maipo": 0,
 "Delegación Presidencial Provincial de Malleco": 0,
 "Delegación Presidencial Provincial de Marga Marga": 0,
 "Delegación Presidencial Provincial de Melipilla": 0,
 "Delegación Presidencial Provincial de Osorno": 0,
 "Delegación Presidencial Provincial de Palena": 0,
 "Delegación Presidencial Provincial de Parinacota": 0,
 "Delegación Presidencial Provincial de Petorca": 0,
 "Delegación Presidencial Provincial de Punilla": 0,
 "Delegación Presidencial Provincial de Quillota": 0,
 "Delegación Presidencial Provincial de San Antonio": 0,
 "Delegación Presidencial Provincial de San Felipe": 0,
 "Delegación Presidencial Provincial de Talagante": 0,
 "Delegación Presidencial Provincial de Tamarugal": 0,
 "Delegación Presidencial Provincial de Tierra del Fuego": 0,
 "Delegación Presidencial Provincial de Tocopilla": 0,
 "Delegación Presidencial Provincial de última Esperanza": 0,
 "Delegación Presidencial Provincial del Bíobío": 0,
 "Delegación Presidencial Provincial del Ranco": 0,
 "Delegación Presidencial Regional de Antofagasta": 0,
 "Delegación Presidencial Regional de Arica y Parinacota": 0,
 "Delegación Presidencial Regional de Atacama": 0,
 "Delegación Presidencial Regional de Aysén del General Carlos Ibáñez del Campo": 0,
 "Delegación Presidencial Regional de Coquimbo": 0,
 "Delegación Presidencial Regional de La Araucanía": 0,
 "Delegación Presidencial Regional de Los Lagos": 0,
 "Delegación Presidencial Regional de Los Ríos": 0,
 "Delegación Presidencial Regional de Magallanes y la Antártica Chilena": 0,
 "Delegación Presidencial Regional de Tarapacá": 0,
 "Delegación Presidencial Regional de Valparaíso": 0,
 "Delegación Presidencial Regional de Ñuble": 0,
 "Delegación Presidencial Regional del Biobío": 0,
 "Delegación Presidencial Regional del Libertador General Bernardo OHiggins": 0,
 "Delegación Presidencial Regional del Maule": 0,
 "Delegación Presidencial Regional Metropolitana": 0,
 "Dirección de Aeropuertos (DAP)": 0,
 "Dirección de Arquitectura (DARQ)": 0,
 "Dirección de Compras y Contratación Pública (CHILECOMPRA)": 0,
 "Dirección de Contabilidad y Finanzas (DCYF)": 0,
 "Dirección de Educación Pública": 0,
 "Dirección de Obras Hidráulicas (DOH)": 0,
 "Dirección de Obras Portuarias (DOP)": 0,
 "Dirección de Planeamiento (DIRPLAN)": 0,
 "Dirección de Presupuestos (DIPRES)": 0,
 "Dirección de Previsión de Carabineros de Chile (DIPRECA)": 0,
 "Dirección de Vialidad (VIALIDAD)": 0,
 "Dirección del Trabajo (DT)": 0,
 "Dirección General de Aeronáutica Civil (DGAC)": 0,
 "Dirección General de Aguas (DGA)": 0,
 "Dirección General de Concesiones (DGC)": 0,
 "Dirección General de Crédito Prendario (DICREP)": 0,
 "Dirección General de Movilización Nacional (DGMN)": 0,
 "Dirección General de Obras Públicas (DGOP)": 0,
 "Dirección General de Relaciones Económicas Internacionales (DIRECON)": 0,
 "Dirección Nacional de Fronteras y Límites del Estado (DIFROL)": 0,
 "Dirección Nacional del Servicio Civil": 0,
 "Ejército de Chile": 0,
 "Estado Mayor Conjunto (EMCO)": 0,
 "Ex Consejo Nacional de la Cultura y las Artes (CNCA)": 0,
 "Fiscalía de Obras Públicas": 0,
 "Fiscalía Nacional Económica (FNE)": 0,
 "Fondo de Solidaridad e Inversión Social (FOSIS)": 0,
 "Fondo Nacional de Salud (FONASA)": 0,
 "Fuerza Aérea de Chile (Incluye al Servicio Aerofotogramétrico)": 0,
 "Fundación Artesanías de Chile": 0,
 "Fundación Centro Cultural de Lo Prado": 0,
 "Fundación Centro Cultural Palacio de La Moneda": 0,
 "Fundación Cultural de la municipalidad de Tocopilla": 0,
 "Fundación Cultural de Sierra Gorda": 0,
 "Fundación Cultural Providencia": 0,
 "Fundación de Comunicación Capacitación y Cultura del Agro (FUCOA)": 0,
 "Fundación de Cultura y Turismo de la Municipalidad de Mejillones": 0,
 "Fundación de desarrollo social de Quillota (BANAMOR)": 0,
 "Fundación de Orquestas Juveniles e Infantiles de Chile (FOJI)": 0,
 "Fundación del deporte de Punta Arenas": 0,
 "Fundación Integra": 0,
 "Fundación para el Desarrollo de la Cultura y las Artes de la comuna de Punta Arenas": 0,
 "Fundación para la Promoción y Desarrollo de la Mujer  (PRODEMU)": 0,
 "Fundación Teatro Municipal de Las Condes": 0,
 "Fundación Tiempos Nuevos (MIM)": 0,
 "Gendarmería de Chile": 0,
 "Gobierno Regional de Antofagasta (GORE)": 0,
 "Gobierno Regional de Arica y Parinacota (GORE)": 0,
 "Gobierno Regional de Atacama (GORE)": 0,
 "Gobierno Regional de Aysén (GORE Aysén)": 0,
 "Gobierno Regional de Coquimbo  GORECOQUIMBO": 0,
 "Gobierno Regional de La Araucanía (Gore Araucanía)": 0,
 "Gobierno Regional de Los Lagos (Gore Los Lagos)": 0,
 "Gobierno Regional de Los Ríos (GORE de Los Ríos)": 0,
 "Gobierno Regional de Magallanes y de la Antártica Chilena (GORE Magallanes)": 0,
 "Gobierno Regional de OHiggins (Gore OHiggins)": 0,
 "Gobierno Regional de Tarapacá (GORE)": 0,
 "Gobierno Regional de Valparaíso  (GORE)": 0,
 "Gobierno Regional de Ñuble (GORE)": 0,
 "Gobierno Regional del Bío Bío (Gore Bío Bío)": 0,
 "Gobierno Regional del Maule (Gore Maule)": 0,
 "Gobierno Regional Metropolitano de Santiago  (GORE Metropolitano)": 0,
 "Hospital Barros Luco": 0,
 "Hospital Base de Valdivia": 0,
 "Hospital Carlos Van Buren": 0,
 "Hospital Claudio Vicuña de San Antonio": 0,
 "Hospital Clínico Dra. Eloísa Díaz I. La Florida": 0,
 "Hospital Clínico Magallanes Dr Lautaro Navarro Aravia": 0,
 "Hospital Clínico Metropolitano La Florida Dra. Eloísa Díaz Insunza": 0,
 "Hospital de Curicó": 0,
 "Hospital de las Higueras": 0,
 "Hospital de Linares": 0,
 "Hospital de Lota": 0,
 "Hospital de Melipilla": 0,
 "Hospital de Osorno": 0,
 "Hospital de Ovalle": 0,
 "Hospital de Puerto Montt": 0,
 "Hospital de Quilpué": 0,
 "Hospital de San Camilo": 0,
 "Hospital de San Carlos": 0,
 "Hospital de Tomé": 0,
 "Hospital de Urgencia Asistencia Pública (HUAP)": 0,
 "Hospital de Victoria": 0,
 "Hospital del Salvador": 0,
 "Hospital Dr. Augusto Riffart de Castro": 0,
 "Hospital Dr. Carlos Cisternas De Calama": 0,
 "Hospital Dr. Exequiel González Cortes": 0,
 "Hospital Dr. Hernán Henríquez Aravena de Temuco": 0,
 "Hospital Dr. Mauricio Heyermann Torres de Angol": 0,
 "Hospital Eduardo Pereira de Valparaíso": 0,
 "Hospital El Carmen Dr. Luis Valentín Ferrada": 0,
 "Hospital El Pino": 0,
 "Hospital Ernesto Torres de Iquique": 0,
 "Hospital Franco Ravera Zunino": 0,
 "Hospital Félix Bulnes": 0,
 "Hospital Guillermo Grant Benavente de Concepción": 0,
 "Hospital Gustavo Fricke": 0,
 "Hospital Herminda Martin": 0,
 "Hospital Juan Noé de Arica": 0,
 "Hospital La Serena": 0,
 "Hospital Leonardo Guzmán de Antofagasta": 0,
 "Hospital Luis Calvo Mackenna": 0,
 "Hospital Luis Tisné": 0,
 "Hospital Padre Hurtado": 0,
 "Hospital Regional Copiapó San José del Carmen": 0,
 "Hospital Regional Coyhaique": 0,
 "Hospital Regional de Rancagua": 0,
 "Hospital Regional de Talca": 0,
 "Hospital Roberto del Río": 0,
 "Hospital San Borja Arriarán": 0,
 "Hospital San José de Coronel": 0,
 "Hospital San José": 0,
 "Hospital San Juan de Dios de Los Andes": 0,
 "Hospital San Juan de Dios de San Fernando": 0,
 "Hospital San Juan de Dios": 0,
 "Hospital San Martín de Quillota": 0,
 "Hospital San Pablo de Coquimbo": 0,
 "Hospital Sótero del Río": 0,
 "Hospital Víctor Ríos Ruiz de Los Angeles": 0,
 "I. Municipalidad de Macul": 1,
 "I. Municipalidad de Negrete": 1,
 "I. Municipalidad de Penco": 1,
 "Ilustre Municipalidad de Constitución": 1,
 "Ilustre Municipalidad de Olivar": 1,
 "Instituto Antártico Chileno (INACH)": 0,
 "Instituto de Desarrollo Agropecuario (INDAP)": 0,
 "Instituto de Neurocirugía": 0,
 "Instituto de Previsión Social (IPS)": 0,
 "Instituto de Salud Pública (ISP)": 0,
 "Instituto de Seguridad Laboral (ISL)": 0,
 "Instituto Forestal (INFOR)": 0,
 "Instituto Nacional de Derechos Humanos (INDH)": 0,
 "Instituto Nacional de Desarrollo Sustentable de la Pesca Artesanal y de la Acuicultura de Pequeña Escala (INDESPA)": 0,
 "Instituto Nacional de Estadisticas (INE)": 0,
 "Instituto Nacional de Geriatría (INGER)": 0,
 "Instituto Nacional de Hidráulica (INH)": 0,
 "Instituto Nacional de la Juventud (INJUV)": 0,
 "Instituto Nacional de Propiedad Industrial (INAPI)": 0,
 "Instituto Nacional de Rehabilitación Pedro Aguirre Cerda": 0,
 "Instituto Nacional del Cáncer": 0,
 "Instituto Nacional del Deporte (IND)": 0,
 "Instituto Nacional del Tórax": 0,
 "Instituto Psiquiátrico": 0,
 "Instituto Traumatológico": 0,
 "Junta de Aeronáutica Civil (JAC)": 0,
 "Junta Nacional de Auxilio Escolar y Becas (JUNAEB)": 0,
 "Junta Nacional de Jardines Infantiles (JUNJI)": 0,
 "Municipalidad de Algarrobo": 1,
 "Municipalidad de Alhué": 1,
 "Municipalidad de Alto Biobío": 1,
 "Municipalidad de Alto del Carmen": 1,
 "Municipalidad de Andacollo": 1,
 "Municipalidad de Angol": 1,
 "Municipalidad de Antofagasta": 1,
 "Municipalidad de Antuco": 1,
 "Municipalidad de Arauco": 1,
 "Municipalidad de Arica": 1,
 "Municipalidad de Aysén": 1,
 "Municipalidad de Buin": 1,
 "Municipalidad de Bulnes": 1,
 "Municipalidad de Cabildo": 1,
 "Municipalidad de Cabo de Hornos y Antártica": 1,
 "Municipalidad de Calama": 1,
 "Municipalidad de Calbuco": 1,
 "Municipalidad de Caldera": 1,
 "Municipalidad de Calera de Tango": 1,
 "Municipalidad de Calle Larga": 1,
 "Municipalidad de Camarones": 1,
 "Municipalidad de Camiña": 1,
 "Municipalidad de Canela": 1,
 "Municipalidad de Carahue": 1,
 "Municipalidad de Cartagena": 1,
 "Municipalidad de Casablanca": 1,
 "Municipalidad de Catemu": 1,
 "Municipalidad de Cauquenes": 1,
 "Municipalidad de Cañete": 1,
 "Municipalidad de Cerrillos": 1,
 "Municipalidad de Cerro Navia": 1,
 "Municipalidad de Chaitén": 1,
 "Municipalidad de Chanco": 1,
 "Municipalidad de Chañaral": 1,
 "Municipalidad de Chiguayante": 1,
 "Municipalidad de Chile Chico": 1,
 "Municipalidad de Chillán Viejo": 1,
 "Municipalidad de Chillán": 1,
 "Municipalidad de Chimbarongo": 1,
 "Municipalidad de Cholchol": 1,
 "Municipalidad de Chonchi": 1,
 "Municipalidad de Chépica": 1,
 "Municipalidad de Cisnes": 1,
 "Municipalidad de Cobquecura": 1,
 "Municipalidad de Cochamó": 1,
 "Municipalidad de Cochrane": 1,
 "Municipalidad de Codegua": 1,
 "Municipalidad de Coelemu": 1,
 "Municipalidad de Coihueco": 1,
 "Municipalidad de Coinco": 1,
 "Municipalidad de Colbún": 1,
 "Municipalidad de Colchane": 1,
 "Municipalidad de Colina": 1,
 "Municipalidad de Collipulli": 1,
 "Municipalidad de Coltauco": 1,
 "Municipalidad de Combarbalá": 1,
 "Municipalidad de Concepción": 1,
 "Municipalidad de Conchalí": 1,
 "Municipalidad de Coquimbo": 1,
 "Municipalidad de Coronel": 1,
 "Municipalidad de Corral": 1,
 "Municipalidad de Coyhaique": 1,
 "Municipalidad de Cunco": 1,
 "Municipalidad de Curacautín": 1,
 "Municipalidad de Curaco de Vélez": 1,
 "Municipalidad de Curanilahue": 1,
 "Municipalidad de Curarrehue": 1,
 "Municipalidad de Curicó": 1,
 "Municipalidad de Dalcahue": 1,
 "Municipalidad de Diego de Almagro": 1,
 "Municipalidad de Doñihue": 1,
 "Municipalidad de El Bosque": 1,
 "Municipalidad de El Carmen": 1,
 "Municipalidad de El Monte": 1,
 "Municipalidad de El Quisco": 1,
 "Municipalidad de El Tabo": 1,
 "Municipalidad de Empedrado": 1,
 "Municipalidad de Ercilla": 1,
 "Municipalidad de Estación Central": 1,
 "Municipalidad de Florida": 1,
 "Municipalidad de Freire": 1,
 "Municipalidad de Freirina": 1,
 "Municipalidad de Fresia": 1,
 "Municipalidad de Frutillar": 1,
 "Municipalidad de Futaleufú": 1,
 "Municipalidad de Futrono": 1,
 "Municipalidad de Galvarino": 1,
 "Municipalidad de General Lagos": 1,
 "Municipalidad de Gorbea": 1,
 "Municipalidad de Graneros": 1,
 "Municipalidad de Guaitecas": 1,
 "Municipalidad de Hijuelas": 1,
 "Municipalidad de Hualaihué": 1,
 "Municipalidad de Hualpén": 1,
 "Municipalidad de Hualqui": 1,
 "Municipalidad de Huara": 1,
 "Municipalidad de Huasco": 1,
 "Municipalidad de Huechuraba": 1,
 "Municipalidad de Illapel": 1,
 "Municipalidad de Independencia": 1,
 "Municipalidad de Iquique": 1,
 "Municipalidad de Isla de Maipo": 1,
 "Municipalidad de Isla de Pascua (Rapa Nui)": 1,
 "Municipalidad de Juan Fernández": 1,
 "Municipalidad de La Calera": 1,
 "Municipalidad de La Cisterna": 1,
 "Municipalidad de La Cruz": 1,
 "Municipalidad de La Estrella": 1,
 "Municipalidad de La Florida": 1,
 "Municipalidad de La Granja": 1,
 "Municipalidad de La Higuera": 1,
 "Municipalidad de La Ligua": 1,
 "Municipalidad de La Pintana": 1,
 "Municipalidad de La Reina": 1,
 "Municipalidad de La Serena": 1,
 "Municipalidad de La Unión": 1,
 "Municipalidad de Lago Ranco": 1,
 "Municipalidad de Lago Verde": 1,
 "Municipalidad de Laguna Blanca": 1,
 "Municipalidad de Laja": 1,
 "Municipalidad de Lampa": 1,
 "Municipalidad de Lanco": 1,
 "Municipalidad de Las Cabras": 1,
 "Municipalidad de Lautaro": 1,
 "Municipalidad de Lebu": 1,
 "Municipalidad de Licantén": 1,
 "Municipalidad de Limache": 1,
 "Municipalidad de Linares": 1,
 "Municipalidad de Litueche": 1,
 "Municipalidad de Llanquihue": 1,
 "Municipalidad de Llay Llay": 1,
 "Municipalidad de Lo Barnechea": 1,
 "Municipalidad de Lo Espejo": 1,
 "Municipalidad de Lo Prado": 1,
 "Municipalidad de Lolol": 1,
 "Municipalidad de Loncoche": 1,
 "Municipalidad de Lonquimay": 1,
 "Municipalidad de Los Alamos": 1,
 "Municipalidad de Los Andes": 1,
 "Municipalidad de Los Lagos": 1,
 "Municipalidad de Los Muermos": 1,
 "Municipalidad de Los Sauces": 1,
 "Municipalidad de Los Vilos": 1,
 "Municipalidad de Los Ángeles": 1,
 "Municipalidad de Lumaco": 1,
 "Municipalidad de Machalí": 1,
 "Municipalidad de Maipú": 1,
 "Municipalidad de Malloa": 1,
 "Municipalidad de Marchige": 1,
 "Municipalidad de Mariquina": 1,
 "Municipalidad de María Elena": 1,
 "Municipalidad de María Pinto": 1,
 "Municipalidad de Maule": 1,
 "Municipalidad de Maullín": 1,
 "Municipalidad de Mejillones": 1,
 "Municipalidad de Melipeuco": 1,
 "Municipalidad de Melipilla": 1,
 "Municipalidad de Molina": 1,
 "Municipalidad de Monte Patria": 1,
 "Municipalidad de Mostazal": 1,
 "Municipalidad de Mulchén": 1,
 "Municipalidad de Máfil": 1,
 "Municipalidad de Nacimiento": 1,
 "Municipalidad de Nancagua": 1,
 "Municipalidad de Navidad": 1,
 "Municipalidad de Ninhue": 1,
 "Municipalidad de Nogales": 1,
 "Municipalidad de OHiggins": 1,
 "Municipalidad de Ollague": 1,
 "Municipalidad de Olmué": 1,
 "Municipalidad de Osorno": 1,
 "Municipalidad de Ovalle": 1,
 "Municipalidad de Padre Hurtado": 1,
 "Municipalidad de Padre Las Casas": 1,
 "Municipalidad de Paihuano": 1,
 "Municipalidad de Paillaco": 1,
 "Municipalidad de Paine": 1,
 "Municipalidad de Palena": 1,
 "Municipalidad de Palmilla": 1,
 "Municipalidad de Panguipulli": 1,
 "Municipalidad de Panquehue": 1,
 "Municipalidad de Papudo": 1,
 "Municipalidad de Paredones": 1,
 "Municipalidad de Parral": 1,
 "Municipalidad de Pedro Aguirre Cerda": 1,
 "Municipalidad de Pelarco": 1,
 "Municipalidad de Pelluhue": 1,
 "Municipalidad de Pemuco": 1,
 "Municipalidad de Pencahue": 1,
 "Municipalidad de Peralillo": 1,
 "Municipalidad de Perquenco": 1,
 "Municipalidad de Petorca": 1,
 "Municipalidad de Peumo": 1,
 "Municipalidad de Peñaflor": 1,
 "Municipalidad de Peñalolén": 1,
 "Municipalidad de Pica": 1,
 "Municipalidad de Pichidegua": 1,
 "Municipalidad de Pichilemu": 1,
 "Municipalidad de Pinto": 1,
 "Municipalidad de Pirque": 1,
 "Municipalidad de Pitrufquén": 1,
 "Municipalidad de Placilla": 1,
 "Municipalidad de Portezuelo": 1,
 "Municipalidad de Porvenir": 1,
 "Municipalidad de Pozo Almonte": 1,
 "Municipalidad de Primavera": 1,
 "Municipalidad de Providencia": 1,
 "Municipalidad de Puchuncaví": 1,
 "Municipalidad de Pucón": 1,
 "Municipalidad de Pudahuel": 1,
 "Municipalidad de Puente Alto": 1,
 "Municipalidad de Puerto Montt": 1,
 "Municipalidad de Puerto Natales": 1,
 "Municipalidad de Puerto Octay": 1,
 "Municipalidad de Puerto Varas": 1,
 "Municipalidad de Pumanque": 1,
 "Municipalidad de Punitaqui": 1,
 "Municipalidad de Punta Arenas": 1,
 "Municipalidad de Puqueldón": 1,
 "Municipalidad de Purranque": 1,
 "Municipalidad de Putaendo": 1,
 "Municipalidad de Putre": 1,
 "Municipalidad de Puyehue": 1,
 "Municipalidad de Queilén": 1,
 "Municipalidad de Quellón": 1,
 "Municipalidad de Quemchi": 1,
 "Municipalidad de Quilaco": 1,
 "Municipalidad de Quilicura": 1,
 "Municipalidad de Quilleco": 1,
 "Municipalidad de Quillota": 1,
 "Municipalidad de Quillón": 1,
 "Municipalidad de Quilpué": 1,
 "Municipalidad de Quinchao": 1,
 "Municipalidad de Quinta Normal": 1,
 "Municipalidad de Quintero": 1,
 "Municipalidad de Quirihue": 1,
 "Municipalidad de Rancagua": 1,
 "Municipalidad de Rauco": 1,
 "Municipalidad de Renaico": 1,
 "Municipalidad de Renca": 1,
 "Municipalidad de Rengo": 1,
 "Municipalidad de Requínoa": 1,
 "Municipalidad de Retiro": 1,
 "Municipalidad de Rinconada": 1,
 "Municipalidad de Rio Bueno": 1,
 "Municipalidad de Romeral": 1,
 "Municipalidad de Ránquil": 1,
 "Municipalidad de Río Claro": 1,
 "Municipalidad de Río Hurtado": 1,
 "Municipalidad de Río Ibáñez": 1,
 "Municipalidad de Río Negro": 1,
 "Municipalidad de Río Verde": 1,
 "Municipalidad de Saavedra": 1,
 "Municipalidad de Sagrada Familia": 1,
 "Municipalidad de Salamanca": 1,
 "Municipalidad de San Antonio": 1,
 "Municipalidad de San Bernardo": 1,
 "Municipalidad de San Carlos": 1,
 "Municipalidad de San Clemente": 1,
 "Municipalidad de San Esteban": 1,
 "Municipalidad de San Fabián": 1,
 "Municipalidad de San Felipe": 1,
 "Municipalidad de San Fernando": 1,
 "Municipalidad de San Gregorio": 1,
 "Municipalidad de San Ignacio": 1,
 "Municipalidad de San Javier": 1,
 "Municipalidad de San Joaquín": 1,
 "Municipalidad de San José de Maipo": 1,
 "Municipalidad de San Juan de la Costa": 1,
 "Municipalidad de San Miguel": 1,
 "Municipalidad de San Nicolás": 1,
 "Municipalidad de San Pablo": 1,
 "Municipalidad de San Pedro De La Paz": 1,
 "Municipalidad de San Pedro": 1,
 "Municipalidad de San Rafael": 1,
 "Municipalidad de San Ramón": 1,
 "Municipalidad de San Rosendo": 1,
 "Municipalidad de San Vicente de Tagua Tagua": 1,
 "Municipalidad de Santa Bárbara": 1,
 "Municipalidad de Santa Cruz": 1,
 "Municipalidad de Santa Juana": 1,
 "Municipalidad de Santa María": 1,
 "Municipalidad de Santiago": 1,
 "Municipalidad de Santo Domingo": 1,
 "Municipalidad de Sierra Gorda": 1,
 "Municipalidad de Talagante": 1,
 "Municipalidad de Talca": 1,
 "Municipalidad de Talcahuano": 1,
 "Municipalidad de Taltal": 1,
 "Municipalidad de Teno": 1,
 "Municipalidad de Teodoro Schmidt": 1,
 "Municipalidad de Tierra Amarilla": 1,
 "Municipalidad de Tiltil": 1,
 "Municipalidad de Timaukel": 1,
 "Municipalidad de Tirúa": 1,
 "Municipalidad de Tocopilla": 1,
 "Municipalidad de Toltén": 1,
 "Municipalidad de Tome": 1,
 "Municipalidad de Torres del Paine": 1,
 "Municipalidad de Tortel": 1,
 "Municipalidad de Traiguén": 1,
 "Municipalidad de Trehuaco": 1,
 "Municipalidad de Tucapel": 1,
 "Municipalidad de Valdivia": 1,
 "Municipalidad de Vallenar": 1,
 "Municipalidad de Valparaíso": 1,
 "Municipalidad de Vichuquén": 1,
 "Municipalidad de Victoria": 1,
 "Municipalidad de Vicuña": 1,
 "Municipalidad de Vilcún": 1,
 "Municipalidad de Villa Alegre": 1,
 "Municipalidad de Villa Alemana": 1,
 "Municipalidad de Villarrica": 1,
 "Municipalidad de Vitacura": 1,
 "Municipalidad de Viña del Mar": 1,
 "Municipalidad de Yerbas Buenas": 1,
 "Municipalidad de Yumbel": 1,
 "Municipalidad de Yungay": 1,
 "Municipalidad de Zapallar": 1,
 "Municipalidad de Ñiquén": 1,
 "Municipalidad de Ñuñoa": 1,
 "Oficinas de Estudios y Políticas Agrarias (ODEPA)": 0,
 "Organismo de Capacitación (CPLT)": 0,
 "Organismo de Capacitación (Prueba)": 0,
 "Parque Metropolitano de Santiago": 0,
 "Partido Ciudadanos": 0,
 "Policía de Investigaciones (PDI)": 0,
 "Presidencia de la República": 0,
 "SEREMI de Salud  de Antofagasta": 0,
 "SEREMI de Salud  de Arica y Parinacota": 0,
 "SEREMI de Salud  de Atacama": 0,
 "SEREMI de Salud  de Coquimbo": 0,
 "SEREMI de Salud  de Tarapacá": 0,
 "SEREMI de Salud  de Valparaíso": 0,
 "SEREMI de Salud  Metropolitano de Santiago": 0,
 "SEREMI de Salud de Aysén": 0,
 "SEREMI de Salud de La Araucanía": 0,
 "SEREMI de Salud de Los Ríos": 0,
 "SEREMI de Salud de Magallanes y Antártica Chilena": 0,
 "SEREMI de Salud de OHiggins": 0,
 "SEREMI de Salud del Bío Bío": 0,
 "SEREMI de Salud del Maule": 0,
 "SEREMI de Salud del Ñuble": 0,
 "SEREMI de Salud región de Los Lagos": 0,
 "SEREMI de Vivienda y Urbanismo Región de Antofagasta": 0,
 "SEREMI de Vivienda y Urbanismo Región de Arica y Parinacota": 0,
 "SEREMI de Vivienda y Urbanismo Región de Atacama": 0,
 "SEREMI de Vivienda y Urbanismo Región de Aysén": 0,
 "SEREMI de Vivienda y Urbanismo Región de Bíobio": 0,
 "SEREMI de Vivienda y Urbanismo Región de Coquimbo": 0,
 "SEREMI de Vivienda y Urbanismo Región de La Araucanía": 0,
 "SEREMI de Vivienda y Urbanismo Región de Los Lagos": 0,
 "SEREMI de Vivienda y Urbanismo Región de Los Ríos": 0,
 "SEREMI de Vivienda y Urbanismo Región de Magallanes y Antártica Chilena": 0,
 "SEREMI de Vivienda y Urbanismo Región de Maule": 0,
 "SEREMI de Vivienda y Urbanismo Región de Tarapacá": 0,
 "SEREMI de Vivienda y Urbanismo Región de Valparaíso": 0,
 "SEREMI de Vivienda y Urbanismo Región de Ñuble": 0,
 "SEREMI de Vivienda y Urbanismo Región del Libertador Bernardo OHiggins": 0,
 "SEREMI de Vivienda y Urbanismo Región Metropolitana": 0,
 "Servicio Agrícola y Ganadero (SAG)": 0,
 "Servicio de Biodiversidad y Áreas Protegidas": 0,
 "Servicio de Cooperación Técnica (SERCOTEC)": 0,
 "Servicio de Evaluación Ambiental (SEA)": 0,
 "Servicio de Gobierno Interior": 0,
 "Servicio de Registro Civil e Identificación": 0,
 "Servicio de Salud Aconcagua": 0,
 "Servicio de Salud Antofagasta": 0,
 "SERVICIO DE SALUD ARAUCANIA NORTE": 0,
 "Servicio de Salud Araucanía Sur": 0,
 "Servicio de Salud Arauco": 0,
 "Servicio de Salud Arica y Parinacota": 0,
 "Servicio de Salud Atacama": 0,
 "Servicio de Salud Aysén": 0,
 "Servicio de Salud Bíobío": 0,
 "Servicio de Salud Concepción": 0,
 "Servicio de Salud Coquimbo": 0,
 "Servicio de Salud de Chiloé": 0,
 "Servicio de Salud del Reloncaví": 0,
 "Servicio de Salud Magallanes": 0,
 "Servicio de Salud Maule": 0,
 "Servicio de Salud Metropolitano Central": 0,
 "Servicio de Salud Metropolitano Norte": 0,
 "Servicio de Salud Metropolitano Occidente": 0,
 "Servicio de Salud Metropolitano Oriente": 0,
 "Servicio de Salud Metropolitano Sur Oriente": 0,
 "Servicio de Salud Metropolitano Sur": 0,
 "Servicio de Salud OHiggins": 0,
 "Servicio de Salud Osorno": 0,
 "Servicio de Salud Talcahuano": 0,
 "Servicio de Salud Tarapacá": 0,
 "Servicio de Salud Valdivia": 0,
 "Servicio de Salud Valparaíso  San Antonio": 0,
 "Servicio de Salud Viña del Mar  Quillota": 0,
 "Servicio de Salud Ñuble": 0,
 "Servicio Electoral (SERVEL)": 0,
 "Servicio Local de Educación Pública  Maule Costa": 0,
 "Servicio Local de Educación Pública Aconcagua (SLEP Aconcagua)": 0,
 "Servicio Local de Educación Pública Andalién Sur (SLEP Andalién Sur)": 0,
 "Servicio Local de Educación Pública Atacama (SLEP Atacama)": 0,
 "Servicio Local de Educación Pública Chiloé (SLEP Chiloé)": 0,
 "Servicio Local de Educación Pública Chinchorro (SLEP Chinchorro)": 0,
 "Servicio Local de Educación Pública Colchagua (SLEP Colchagua)": 0,
 "Servicio Local de Educación Pública Costa Araucanía (SLEP Costa Araucanía)": 0,
 "Servicio Local de Educación Pública Costa Central (SLEP Costa Central)": 0,
 "Servicio Local de Educación Pública de Andalién Costa (SLEP Andalién Costa)": 0,
 "Servicio Local de Educación Pública de Antofagasta (SLEP Antofagasta)": 0,
 "Servicio Local de Educación Pública de Aysén (SLEP Aysén)": 0,
 "Servicio Local de Educación Pública de Barrancas (SLEP Barrancas)": 0,
 "Servicio Local de Educación Pública de Iquique (SLEP Iquique)": 0,
 "Servicio Local de Educación Pública de Los Parques": 0,
 "Servicio Local de Educación Pública de Magallanes (SLEP Magallanes)": 0,
 "Servicio Local de Educación Pública del Pino": 0,
 "Servicio Local de Educación Pública del Tamarugal": 0,
 "Servicio Local de Educación Pública Elqui (SLEP Elqui)": 0,
 "Servicio Local de Educación Pública Gabriela Mistral (SLEP Gabriela Mistral)": 0,
 "Servicio Local de Educación Pública Huasco (SLEP Huasco)": 0,
 "Servicio Local de Educación Pública Licancabur": 0,
 "Servicio Local de Educación Pública Llanquihue (SLEP Llanquihue)": 0,
 "Servicio Local de Educación Pública Los Andes (SLEP Los Andes)": 0,
 "Servicio Local de Educación Pública los Libertadores": 0,
 "Servicio Local de Educación Pública Los Álamos (SLEP Los Álamos)": 0,
 "Servicio Local de Educación Pública Marga Marga (SLEP Marga Marga)": 0,
 "Servicio Local de Educación Pública Petorca (SLEP Petorca)": 0,
 "Servicio Local de Educación Pública Puelche (SLEP Puelche)": 0,
 "Servicio Local de Educación Pública Puerto Cordillera": 0,
 "Servicio Local de educación Pública Punilla Cordillera": 0,
 "Servicio Local de Educación Pública Santa Rosa": 0,
 "Servicio Local de Educación Pública Santiago Centro (SLEP Santiago Centro)": 0,
 "Servicio Local de Educación Pública Valdivia (SLEP Valdivia)": 0,
 "Servicio Local de Educación Pública Valle Cachapoal": 0,
 "Servicio Local de Educación Pública Valle Diguillín (SLEP Valle Diguillín)": 0,
 "Servicio Local de Educación Pública Valparaíso (SLEP Valparaíso)": 0,
 "Servicio Localde Educación Pública Santa Corina": 0,
 "Servicio Médico Legal (SML)": 0,
 "Servicio Nacional de Aduanas": 0,
 "Servicio Nacional de Capacitación y Empleo (SENCE)": 0,
 "Servicio Nacional de Geología y Minería (SERNAGEOMIN)": 0,
 "Servicio Nacional de la Discapacidad (SENADIS)": 0,
 "Servicio Nacional de la Mujer y la Equidad de Género (SERNAMEG)": 0,
 "Servicio Nacional de Menores (SENAME)": 0,
 "Servicio Nacional de Migraciones": 0,
 "Servicio Nacional de Pesca y Acuicultura (SERNAPESCA)": 0,
 "Servicio Nacional de Prevención y Respuesta ante Desastres (SENAPRED) ex ONEMI": 0,
 "Servicio Nacional de Prevención y Respuesta ante Desastres (SENAPRED)": 0,
 "Servicio Nacional de Protección Especializada a la Niñez y Adolescencia": 0,
 "Servicio Nacional de Reinserción Social Juvenil": 0,
 "Servicio Nacional de Turismo (SERNATUR)": 0,
 "Servicio Nacional del Adulto Mayor (SENAMA)": 0,
 "Servicio Nacional del Consumidor (SERNAC)": 0,
 "Servicio Nacional del Patrimonio Cultural": 0,
 "Servicio Nacional para la Prevención y Rehabilitación del Consumo de Drogas y Alcohol (SENDA)": 0,
 "SERVIU Metropolitano": 0,
 "SERVIU Región de Antofagasta": 0,
 "SERVIU Región de Arica y Parinacota": 0,
 "SERVIU Región de Atacama": 0,
 "SERVIU Región de Aysén del General Carlos Ibáñez del Campo": 0,
 "SERVIU Región de Coquimbo": 0,
 "SERVIU Región de la Araucanía": 0,
 "SERVIU Región de Los Lagos": 0,
 "SERVIU Región de Los Ríos": 0,
 "SERVIU Región de Magallanes y la Antártica Chilena": 0,
 "SERVIU Región de Tarapacá": 0,
 "SERVIU Región de Valparaíso": 0,
 "SERVIU Región del Bío Bío": 0,
 "SERVIU Región del Libertador Bernardo OHiggins": 0,
 "SERVIU Región del Maule": 0,
 "SERVIU Región del Ñuble": 0,
 "Sistema de Empresas  SEP": 0,
 "Subsecretaría de Agricultura": 0,
 "Subsecretaría de Bienes Nacionales": 0,
 "Subsecretaría de Ciencia Tecnología Conocimiento e Innovación": 0,
 "Subsecretaría de Defensa": 0,
 "Subsecretaría de Derechos Humanos": 0,
 "Subsecretaría de Desarrollo Regional y Administrativo (SUBDERE)": 0,
 "Subsecretaría de Economía (MINECON)": 0,
 "Subsecretaría de Educación (MINEDUC)": 0,
 "Subsecretaría de Educación Parvularia": 0,
 "Subsecretaría de Educación Superior": 0,
 "Subsecretaría de Energía": 0,
 "Subsecretaría de Evaluación Social": 0,
 "Subsecretaría de Hacienda": 0,
 "Subsecretaría de Justicia": 0,
 "Subsecretaría de la Mujer y la Equidad de Género": 0,
 "Subsecretaría de la Niñez": 0,
 "Subsecretaría de las Culturas y las Artes": 0,
 "Subsecretaría de Minería": 0,
 "Subsecretaría de Obras Públicas (MOP)": 0,
 "Subsecretaría de Pesca y Acuicultura": 0,
 "Subsecretaría de Prevención del Delito": 0,
 "Subsecretaría de Previsión Social (SPS)": 0,
 "Subsecretaría de Redes Asistenciales": 0,
 "Subsecretaría de Relaciones Económicas Internacionales": 0,
 "Subsecretaría de Relaciones Exteriores": 0,
 "Subsecretaría de Salud Pública (MINSAL)": 0,
 "Subsecretaría de Seguridad Pública": 0,
 "Subsecretaría de Servicios Sociales": 0,
 "Subsecretaría de Telecomunicaciones (SUBTEL)": 0,
 "Subsecretaría de Transportes (MTT)": 0,
 "Subsecretaría de Turismo": 0,
 "Subsecretaría de Vivienda y Urbanismo (MINVU)": 0,
 "Subsecretaría del Deporte": 0,
 "Subsecretaría del Interior": 0,
 "Subsecretaría del Medio Ambiente (MMA)": 0,
 "Subsecretaría del Patrimonio Cultural": 0,
 "Subsecretaría del Trabajo (MINTRAB)": 0,
 "Subsecretaría General de Gobierno (SEGEGOB)": 0,
 "Subsecretaría General de La Presidencia (SEGPRES)": 0,
 "Subsecretaría para las Fuerzas Armadas (SSFFAA)": 0,
 "Superintendencia de Bancos e Instituciones Financieras (SBIF) derogada por la CMF": 0,
 "Superintendencia de Casinos de Juego (SCJ)": 0,
 "Superintendencia de Educación Dirección Nacional": 0,
 "Superintendencia de Educación Superior": 0,
 "Superintendencia de Electricidad y Combustibles (SEC)": 0,
 "Superintendencia de Insolvencia y Reemprendimiento (SUPERIR)": 0,
 "Superintendencia de Pensiones (SP)": 0,
 "Superintendencia de Salud (SdS)": 0,
 "Superintendencia de Seguridad Social (SUSESO)": 0,
 "Superintendencia de Servicios Sanitarios (SISS)": 0,
 "Superintendencia del Medio Ambiente (SMA)": 0,
 "Tesorería General de la República (TGR)": 0,
 "Unidad de Análisis Financiero": 0,
 "Universidad de Atacama": 0,
 "Universidad de Aysén": 0,
 "Universidad de Los Lagos": 0,
 "Universidad de Magallanes": 0,
 "Universidad de OHiggins (UOH)": 0,
 "Universidad de OHiggins": 0,
 "Universidad de Santiago de Chile (USACH)": 0
};